const assert=require('assert'),fs=require('fs'),path=require('path'),fixture=require('./agent-seven.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb46-browser-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw new Error('只允许隔离本机测试');
function dataFor(n){const code='L'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=Array.from({length:n},(_,i)=>({pid:code+'p'+i,name:'许可界面'+i,credential:code+'凭证'+i,bot:false})),G=fixture(seats),actor=G.turn,ids=G.wires.filter(w=>!w.cut&&w.v===7).map(w=>w.id),observer={pid:code+'watch',name:'许可观众',credential:code+'观战凭证',perspective:null};G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:46,ruleset:'campaign',attempts:1,started:true,seats,observers:[observer],revision:0,seen:[],G}),{mode:0o600});return {code,seats,observer,actor,ids};}
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(let n=2;n<=5;n++){
 const data=dataFor(n),pages=[],contexts=[];let threeD=true;
 try{for(const identity of data.seats.concat([data.observer])){const c=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(c);await c.addInitScript(({code,identity})=>{localStorage.setItem('bb_pid',JSON.stringify(identity.pid));localStorage.setItem('bb_name',JSON.stringify(identity.name));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:identity.credential}));localStorage.setItem('bb_view3d','true');const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...a){super(...a);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,identity});const p=await c.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('#nm').fill(identity.name);await p.locator('#jcode').fill(data.code);await p.locator('#btn-join').click();await p.waitForFunction(()=>window.testView?.official?.module==='agent-seven');}
 const host=pages[0],observer=pages[n];async function views(){const r=Math.max(...await Promise.all(pages.map(p=>p.evaluate(()=>window.testRevision))));await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,r)));return Promise.all(pages.map(p=>p.evaluate(()=>window.testView)));}
 async function advance(f){await views();const r=await host.evaluate(()=>window.testRevision);await f();await host.waitForFunction(r=>window.testRevision>r,r);await views();}
 async function toggle(){for(const p of pages)await p.locator('[data-act=view]').click();threeD=!threeD;}
 await observer.locator('#spectator-perspective').selectOption(data.seats[data.actor].pid);await observer.waitForFunction(pid=>window.testView.perspective===pid,data.seats[data.actor].pid);
 for(let mode=0;mode<2;mode++){const v=await views();for(let pi=0;pi<n;pi++){assert.equal('licenseRequired'in v[pi].official,pi===data.actor);assert.equal(await pages[pi].locator('[data-act=precision-start]:enabled').count(),pi===data.actor?1:0);}assert(!('licenseRequired'in v[n].official));assert.equal(await observer.locator('[data-act=precision-start]').count(),0);for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await toggle();}
 await pages[data.actor].locator('[data-act=precision-start]').click();for(const id of data.ids)await pages[data.actor].locator((threeD?'.slot.can':'.tile.can')+'[data-w="'+id+'"]').click();await advance(()=>pages[data.actor].locator('[data-act=precision-submit]').click());for(const p of pages)assert.equal(await p.locator('.declared-target').count(),4);
 let reloaded=false,replies=0;while((await views())[0].pending){const v=await views(),who=v[0].pending.to,id=v[0].pending.id;for(let pi=0;pi<=n;pi++)assert.equal('ownAnswers'in v[pi].pending,pi===who);assert.equal(await observer.locator('[data-act=precision-reply]').count(),0);
  if(!reloaded){await advance(()=>host.locator('[data-act=host-pause]').click());await pages[who].reload({waitUntil:'domcontentloaded'});await pages[who].locator('#jcode').fill(data.code);await pages[who].locator('#btn-join').click();await pages[who].waitForFunction(id=>window.testView?.pending?.id===id,id);await advance(()=>host.locator('[data-act=host-pause]').click());reloaded=true;}
  await advance(()=>pages[who].locator('[data-act=precision-reply]').click());replies++;
 }
 const v=await views();assert(replies>=2);assert(v[0].official.precision.complete);assert.equal(v[0].det,0);assert(data.ids.every(id=>v[0].players.some(p=>p.stands.some(st=>st.some(w=>w.id===id&&w.cut)))));for(let mode=0;mode<2;mode++){for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await toggle();}
 console.log('✓ 第46关开发版'+n+'人＋观众来源许可阶段手机双视图：本人资格、四目标箭头、逐人私人回应、暂停刷新重连、观战只读和四7成功通过');
 }finally{for(const c of contexts)await c.close();}
}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
