// 第56关隔离来源设置联机检查；公开目录仍保持改编。
const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),{game,setup}=require('./all-outward.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb56-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('朝外夹具只允许隔离本机服务器');
function fixture(n){let G,target,own;for(let seed=1;seed<=400;seed++){G=game(n,0,seed);setup(G);target=G.wires[G.officialState.outwardIds[1]];own=G.wires.find(w=>w.o===0&&!BB.isOutward(G,w)&&w.v===target.v);if(own&&Number.isInteger(target.v))break;}assert(own);const code='O'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:56,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,ids:G.officialState.outwardIds.slice(),target:target.id,value:target.v,own:own.id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'朝外观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='all-outward-wires');}
  for(let mode=0;mode<2;mode++){for(let p=0;p<n;p++){const page=pages[p],V=await page.evaluate(()=>window.testView);assert((await page.locator('.all-outward-notice').innerText()).includes('队友可见'));for(let owner=0;owner<n;owner++){const w=V.players[owner].stands.flat().find(w=>w.id===data.ids[owner]);assert.equal(w.v===null,p===owner);}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="'+data.value+'"]').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');assert((await pages[1].locator('[data-act="resolve-target"]').innerText()).includes('命中'));assert.equal((await pages[1].evaluate(()=>window.testView)).players[1].stands.flat().find(w=>w.id===data.target).v,null);
  for(const page of pages)await page.waitForFunction(()=>window.testView?.pending?.step==='target');for(const page of pages)assert(await page.locator('.declared-target[data-w="'+data.target+'"] .target-arrow').count()>0);
  await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(data.code);await pages[1].locator('#btn-join').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');assert.equal((await pages[0].evaluate(()=>window.testView)).det,0);await pages[0].locator('#scr-game .tile.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>!window.testView?.pending&&window.testView?.det===1)));
  for(const page of pages){assert((await page.locator('#g-main').innerText()).includes('处罚'));const V=await page.evaluate(()=>window.testView);assert(V.players[1].stands.flat().find(w=>w.id===data.target).cut);}
  console.log('✓ 第56关'+n+'人375像素双视图：本人隐藏／队友可见、朝外规则提示／公共目标箭头、目标主人正确确认文字／刷新恢复、选自己之后只罚一次，观战同步；两架位置等例外仍待核实');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
