// 浏览器替换媒体对象检查界面与同步，不请求或认证真实录音。
const assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto'),BB=require('../js/engine'),M=require('../js/missions'),{chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb-audio-browser';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('合成音频夹具只允许本机隔离服务');
const G=BB.createGame(M.get('official-development',54),Array.from({length:3},(_,i)=>({pid:'p'+i,name:'音频界面玩家'+i})));while(G.phase==='setup'){const p=BB.setupActor(G),w=G.wires.find(w=>w.o===p&&BB.setupInfoAllowed(G,w));assert.equal(BB.act(G,p,{a:'info',w:w.id}),null);}const definition={version:1,verified:true,mission:54,contentVersion:G.mission.contentVersion,durationMs:210000,asset:{url:'https://cdn.pegasus.de/合成界面测试.mp3',sha256:crypto.createHash('sha256').update(Buffer.from('合成浏览器录音字节')).digest('hex'),locale:'en'},cues:[{id:'停',atMs:0,type:'hold'},{id:'继续',atMs:100000,type:'resume'},{id:'结束',atMs:200000,type:'fail'}]};assert.equal(BB.initializeAudio(G,definition,{serverAudio:true}),null);assert.equal(BB.advanceAudio(G,{serverAudio:true}).error,null);G.catalog=G.mission.catalog='campaign';const code='A'+Date.now().toString(36).slice(-5).toUpperCase(),seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(path.join(dir,'audio-cache'),{recursive:true});fs.writeFileSync(path.join(dir,'audio-cache',definition.asset.sha256+'.mp3'),Buffer.from('合成浏览器录音字节'));fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:'p0',mid:54,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),contexts=[],pages=[],errors=[];try{
 for(let p=0;p<=3;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}window.testMedia=[];window.Audio=class{constructor(){this.currentTime=0;this.duration=999;this.paused=true;this.plays=0;window.testMedia.push(this);}addEventListener(){}play(){this.plays++;this.paused=false;return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){this.src=null;}load(){}};const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code,seat:seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(seats[p]?.name||'音频观众');await page.locator('#jcode').fill(code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.audio?.cutHeld);assert.equal(await page.evaluate(()=>window.testMedia.length),0);assert.equal(await page.locator('.slot.can').count(),0);if(p<3)await page.waitForFunction(()=>document.querySelector('#g-con')?.innerText.includes('停止操作'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await pages[0].locator('[data-act="audio-prepare"]').click();await pages[0].waitForFunction(()=>document.querySelector('#audio-state')?.innerText.includes('音频已就绪'));assert.equal(await pages[0].evaluate(()=>window.testMedia.length),0);await pages[0].locator('[data-act="audio-enable"]').click();await pages[0].waitForFunction(()=>window.testMedia[0]?.plays===1);const time=await pages[0].evaluate(()=>window.testMedia[0].currentTime);for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();assert.equal(await pages[0].evaluate(()=>window.testMedia.length),1);assert.equal(await pages[0].evaluate(()=>window.testMedia[0].plays),1);assert((await pages[0].evaluate(()=>window.testMedia[0].currentTime))>=time);
 await pages[0].locator('[data-act="host-pause"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.paused)));await pages[0].waitForFunction(()=>window.testMedia[0].paused);const paused=await pages[0].evaluate(()=>window.testMedia[0].currentTime);await pages[0].waitForTimeout(500);assert.equal(await pages[0].evaluate(()=>window.testMedia[0].currentTime),paused);await pages[0].locator('[data-act="host-pause"]').click();await pages[0].waitForFunction(()=>!window.testView.paused&&!window.testMedia[0].paused);assert.equal(await pages[0].evaluate(()=>window.testMedia.length),1);
 await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.audio?.status==='running');assert.equal(await pages[0].evaluate(()=>window.testMedia.length),0);await pages[0].locator('[data-act="audio-prepare"]').click();await pages[0].waitForFunction(()=>document.querySelector('#audio-state')?.innerText.includes('音频已就绪'));assert.equal(await pages[0].evaluate(()=>window.testMedia.length),0);await pages[0].locator('[data-act="audio-enable"]').click();await pages[0].waitForFunction(()=>window.testMedia[0]?.plays===1);assert((await pages[0].evaluate(()=>window.testMedia[0].currentTime))>=paused);for(const page of pages)assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
 console.log('✓ 音频界面三人加观众375像素实际三维到二维：开启前不建媒体、听音期无可点导线、播放按钮跟随服务器位置、切视图不重播、不暂停录音以替代听音；房主暂停冻结媒体／继续恢复、刷新需再次开启且追到当前位置、无异常溢出；替换媒体对象，不认证真实录音或Mac Safari');
}finally{for(const c of contexts)await c.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
