// 浏览器替换媒体对象检查界面与同步，不请求或认证真实录音。
const assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto'),BB=require('../js/engine'),M=require('../js/missions'),{chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb-audio-ready-browser';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('合成音频夹具只允许本机隔离服务');
const G=BB.createGame(M.get('official-development',54),Array.from({length:3},(_,i)=>({pid:'p'+i,name:'音频界面玩家'+i})));while(G.phase==='setup'){const p=BB.setupActor(G),w=G.wires.find(w=>w.o===p&&BB.setupInfoAllowed(G,w));assert.equal(BB.act(G,p,{a:'info',w:w.id}),null);}const definition={version:1,verified:true,mission:54,contentVersion:G.mission.contentVersion,durationMs:210000,asset:{url:'https://cdn.pegasus.de/合成界面测试.mp3',sha256:crypto.createHash('sha256').update(Buffer.from('合成浏览器录音字节')).digest('hex'),locale:'en'},cues:[{id:'停',atMs:0,type:'hold'},{id:'继续',atMs:100000,type:'resume'},{id:'结束',atMs:200000,type:'fail'}]};assert.equal(BB.prepareAudio(G,definition,{serverAudio:true}),null);G.catalog=G.mission.catalog='campaign';const code='A'+Date.now().toString(36).slice(-5).toUpperCase(),seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(path.join(dir,'audio-cache'),{recursive:true});fs.writeFileSync(path.join(dir,'audio-cache',definition.asset.sha256+'.mp3'),Buffer.from('合成浏览器录音字节'));fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:'p0',mid:54,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),contexts=[],pages=[],errors=[];try{
 for(let p=0;p<=3;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}window.testMedia=[];window.Audio=class{constructor(){this.currentTime=0;this.duration=999;this.paused=true;this.plays=0;window.testMedia.push(this);}addEventListener(){}play(){this.plays++;this.paused=false;return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){this.src=null;}load(){}};const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code,seat:seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(seats[p]?.name||'音频观众');await page.locator('#jcode').fill(code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.audio?.status==='waiting');assert.equal(await page.evaluate(()=>window.testMedia.length),0);assert.equal(await page.locator('.slot.can').count(),0);if(p<3)await page.waitForFunction(()=>document.querySelector('#g-con')?.innerText.includes('全员就绪'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 assert(await pages[0].locator('[data-act="audio-start"]').isDisabled());assert.equal(await pages[3].locator('[data-act="audio-ready"]').count(),0);
 for(let p=0;p<3;p++){await pages[p].locator('[data-act="audio-prepare"]').click();await pages[p].waitForFunction(()=>document.querySelector('#audio-state')?.innerText.includes('音频已就绪'));await pages[p].locator('[data-act="audio-enable"]').click();await pages[p].waitForFunction(()=>window.testMedia[0]?.plays===1&&window.testMedia[0].paused);assert.equal(await pages[p].evaluate(()=>window.testMedia[0].currentTime),0);await pages[p].locator('[data-act="audio-ready"]').click();await Promise.all(pages.map(page=>page.waitForFunction(index=>window.testView?.audio?.preparation?.ready[index],p)));}
 await pages[0].waitForFunction(()=>!document.querySelector('[data-act="audio-start"]').disabled);for(const page of pages){assert.equal((await page.evaluate(()=>window.testView)).audio.elapsedMs,0);await page.locator('#scr-game [data-act="view"]').click();}
 await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(code);await pages[1].locator('#btn-join').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.audio?.preparation?.ready[1]===false)));assert(await pages[0].locator('[data-act="audio-start"]').isDisabled());assert.equal(await pages[1].evaluate(()=>window.testMedia.length),0);await pages[1].locator('[data-act="audio-prepare"]').click();await pages[1].waitForFunction(()=>document.querySelector('#audio-state')?.innerText.includes('音频已就绪'));await pages[1].locator('[data-act="audio-enable"]').click();await pages[1].waitForFunction(()=>window.testMedia[0]?.plays===1&&window.testMedia[0].paused);await pages[1].locator('[data-act="audio-ready"]').click();await pages[0].waitForFunction(()=>!document.querySelector('[data-act="audio-start"]').disabled);
 await pages[0].locator('[data-act="audio-start"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.phase==='play'&&window.testView?.audio?.status==='running')));for(let p=0;p<3;p++){await pages[p].waitForFunction(()=>window.testMedia[0]?.plays===2&&!window.testMedia[0].paused);assert.equal(await pages[p].evaluate(()=>window.testMedia.length),1);}for(const page of pages){assert.equal(await page.locator('[data-act="audio-ready"]').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.deepEqual(errors,[]);
 console.log('✓ 音频准备三人加观众375像素双视图：准备／播放许可检查后停在0、自行确认、全员前开始禁用、准备不计时；刷新撤回就绪并重确认、观众不计入准备／不能代确认，房主实际统一开始后沿用同一媒体播放，全员同一时钟，无异常溢出；合成字节／替换媒体非真实任务认证');
}finally{for(const c of contexts)await c.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
