// 合成清单准备流程，不认证任何官方录音信号。
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),BB=require('../js/engine'),M=require('../js/missions'),Service=require('../server/official');
function game(n=3){const G=BB.createGame(M.get('official-development',54),Array.from({length:n},(_,i)=>({pid:'p'+i,name:'就绪玩家'+i})));while(G.phase==='setup'){const p=BB.setupActor(G),w=G.wires.find(w=>w.o===p&&BB.setupInfoAllowed(G,w));assert.equal(BB.act(G,p,{a:'info',w:w.id}),null);}return G;}
function definition(G){return {version:1,verified:true,mission:54,contentVersion:G.mission.contentVersion,durationMs:60000,asset:{url:'https://cdn.pegasus.de/合成就绪.mp3',sha256:'e'.repeat(64),locale:'en'},cues:[{id:'停',atMs:0,type:'hold'},{id:'继续',atMs:10000,type:'resume'},{id:'截止',atMs:50000,type:'fail'}]};}
function reject(G,fn){const before=JSON.stringify(G);assert(fn());assert.equal(JSON.stringify(G),before);}
for(let n=2;n<=5;n++){
 const G=game(n),d=definition(G);reject(G,()=>BB.prepareAudio(G,d,{}));reject(G,()=>BB.prepareAudio(G,{...d,verified:false},{serverAudio:true}));assert.equal(BB.prepareAudio(G,d,{serverAudio:true}),null);const id=G.audioPreparation.id;assert.equal(G.phase,'audio-ready');assert.equal(G.audioClock,undefined);assert.equal(G.deadline,null);assert.equal(BB.view(G,0).audio.status,'waiting');assert.equal(BB.view(G,0).audio.elapsedMs,0);reject(G,()=>BB.initializeAudio(G,d,{serverAudio:true,now:1000}));reject(G,()=>BB.act(G,0,{a:'audio-ready',id:'旧',sha256:d.asset.sha256,ready:true}));reject(G,()=>BB.act(G,0,{a:'audio-ready',id,sha256:'0'.repeat(64),ready:true}));
 for(let pi=0;pi<n;pi++)assert.equal(BB.act(G,pi,{a:'audio-ready',id,sha256:d.asset.sha256,ready:true}),null);const once=JSON.stringify(G);assert.equal(BB.act(G,0,{a:'audio-ready',id,sha256:d.asset.sha256,ready:true}),null);assert.equal(JSON.stringify(G),once);assert.equal(G.audioClock,undefined);const revision=G.audioPreparation.revision;assert.equal(BB.initializeAudio(G,d,{serverAudio:true,now:12345}),null);assert.equal(G.audioClock.startedAt,12345);assert(G.audioClock.revision>revision);assert.equal(G.phase,'play');reject(G,()=>BB.act(G,0,{a:'audio-ready',id,sha256:d.asset.sha256,ready:false},{now:12345}));
}
console.log('✓ 音频准备2–5人：未核实／客户端清单拒绝，准备不建时钟／不计时，各人正确指纹／决定编号就绪、重复不改变状态，全员确认才开始，时钟修订连续、开始后旧就绪无效；合成清单非关卡认证');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb-audio-ready-authority-'));function peer(room){return {room,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}const last=(ws,t)=>ws.messages.filter(m=>m.topic===t).at(-1)?.data;
try{for(let n=2;n<=5;n++){
 const G=game(n),d=definition(G),name='bb-ready'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'就绪凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:'p0',mid:54,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
 function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'就绪观众'});room=service.load(name);}
 function send(pi,key,a){service.handle(peers[pi],'official:act',{gid:room.G.gid,revision:room.revision,commandId:key,action:a});}
 function start(ws,key){service.handle(ws,'official:audio-start',{gid:room.G.gid,revision:room.revision,commandId:key,id:room.G.audioPreparation.id,definition:{verified:true},now:999999});}
 connect();assert.equal(service.prepareAudio(name,d),null);assert(service.audioAsset(d.asset.sha256));const id=room.G.audioPreparation.id;start(peers[0],'太早');assert.equal(room.G.audioClock,undefined);for(let p=0;p<n;p++)send(p,'就绪'+p,{a:'audio-ready',id,sha256:d.asset.sha256,ready:true,pi:0});assert(room.G.audioPreparation.ready.every(Boolean));start(peers[1],'客人开始');assert.equal(room.G.audioClock,undefined);start(observer,'观战开始');assert.equal(room.G.audioClock,undefined);const before=JSON.stringify(room.G);service.handle(observer,'official:act',{gid:room.G.gid,revision:room.revision,commandId:'观战就绪',action:{a:'audio-ready',id,sha256:d.asset.sha256,ready:true}});assert.equal(JSON.stringify(room.G),before);
 peers[1].readyState=3;service.disconnect(peers[1]);assert.equal(room.G.audioPreparation.ready[1],false);start(peers[0],'断线开始');assert.equal(room.G.audioClock,undefined);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(room.G.audioPreparation.ready.every(r=>!r));assert.equal(room.G.audioClock,undefined);assert.equal(room.G.deadline,null);
 for(let p=0;p<n;p++)send(p,'重连就绪'+p,{a:'audio-ready',id,sha256:d.asset.sha256,ready:true});start(peers[0],'房主开始');assert.equal(room.G.phase,'play');assert(room.G.audioClock.startedAt<Date.now()+10);assert(room.G.audioClock.startedAt>999999);const once=JSON.stringify(room.G),revision=room.revision;start(peers[0],'房主开始');assert.equal(room.revision,revision);assert.equal(JSON.stringify(room.G),once);for(const ws of [...peers,observer])assert.equal(last(ws,'official:view').view.audio.status,'running');room.G.paused=true;wss.clients.forEach(ws=>ws.readyState=3);
}}finally{fs.rmSync(dir,{recursive:true,force:true});}
console.log('✓ 权威准备2–5人：自己确认不受pi冒用、客人／观战不能开始或代就绪，断线撤回就绪、快照重新载入后重确认且不计时；同源指纹准备可用，房主用服务器时间启动、客户端时间／清单不采用、重复一次启动、全员同一时钟');
