const assert=require('assert'),P=require('../js/audio-player');
const loader=async()=>({url:'blob:合成验证',release(){}});
function media(){return {currentTime:0,duration:100,paused:true,plays:0,pauses:0,src:null,listeners:{},addEventListener(k,f){this.listeners[k]=f;},play(){this.plays++;this.paused=false;return Promise.resolve();},pause(){this.pauses++;this.paused=true;},removeAttribute(){this.src=null;},load(){}};}
function view(status='running',elapsed=5000,revision=1,time=1000){return {status,elapsedMs:elapsed,serverTime:time,revision,source:{url:'https://cdn.pegasus.de/test.mp3',sha256:'b'.repeat(64)}};}
(async()=>{let now=0,created=0,m;const p=P.create({loadAsset:loader,now:()=>now,makeAudio:()=>{created++;m=media();return m;}}),v=view();p.update('局1',v);assert.equal(created,0);assert.equal(p.status().enabled,false);assert((await p.enable()).includes('准备'));assert.equal(created,0);assert.equal(await p.prepare(),null);assert.equal(await p.enable(),null);assert.equal(created,1);assert.equal(m.currentTime,5);now=2000;m.currentTime=7;p.update('局1',JSON.parse(JSON.stringify(v)));p.sync();assert.equal(m.currentTime,7,'切换视图不能重置旧快照锚点');assert.equal(m.plays,1);p.update('局1',view('running',1000,1,900));p.sync();assert.equal(m.currentTime,7,'迟到快照不能把声音倒回旧位置');
 m.currentTime=2;m.seeking=true;p.sync();assert.equal(m.currentTime,2,'定位未完成时不能反复重新定位');m.seeking=false;p.sync();assert.equal(m.currentTime,7,'漂移超过半秒时追上服务器位置');p.update('局1',view('paused',7300,2,3300));assert(m.paused);assert.equal(m.currentTime,7.3);now=8000;p.sync();assert.equal(m.currentTime,7.3);p.update('局1',view('running',7300,3,9000));assert(!m.paused);assert.equal(m.plays,2);p.update('局1',view('ended',8500,4,10000));assert(m.paused);assert.equal(m.currentTime,8.5);
 p.update('局2',view());assert(m.paused);assert.equal(p.status().enabled,false);assert.equal(created,1);await p.prepare();await p.enable();assert.equal(created,2);p.update('局2',null);assert(m.paused);assert.equal(m.src,null);const bad=view();bad.source.url='http://127.0.0.1/private';p.update('恶意局',bad);assert(p.status().error);await p.prepare();await p.enable();assert.equal(created,2);
 console.log('✓ 本机音频合成媒体：用户开启前不请求录音，同一快照／切换视图不重播，漂移修正、暂停冻结／恢复／截止停止、换局需重新开启、离局释放；非发行商／本机地址不播放，播放器没有服务器推进入口');
 let rejectPlay;const old=media();old.play=()=>new Promise((_,reject)=>rejectPlay=reject);const q=P.create({loadAsset:loader,now:()=>0,makeAudio:()=>old});q.update('旧局',view());await q.prepare();const promise=q.enable();q.update('新局',view());rejectPlay(Error('旧音频异步拒绝'));assert.equal(await promise,null);assert.equal(q.status().error,null);assert.equal(q.status().enabled,false);
 let waitingMedia;const waiting=P.create({loadAsset:loader,now:()=>now,makeAudio:()=>waitingMedia=media()});now=0;waiting.update('就绪',view('waiting',0,4,1000));await waiting.prepare();assert.equal(await waiting.enable(),null);assert(waiting.status().enabled);assert(waitingMedia.paused);assert.equal(waitingMedia.currentTime,0);now=100000;waiting.sync();assert.equal(waitingMedia.currentTime,0);waiting.update('就绪',view('running',0,5,2000));assert(!waitingMedia.paused);assert.equal(waitingMedia.plays,2);
 const bounded=P.create({loadAsset:loader,now:()=>now,makeAudio:media});const boundedView=view('running',5000);boundedView.mediaDurationMs=9000;now=0;bounded.update('有界',boundedView);await bounded.prepare();await bounded.enable();now=5000;bounded.sync();assert(bounded.status().error.includes('末尾'));
 const crypto=require('crypto'),bytes=Buffer.from('合成录音字节'),asset={url:'https://cdn.pegasus.de/test.mp3',sha256:crypto.createHash('sha256').update(bytes).digest('hex')};let blobCount=0,released=0;const options={crypto:crypto.webcrypto,fetch:async(url,opts)=>{assert.equal(opts.credentials,'omit');return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};},createURL:()=>{blobCount++;return 'blob:字节核实';},releaseURL:()=>released++};const verified=await P.loadVerified(asset,options);assert.equal(blobCount,1);verified.release();assert.equal(released,1);await assert.rejects(P.loadVerified({...asset,sha256:'0'.repeat(64)},options),/版本不匹配/);assert.equal(blobCount,1);
 console.log('✓ 实际SHA-256匹配才创建本机播放地址，不发送凭据，错误字节拒绝且不创建媒体／地址，离局释放资源；合成字节不认证官方录音');
 console.log('✓ 上一局迟到的播放失败不污染新局状态；媒体测试不证明真实录音或浏览器自动播放兼容');
})().catch(e=>{console.error(e);process.exitCode=1;});
