// 使用合成指令验收同步基础设施，绝不认证真实录音信号。
const assert=require('assert'),A=require('../js/audio-timeline'),BB=require('../js/engine'),M=require('../js/missions');
const copy=x=>JSON.parse(JSON.stringify(x));
function definition(mission=54,contentVersion=9){return {version:1,verified:true,mission,contentVersion,durationMs:6000,asset:{url:'https://cdn.pegasus.de/public/合成测试.mp3',locale:'en',sha256:'a'.repeat(64)},cues:[{id:'停',atMs:1000,type:'hold',text:'停止拆线，听取指令。'},{id:'继续',atMs:3000,type:'resume',text:'可以继续拆线。'},{id:'引爆',atMs:5000,type:'fail',text:'合成测试截止。'}]};}
function game(){const G=BB.createGame(M.get('official-development',54),[{pid:'p0',name:'听音玩家0'},{pid:'p1',name:'听音玩家1'}]);while(G.phase==='setup'){const p=BB.setupActor(G),w=G.wires.find(w=>w.o===p&&BB.setupInfoAllowed(G,w));assert.equal(BB.act(G,p,{a:'info',w:w.id}),null);}assert.equal(G.phase,'audio-ready');return G;}
function reject(G,fn){const before=JSON.stringify(G);assert(fn());assert.equal(JSON.stringify(G),before);}
for(const id of A.missions){const d=definition(id);assert.equal(A.validate(d,id,9),null);for(const alter of [d=>d.verified=false,d=>d.contentVersion=8,d=>d.cues[1].id=d.cues[0].id,d=>d.cues[0].atMs=-1,d=>d.cues[0].type='客户端任意指令',d=>d.asset.url='https://example.com/test.mp3',d=>d.asset.url='https://user:secret@cdn.pegasus.de/file.mp3']){const bad=copy(d);alter(bad);assert(A.validate(bad,id,9));}}
{
 const s=A.create('合成',definition(),1000),events=[];assert.equal(A.elapsed(s,1500),500);assert.equal(A.advance(s,2000,c=>{events.push(c.id);return null;}).error,null);assert(s.cutHeld);assert.equal(s.applied,1);assert.equal(A.advance(s,2000,()=>{throw Error('重复执行');}).changed,false);
 assert(A.pause(s,2500));assert.equal(A.elapsed(s,100000),1500);const paused=JSON.stringify(s);assert(!A.pause(s,3000));assert.equal(JSON.stringify(s),paused);const saved=copy(s);assert(A.resume(saved,4000));assert.equal(A.advance(saved,5500,c=>{events.push(c.id);return null;}).error,null);assert(!saved.cutHeld);assert.equal(saved.applied,2);assert.equal(A.advance(saved,10000,c=>{events.push(c.id);return null;}).error,null);assert.equal(saved.status,'ended');assert.equal(A.elapsed(saved,99999),5000);assert.deepEqual(events,['停','继续','引爆']);
 saved.definition.asset.privateNote='服务器私有说明';const view=A.view(saved,10000);assert(!('cues' in view));assert(!('definition' in view));assert(!('applied' in view));assert(!JSON.stringify(view).includes('atMs'));assert(!('privateNote' in view.source));assert.equal(A.elapsed(saved,-1000),5000);
 const failure=A.create('回滚',definition(),0),before=JSON.stringify(failure);assert(A.advance(failure,4000,c=>c.type==='resume'?'拒绝内部指令':null).error);assert.equal(JSON.stringify(failure),before);
}
console.log('✓ 音频组件覆盖19／30／42／54／66版本门禁、发行商资源与哈希、重复／倒序／客户端任意指令拒绝；绝对时钟、暂停冻结、重载后补执行一次、截止冻结和执行失败回滚；公共包无未来信号／引爆时刻');
{
 const G=game(),d=definition(54,G.mission.contentVersion);reject(G,()=>BB.initializeAudio(G,d,{}));const bad=copy(d);bad.verified=false;reject(G,()=>BB.initializeAudio(G,bad,{serverAudio:true,now:1000}));assert.equal(BB.initializeAudio(G,d,{serverAudio:true,now:1000}),null);reject(G,()=>BB.initializeAudio(G,d,{serverAudio:true,now:1000}));
 const ones=G.wires.filter(w=>w.v===1);ones.forEach((w,i)=>{w.o=i<2?0:1;w.s=0;w.info=null;});G.players.forEach((p,o)=>p.stands=p.stands.map((_,s)=>G.wires.filter(w=>w.o===o&&w.s===s).sort((a,b)=>a.v-b.v||a.id-b.id).map(w=>w.id)));const target=ones[2].id,own=ones[1].id;
 assert.equal(BB.act(G,0,{a:'dual',w:target,val:1},{now:1500}),null);const id=G.pending.id,balances=copy(G.officialState.submarine54.balances);assert.equal(BB.advanceAudio(G,{serverAudio:true,now:2000}).error,null);assert(G.audioClock.cutHeld);reject(G,()=>BB.act(G,1,{a:'resolve',id,w:target},{now:2500}));assert.equal(G.pending.id,id);
 assert.equal(BB.setPaused(G,true,2500),null);const saved=copy(G),frozen=JSON.stringify(saved);assert.equal(BB.advanceAudio(saved,{serverAudio:true,now:100000}).changed,false);assert.equal(JSON.stringify(saved),frozen);assert.equal(BB.setPaused(saved,false,4000),null);assert.equal(BB.advanceAudio(saved,{serverAudio:true,now:5500}).error,null);assert(!saved.audioClock.cutHeld);assert.equal(saved.pending.id,id);
 assert.equal(BB.act(saved,1,{a:'resolve',id,w:target},{now:5500}),null);assert.equal(saved.pending.step,'own');assert(BB.view(saved,0).pending.choices.includes(own));assert(!BB.view(saved,1).pending.choices);assert.equal(BB.act(saved,0,{a:'resolve',id,w:own},{now:6000}),null);assert.deepEqual(saved.officialState.submarine54.balances,balances);assert.equal(saved.audioClock.applied,2);
 const beforeLate=JSON.stringify(saved);reject(saved,()=>BB.act(saved,saved.turn,{a:'red'},{now:7500}));assert.equal(JSON.stringify(saved),beforeLate);assert.equal(BB.advanceAudio(saved,{serverAudio:true,now:7500}).error,null);assert.equal(saved.phase,'lost');assert.equal(saved.pending,null);assert.equal(saved.audioClock.status,'ended');assert.equal(saved.audioClock.applied,3);assert.equal(BB.advanceAudio(saved,{serverAudio:true,now:99999}).changed,false);
 const untouched=game();reject(untouched,()=>BB.advanceAudio(untouched,{serverAudio:false}).error);
}
console.log('✓ 第54关真实引擎接合成时间轴：未核实／客户端启动不变，私有拆线决定跨听音暂停／存档／恢复保留，继续后按本人选副本不重复耗氧；迟到动作不能绕过服务器指令，截止真实失败且不重复；未启用真实录音');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb-audio-registry-'));
 try{const G=game(),d=definition(54,G.mission.contentVersion);assert.equal(BB.initializeAudio(G,d,{serverAudio:true,now:1000}),null);assert.equal(BB.setPaused(G,true,1500),null);G.catalog=G.mission.catalog='campaign';const name='bb-audio-registry';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:'p0',mid:54,ruleset:'campaign',attempts:1,started:true,seats:G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'录音凭据'+p.pid})),observers:[],revision:0,seen:[],G}));const service=Service({clients:new Set()},dir),room=service.load(name),clock=room.G.audioClock;assert.equal(service.audioAsset(d.asset.sha256).url,d.asset.url);assert.equal(service.audioAsset('0'.repeat(64)),null);clock.definition.verified=false;assert.equal(service.audioAsset(d.asset.sha256),null);clock.definition.verified=true;clock.definition.contentVersion++;assert.equal(service.audioAsset(d.asset.sha256),null);clock.definition.contentVersion--;clock.gid='旧局';assert.equal(service.audioAsset(d.asset.sha256),null);clock.gid=room.G.gid;clock.version=99;assert.equal(service.audioAsset(d.asset.sha256),null);}
 finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 真实权威录音登记仅接受本局／已核实／对应内容版本／支持时钟版本的指纹；未知指纹、未核实清单、旧局或旧版本不提供文件');
