const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),http=require('http'),crypto=require('crypto'),create=require('../server/audio-files');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb-audio-bytes-')),bytes=Buffer.from('用于录音传输验收的合成字节'),hash=crypto.createHash('sha256').update(bytes).digest('hex');let downloads=0,content=bytes,asset={sha256:hash,url:'https://cdn.pegasus.de/固定验收录音.mp3'},handler;
const options={dir,resolve:h=>h===hash?asset:null,fetchTo:async(url,file)=>{assert.equal(url,'https://cdn.pegasus.de/固定验收录音.mp3');downloads++;await new Promise(r=>setTimeout(r,30));fs.writeFileSync(file,content);}};
const server=http.createServer((req,res)=>handler.handle(req,res,new URL(req.url,'http://localhost').pathname));
function request(port,route,method='GET'){return new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,path:route,method},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);req.end();});}
(async()=>{try{handler=create(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,route='/audio/'+hash+'.mp3';assert.equal((await request(port,'/audio/'+'0'.repeat(64)+'.mp3')).status,404);assert.equal((await request(port,route,'POST')).status,405);assert.equal((await request(port,route+'?url=http://127.0.0.1/secret')).status,400);assert.equal(downloads,0);asset={...asset,url:'http://127.0.0.1/private'};assert.equal((await request(port,route)).status,404);assert.equal(downloads,0);asset={...asset,url:'https://cdn.pegasus.de/固定验收录音.mp3'};
 const replies=await Promise.all(Array.from({length:8},()=>request(port,route)));for(const res of replies){assert.equal(res.status,200);assert.deepEqual(res.body,bytes);assert.equal(res.headers['content-type'],'audio/mpeg');assert.equal(res.headers.etag,'"'+hash+'"');}assert.equal(downloads,1);const head=await request(port,route,'HEAD');assert.equal(head.status,200);assert.equal(head.body.length,0);assert.equal(downloads,1);
 const file=path.join(dir,hash+'.mp3');fs.writeFileSync(file,'损坏缓存');assert.deepEqual((await request(port,route)).body,bytes);assert.equal(downloads,2);fs.writeFileSync(file,'再次损坏缓存');content=Buffer.from('错误版本');handler=create(options);assert.equal((await request(port,route)).status,502);assert.equal(fs.existsSync(file),false);assert.deepEqual(fs.readdirSync(dir),[]);
 console.log('✓ 录音同源文件服务真实HTTP：未知指纹／任意地址参数／POST／本机来源均不下载；八并发请求只下载一次，校验实际SHA-256后返回固定文件，HEAD／缓存复用、损坏缓存重核及重启后错误字节拒绝、临时文件清除；合成字节非官方录音认证');
}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
