const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup}=require('./constraint-ring.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb61-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('轮转夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);const c=G.officialState.constraints,original=c.ring.map(x=>x.id),draw=c.deck[0],code='C'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:61,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,original,draw};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const scenario of [{n:2,agree:true},{n:3,agree:true},{n:4,agree:true},{n:5,agree:true},{n:3,agree:false}].filter(x=>!process.env.BB_RING_BROWSER_N||x.n===Number(process.env.BB_RING_BROWSER_N))){const {n,agree}=scenario,data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'轮转观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='rotating-personal-constraints');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert.equal(await page.locator('[data-ring-slot]').count(),n<=3?4:n);await page.locator('[data-ring-slot="0"] summary').click();assert((await page.locator('[data-ring-slot="0"] p').innerText()).includes('只能'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.equal(await pages[0].locator('[data-act="constraint-rotation"]').count(),3);assert.equal(await pages[1].locator('[data-act="constraint-rotation"]').count(),0);if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  await pages[0].locator('[data-act="constraint-rotation"][data-direction="1"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.type==='constraint-vote')));
  if(n===2){const id=(await pages[0].evaluate(()=>window.testView)).pending.id;await pages[0].locator('[data-act="host-pause"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.paused)));assert.equal(await pages[1].locator('[data-act="constraint-vote"]').count(),0);await pages[0].locator('[data-act="host-pause"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>!window.testView?.paused)));assert.equal((await pages[0].evaluate(()=>window.testView)).pending.id,id);}
  for(let pi=1;pi<n;pi++){for(const page of pages){assert.deepEqual((await page.evaluate(()=>window.testView)).official.constraints.ring.map(x=>x.id),data.original);assert.equal(await page.locator('[data-act="constraint-replace"]').count(),0);}assert.equal(await pages[pi].locator('[data-act="constraint-vote"]').count(),2);assert((await pages[pi].locator('.turn-notice').innerText()).includes('确认'));assert.equal(await pages[n].locator('[data-act="constraint-vote"]').count(),0);if(pi===n-1){await pages[pi].reload({waitUntil:'domcontentloaded'});await pages[pi].locator('#jcode').fill(data.code);await pages[pi].locator('#btn-join').click();await pages[pi].waitForFunction(()=>window.testView?.pending?.type==='constraint-vote');}await pages[pi].locator('[data-act="constraint-vote"][data-agree="'+(agree?'yes':'no')+'"]').click();if(!agree)break;if(pi<n-1)await Promise.all(pages.map(p=>p.waitForFunction(next=>window.testView?.pending?.to===next,pi+1)));}
  await Promise.all(pages.map(p=>p.waitForFunction(()=>!window.testView?.pending)));const expected=agree?data.original.map((_,i)=>data.original[(i-1+data.original.length)%data.original.length]):data.original;for(const page of pages){const V=await page.evaluate(()=>window.testView);assert.deepEqual(V.official.constraints.ring.map(x=>x.id),expected);assert.equal(V.det,0);assert(!V.official.constraints.deck);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  await pages[1].locator('[data-act="constraint-replace"]').click();await Promise.all(pages.map(p=>p.waitForFunction(draw=>window.testView?.official?.constraints.personal[1].id===draw&&window.testView.det===1,data.draw)));for(const page of pages){assert.equal((await page.evaluate(()=>window.testView)).official.constraints.remaining,6);assert((await page.locator('[aria-label="轮转个人限制"]').innerText()).includes('剩余换牌 6'));}
  console.log('✓ 第61关'+n+'人'+(agree?'全队同意':'拒绝轮转')+'375像素双视图加观众：额外牌位／完整限制可读、队长提议、逐人私人按钮与轮到本人通知、刷新后继续确认／未提前移牌，全员同步最终牌位与真实非回合付费换牌；零轮转罚格／牌堆隐藏／无页面异常');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
