const assert=require('assert'),BB=require('../js/engine'),{game,setup,resort,card}=require('./constraint-ring.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));}function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
function state(G){return G.officialState.constraints;}
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),s=state(G);assert.equal(G.wires.length,n===2?50:49);assert.equal(G.rmark.n,n===2?2:1);assert.equal(G.rmark.cand.length,G.rmark.n);assert.equal(G.ymark.n,0);assert.equal(s.ring.length,n<=3?4:n);assert.equal(new Set(s.ring.map(x=>x.id)).size,s.ring.length);assert(s.ring.every(x=>'ABCDE'.includes(x.id)));assert.equal(s.deck.length,7);assert.equal(new Set(s.deck).size,7);assert(s.deck.every(id=>'FGHIJKL'.includes(id)));assert.equal(s.ring[0].owner,cap);assert.deepEqual(s.ring.filter(x=>x.owner===null).map(x=>x.side),n===2?['left','right']:n===3?['left']:[]);for(let p=0;p<n;p++)assert.equal(s.personal[p].id,s.ring.find(x=>x.owner===p).id);setup(G);assert.equal(G.phase,'play');assert.equal(G.turn,cap);assert(state(G).captainPending);assert(G.players.every((_,p)=>G.setup[p]===1));assert.equal(G.deadline,null);for(let p=-1;p<n;p++){const v=BB.view(G,p).official.constraints;assert.equal(v.remaining,7);assert.equal(v.ring.length,s.ring.length);assert(!v.deck);assert(!v.unused);}
}
console.log('✓ 第61关2–5人全部队长8种子：48蓝／已知红1或双人2、随机唯一A–E与额外左右牌位、隐藏F–L牌堆、普通初始、队长轮转选择／无计时与牌堆泄露');
for(const n of [2,3,4,5])for(const d of [-1,1]){
 const G=game(n);setup(G);const original=state(G).ring.map(x=>x.id),owners=state(G).ring.map(x=>x.owner),id=state(G).decisionId;reject(G,1,{a:'constraint-rotation',id,direction:d});act(G,0,{a:'constraint-rotation',id,direction:d});const decision=G.pending.id;assert.deepEqual(state(G).ring.map(x=>x.id),original);for(let p=1;p<n;p++){assert.equal(G.pending.to,p);assert.deepEqual(BB.view(G,p).pending.choices,[true,false]);assert(!BB.view(G,0).pending.choices);assert(!BB.view(G,-1).pending.choices);reject(G,p,{a:'constraint-vote',id:decision-1,agree:true});const copy=JSON.parse(JSON.stringify(G));act(G,p,{a:'constraint-vote',id:decision,agree:true});act(copy,p,{a:'constraint-vote',id:decision,agree:true});assert.deepEqual(copy,G);if(p<n-1)assert.deepEqual(state(G).ring.map(x=>x.id),original);}
 assert(!G.pending);assert.deepEqual(state(G).ring.map(x=>x.owner),owners);assert.deepEqual(state(G).ring.map(x=>x.id),original.map((_,i)=>original[(i-d+original.length)%original.length]));assert.equal(state(G).revision,1);assert.equal(G.det,0);assert.equal(G.turnNo,1);reject(G,0,{a:'constraint-vote',id:decision,agree:true});reject(G,0,{a:'constraint-rotation',id,direction:d});
 const H=game(n);setup(H);const unchanged=state(H).ring.map(x=>x.id);act(H,0,{a:'constraint-rotation',id:state(H).decisionId,direction:1});act(H,1,{a:'constraint-vote',id:H.pending.id,agree:false});assert(!H.pending);assert.deepEqual(state(H).ring.map(x=>x.id),unchanged);assert.equal(state(H).revision,0);assert.equal(H.det,0);
}
console.log('✓ 第61关2–5人顺／逆时针：全队逐人同意之前不移动，额外牌位参与、主人位置不移、保存恢复一致、私人菜单／越权旧决定拒绝；有人不同意则牌与引爆器不变');
{
 const G=game(3);setup(G);const s=state(G),index=s.ring.findIndex(x=>x.owner===0),incoming=(index-1+s.ring.length)%s.ring.length,even=s.ring.findIndex(x=>x.id==='A');[s.ring[even].id,s.ring[incoming].id]=[s.ring[incoming].id,s.ring[even].id];require('./constraint-ring.fixture').sync(G);
 G.wires.filter(w=>w.v===2).forEach((w,i)=>{w.o=i<2?0:1;w.s=0;w.info=null;});resort(G);const twos=G.wires.filter(w=>w.v===2),before=state(G).personal[0].id;assert.notEqual(before,'A');act(G,0,{a:'constraint-rotation',id:state(G).decisionId,direction:1});while(G.pending)act(G,G.pending.to,{a:'constraint-vote',id:G.pending.id,agree:true});assert.equal(state(G).personal[0].id,'A');const odd=G.wires.find(w=>w.o===0&&!w.cut&&Number.isInteger(w.v)&&w.v%2),peer=G.wires.find(w=>w.o!==0&&!w.cut);reject(G,0,{a:'dual',w:peer.id,val:odd.v});act(G,0,{a:'dual',w:twos[2].id,val:2});const id=G.pending.id,revision=state(G).revision;
 reject(G,0,{a:'constraint-replace',revision});reject(G,1,{a:'constraint-replace',revision});act(G,1,{a:'resolve',id,w:twos[2].id});assert.equal(G.pending.step,'own');assert.deepEqual(BB.view(G,0).pending.choices,[twos[0].id,twos[1].id]);reject(G,2,{a:'constraint-replace',revision});const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'resolve',id,w:twos[1].id});act(saved,0,{a:'resolve',id,w:twos[1].id});assert.deepEqual(saved,G);assert(!G.wires[twos[0].id].cut);assert(G.wires[twos[1].id].cut&&G.wires[twos[2].id].cut);assert.equal(state(G).revision,revision);assert.equal(G.det,0);
}
console.log('✓ 第61关实际轮转到A后立即限制宣告；正确双拆仍由目标公开／本人选第二副本，目标及本人阶段换牌拒绝且不耗库存，保存恢复一致，不把轮转当拆线回合');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);const prior=state(G).ring.find(x=>x.owner===1).id,draw=state(G).deck[0],id=state(G).decisionId;act(G,1,{a:'constraint-replace',revision:0});assert.equal(state(G).personal[1].id,draw);assert(state(G).discard.includes(prior));assert.equal(state(G).deck.length,6);assert.equal(G.det,1);assert.equal(G.turn,0);assert(state(G).captainPending);assert.notEqual(state(G).decisionId,id);reject(G,0,{a:'constraint-rotation',id,direction:0});reject(G,1,{a:'constraint-replace',revision:0});assert.equal(state(G).ring.length+state(G).deck.length+state(G).discard.length,(n<=3?4:n)+7);
 const H=game(n);setup(H);H.det=H.detMax-1;act(H,1,{a:'constraint-replace',revision:0});assert.equal(H.phase,'lost');assert(!H.pending);assert.equal(H.det,H.detMax);
 const E=game(n);setup(E);state(E).discard.push(...state(E).deck);state(E).deck=[];reject(E,1,{a:'constraint-replace',revision:0}); // 构造库存耗尽，不是实际开局可达性证明。
}
{
 const G=game(3);setup(G);G.wires.filter(w=>w.v===3||w.v===4).forEach(w=>{w.o=w.v===3?0:1;w.s=0;w.info=null;});G.wires.filter(w=>![3,4].includes(w.v)).forEach(w=>w.cut=true);resort(G);const ids=state(G).ring.map(x=>x.id);card(G,0,'A');const legal=ids.find(id=>'CE'.includes(id));card(G,1,legal);act(G,0,{a:'constraint-rotation',id:state(G).decisionId,direction:0});assert.equal(G.turn,1);assert.equal(G.turnNo,2);assert.equal(G.det,0);assert.equal(state(G).personal[0].id,'A');assert(!state(G).personal[0].retired);
 const R=game(3);setup(R);const red=R.wires.find(w=>BB.kindOf(w)==='r');red.o=0;red.s=0;R.wires.filter(w=>w.o===0&&w.id!==red.id).forEach(w=>w.cut=true);resort(R);card(R,0,'G');act(R,0,{a:'red'});assert(R.wires[red.id].cut);assert.equal(R.det,0);assert.equal(state(R).personal[0].id,'G');
 const trapped=game(3);setup(trapped);trapped.wires.filter(w=>w.v===1).forEach(w=>{w.o=0;w.s=0;w.info=null;});trapped.wires.filter(w=>w.v!==1).forEach(w=>w.cut=true);resort(trapped);card(trapped,0,state(trapped).ring.find(x=>'BC'.includes(x.id)).id);state(trapped).deck=state(trapped).deck.filter(id=>id!=='K');state(trapped).deck.unshift('K');act(trapped,0,{a:'constraint-replace',revision:0});assert.equal(trapped.phase,'lost');assert.equal(trapped.det,1);
 const saved=game(3);setup(saved);saved.wires.filter(w=>w.v===1).forEach(w=>{w.o=0;w.s=0;w.info=null;});saved.wires.filter(w=>w.v!==1).forEach(w=>w.cut=true);resort(saved);card(saved,0,'K');saved.paused=true;assert(BB.recoverFatalState(saved));assert.equal(saved.phase,'lost');assert.equal(saved.paused,false);assert(!BB.recoverFatalState(saved));
}
console.log('✓ 第61关真实非回合付费换本人牌、有限牌堆／不回收弃牌、刷新队长旧决定、到末端失败；不能遵守保留限制并免费跳过，红线豁免G，真实换K全队死锁立即引爆及异常快照恢复一次；后段／耗尽夹具非整局证明');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb61-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=game(n);setup(G);const name='bb-ring'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'轮转凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:61,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'轮转观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  function restore(label,p,answer){service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'暂停',paused:true});const paused=JSON.stringify(G);send(p,label+'暂停回复',answer);assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'继续',paused:false});}
  connect();const original=state(G).ring.map(x=>x.id),decision=state(G).decisionId;restore('提议前',0,{a:'constraint-rotation',id:decision,direction:1});send(0,'提出轮转',{a:'constraint-rotation',id:decision,direction:1});const id=G.pending.id;
  for(let p=1;p<n;p++){restore('同意'+p,p,{a:'constraint-vote',id,agree:true});assert.equal(G.pending.id,id);assert.deepEqual(state(G).ring.map(x=>x.id),original);assert.deepEqual(last(peers[p],'official:view').view.pending.choices,[true,false]);assert(!last(peers[0],'official:view').view.pending.choices);service.handle(observer,'official:perspective',{pid:seats[p].pid});assert(!last(observer,'official:view').view.pending.choices);const before=JSON.stringify(G);send(0,'冒充同意'+p,{a:'constraint-vote',id,agree:true});assert.equal(JSON.stringify(G),before);send(p,'过期同意'+p,{a:'constraint-vote',id:id-1,agree:true});assert.equal(JSON.stringify(G),before);send(p,'同意轮转'+p,{a:'constraint-vote',id,agree:true});}
  assert(!G.pending);const expected=original.map((_,i)=>original[(i-1+original.length)%original.length]);assert.deepEqual(state(G).ring.map(x=>x.id),expected);assert.equal(G.det,0);const once=JSON.stringify(G),revision=room.revision;send(n-1,'同意轮转'+(n-1),{a:'constraint-vote',id,agree:true});assert.equal(room.revision,revision);assert.equal(JSON.stringify(G),once);for(const ws of [...peers,observer]){const c=last(ws,'official:view').view.official.constraints;assert.deepEqual(c.ring.map(x=>x.id),expected);assert(!c.deck);}
  const prior=state(G).personal[1].id,cardRevision=state(G).revision,draw=state(G).deck[0];restore('非回合换牌',1,{a:'constraint-replace',revision:cardRevision});send(1,'非回合更换',{a:'constraint-replace',revision:cardRevision});assert.equal(state(G).personal[1].id,draw);assert(state(G).discard.includes(prior));assert.equal(G.det,1);const used=JSON.stringify(G),usedRevision=room.revision;send(1,'非回合更换',{a:'constraint-replace',revision:cardRevision});assert.equal(room.revision,usedRevision);assert.equal(JSON.stringify(G),used);wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第61关2–5人权威每次同意前暂停重启凭据重连：牌未提前移、菜单只给对应玩家／观战视角移除、冒用／旧回复拒绝、全员一次轮转；非回合换牌恢复／重复只一次抽牌及罚格');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',61),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧限制'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.constraintRing(G),null);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.deepEqual(G.mission.rules,{missing:true,hide:true});}
}
console.log('✓ 第61关旧版17改编保存／视图保留缺失值及隐藏候选规则，不强制迁移到轮转个人限制');
