// 内部法文版效果快照的显示检查；不认证即时自动触发。
const assert=require('assert'),fs=require('fs'),path=require('path'),{create,unlock,apply}=require('./disintegrator.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb55-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('分解器夹具只允许隔离本机服务器');
function fixture(n,value){const G=create(n);unlock(G);if(value)apply(G,value);const code='D'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid})),ids=G.declaration?.ids||[];G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,ids,value};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const [n,value] of [[2,0],[2,2],[3,2],[4,2],[5,2],[3,10]]){const data=fixture(n,value),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'分解器观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.equip?.some(e=>e.n===17));}
  for(let mode=0;mode<2;mode++){for(const page of pages){const V=await page.evaluate(()=>window.testView),card=page.locator('.card3[data-n="17"],.eq[data-n="17"]');assert((await card.innerText()).includes('10·10'));assert(V.players.every(p=>!p.character.used&&p.dd));assert.equal(V.det,0);assert.equal(V.turn,0);assert(!('equipmentEffects' in V));if(value){assert(V.equip[0].used);assert.equal(V.declaration.type,'disintegrator');assert.deepEqual(V.declaration.ids,data.ids);const text=await page.locator('.disintegrator-notice').innerText();assert(text.includes('蓝色 '+value));if(value===10)assert(text.includes('不重新抽取'));else{assert.equal(data.ids.length,4);for(const id of data.ids){assert.equal(await page.locator('.declared-target[data-w="'+id+'"] .target-arrow').count(),1);const wire=V.players.flatMap(p=>p.stands.flat()).find(w=>w.id===id);assert(wire.cut&&wire.v===2);}}}else assert(!V.equip[0].used);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  const A=pages[0];if(!value){await A.locator('.eq[data-n="17"]').click();assert.equal(await A.locator('[data-act="eqinstant"]').count(),0);assert((await A.locator('.act').innerText()).includes('触发时机'));}else{await A.reload({waitUntil:'domcontentloaded'});await A.locator('#jcode').fill(data.code);await A.locator('#btn-join').click();await A.waitForFunction(()=>window.testView?.equip?.find(e=>e.n===17)?.used);assert.deepEqual((await A.evaluate(()=>window.testView)).declaration.ids,data.ids);}
  console.log('✓ 分解器'+n+'人375像素双视图：印刷10·10、'+(!value?'客户端激活门禁':value===10?'无目标也用尽／不重抽':'全队4根蓝2公开／4箭头')+'、个人卡／正常回合不变、观战同步／刷新保留，内部法文快照非实时自动触发证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
