const assert=require('assert'),BB=require('../js/engine'),C=require('../js/campaign-rules'),{create,unlock,event,apply,randomFor}=require('./disintegrator.fixture');
function reject(G,e=event(G),opts={serverEquipment:true,rng:()=>.5}){const before=JSON.stringify(G);assert(BB.applyEquipmentEffect(G,e,opts));assert.equal(JSON.stringify(G),before);}
assert.equal(BB.EQUIP[17].id,'disintegrator');assert.equal(BB.equipmentLabel(17),'10·10');
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++){
 const G=create(n,cap),tens=G.wires.filter(w=>w.v===10);tens.slice(0,2).forEach(w=>w.cut=true);reject(G);unlock(G);reject(G,event(G),{});reject(G,{...event(G),gid:'旧局'});reject(G,{...event(G),edition:'de'});reject(G,{...event(G),generation:1});reject(G,event(G),{serverEquipment:true,rng:()=>1});
 const client=JSON.stringify(G);assert(BB.act(G,cap,{a:'equip',n:17}));assert.equal(JSON.stringify(G),client);for(const flag of ['paused','pending']){G[flag]=true;reject(G);G[flag]=flag==='pending'?null:false;}
 const targets=G.wires.filter(w=>w.v===2).map(w=>w.id),others=G.wires.filter(w=>w.v!==2).map(w=>({id:w.id,cut:w.cut,info:w.info})),players=G.players.map(p=>({pid:p.pid,dd:p.dd,character:p.character})),turn=G.turn,turnNo=G.turnNo,det=G.det;G.announcement={id:0,info:{t:'v',v:1}};G.radar={val:1};const saved=JSON.parse(JSON.stringify(G));apply(G,2);apply(saved,2);assert.deepEqual(saved,G);assert(targets.every(id=>G.wires[id].cut));assert.deepEqual(G.wires.filter(w=>w.v!==2).map(w=>({id:w.id,cut:w.cut,info:w.info})),others);assert.equal(G.turn,turn);assert.equal(G.turnNo,turnNo);assert.equal(G.det,det);assert.equal(G.announcement,null);assert.equal(G.radar,null);assert(G.equip[0].used);assert.equal(G.declaration.type,'disintegrator');assert.deepEqual(G.declaration.ids,targets);assert.equal(G.equipmentEffects.length,1);assert.equal(G.equipmentEffects[0].value,2);assert.deepEqual(G.players.map(p=>({pid:p.pid,dd:p.dd,character:p.character})),players);
 const done=JSON.stringify(G);let calls=0;assert.equal(BB.applyEquipmentEffect(G,event(G),{serverEquipment:true,rng:()=>{calls++;return.9;}}),null);assert.equal(calls,0);assert.equal(JSON.stringify(G),done);for(let viewer=-1;viewer<n;viewer++){const V=BB.view(G,viewer);assert(!('equipmentEffects' in V));assert(V.players.flatMap(p=>p.stands.flat()).filter(w=>targets.includes(w.id)).every(w=>w.cut&&w.v===2));}
}
console.log('✓ 法文分解器内部组件2–5人全部队长：四根10解锁、蓝数字标记随机抽取、全员剩余该蓝值一次剪完／其他线不变；角色／引爆器／正常回合不变、公开结果／当前提示替换、保存恢复／重复不再抽、客户端／版别／旧批次／错误拒绝不变');
{
 for(let remaining=0;remaining<=4;remaining++){const G=create(3);unlock(G);const blue=G.wires.filter(w=>w.v===2);blue.slice(remaining).forEach(w=>w.cut=true);apply(G,2);assert.equal(BB.cutCount(G,2),4);assert.equal(G.declaration.ids.length,remaining);assert(G.equip[0].used);}
 const G=create(3);unlock(G);const old=G.wires.filter(w=>w.v===2).slice(0,2);old.forEach(w=>w.info={t:'v',v:2});assert(C.availableInfoTokens(G,false).every(t=>t.value!==2));apply(G,C.availableInfoTokens(G,false)[0].value);assert.notEqual(G.equipmentEffects[0].value,2);
 const empty=create(3);unlock(empty);let j=0;for(let value=1;value<=12;value++)empty.wires.filter(w=>!w.cut).slice(j,j+2).forEach(w=>w.info={t:'v',v:value}),j+=2;assert.equal(C.availableInfoTokens(empty,false).length,0);reject(empty);
 const mission=create(3);unlock(mission);mission.officialState={version:1,module:'frequency'};reject(mission);
}
console.log('✓ 分解器剩余0／1／2／3／4根均合法且不重抽；抽取排除已占用数字标记／不抽黄，无供给与未实现任务例外拒绝，不自行绕过限制');
{
 const G=create(3);unlock(G);apply(G,2);G.equip.push({n:15,id:'emergency-reserve',used:false});G.wires.filter(w=>w.v===3).forEach(w=>w.cut=true);assert.equal(BB.applyEquipmentEffect(G,{gid:G.gid,n:15},{serverEquipment:true}),null);assert.equal(G.equip.find(e=>e.n===17).effectGeneration,1);assert(!G.equip.find(e=>e.n===17).used);assert.equal(G.declaration,null);const before=JSON.stringify(G);assert.equal(BB.applyEquipmentEffect(G,event(G,0),{serverEquipment:true,rng:()=>.9}),null);assert.equal(JSON.stringify(G),before);apply(G,C.availableInfoTokens(G,false).find(t=>t.value!==2&&t.value!==3&&t.value!==10).value,1);assert.equal(G.equipmentEffects.filter(e=>e.n===17).length,2);assert(G.equip.find(e=>e.n===17).used);
 const win=create(3);unlock(win);win.wires.filter(w=>w.v!==2).forEach(w=>w.cut=true);apply(win,2);assert.equal(win.phase,'won');const red=create(3);unlock(red);red.wires.filter(w=>w.v!==2&&BB.kindOf(w)!=='r').forEach(w=>w.cut=true);apply(red,2);assert.equal(red.phase,'play');assert(red.wires.some(w=>!w.cut&&BB.kindOf(w)==='r'));
}
console.log('✓ 分解器被储备箱恢复后使用批次＋1，旧批次事件不能影响新卡；新批次可再用，真正清空获胜／剩红须主动公开；自动触发／嵌套时机未认证');
{
 const G=create(3);unlock(G);G.officialState={version:1,module:'test-disintegrator-rejection'};C.modules['test-disintegrator-rejection']={afterEquipmentEffect(){return '构造任务钩子拒绝';}};try{reject(G,event(G),{serverEquipment:true,rng:randomFor(G,2)});}finally{delete C.modules['test-disintegrator-rejection'];}
}
console.log('✓ 批量效果任务钩子拒绝后，已剪线／卡／事件记录／提示全部回滚；库存耗尽仅为构造边界，不认证实际开局');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb55-disintegrator-authority-'));
 function peer(room){return {room,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=create(n);unlock(G);G.equip.push({n:15,id:'emergency-reserve',used:false});G.wires.filter(w=>w.v===3).forEach(w=>w.cut=true);G.catalog=G.mission.catalog='campaign';const name='bb-disintegrator'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'分解凭据'+p.pid})),wss={clients:new Set()};fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer,credential;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',credential?{credential,name:'分解观众'}:{spectator:true,name:'分解观众'});credential=last(observer,'official:welcome').credential;room=service.load(name);G=room.G;}
  connect();const before=JSON.stringify(G);service.handle(peers[0],'official:act',{gid:G.gid,revision:room.revision,commandId:'伪造分解',action:{a:'equipment-effect',event:event(G),serverEquipment:true}});assert.equal(JSON.stringify(G),before);const revision=room.revision;assert.equal(service.applyEquipmentEffect(name,event(G),{rng:randomFor(G,2)}),null);assert.equal(room.revision,revision+1);assert.equal(BB.cutCount(G,2),4);for(const ws of [...peers,observer]){const V=last(ws,'official:view').view;assert.equal(V.declaration.type,'disintegrator');assert.deepEqual(V.declaration.vals,[2]);assert(!('equipmentEffects' in V));}
  service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'保存分解后',paused:true});wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);assert.equal(BB.cutCount(G,2),4);assert(G.equip.find(e=>e.n===17).used);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'继续分解后',paused:false});const done=JSON.stringify(G),rev=room.revision;let calls=0;assert.equal(service.applyEquipmentEffect(name,event(G),{rng:()=>{calls++;return .9;}}),null);assert.equal(calls,0);assert.equal(room.revision,rev);assert.equal(JSON.stringify(G),done);
  assert.equal(service.applyEquipmentEffect(name,{gid:G.gid,n:15}),null);assert.equal(G.equip.find(e=>e.n===17).effectGeneration,1);const restored=JSON.stringify(G),r=room.revision;assert.equal(service.applyEquipmentEffect(name,event(G,0),{rng:()=>{calls++;return .9;}}),null);assert.equal(calls,0);assert.equal(JSON.stringify(G),restored);assert.equal(room.revision,r);assert.equal(service.applyEquipmentEffect(name,event(G,1),{rng:randomFor(G,5)}),null);assert.equal(BB.cutCount(G,5),4);assert.equal(room.revision,r+1);assert.equal(G.equipmentEffects.filter(e=>e.n===17).length,2);wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 分解器2–5人内部权威：客户端无入口、公共结果／私有事件账本、一次修订、暂停重启／凭据重连后不重抽；储备箱恢复新批次，旧批次不影响新卡，真实内部第二次效果通过；非自动触发证明');
