const assert=require('assert'),BB=require('../js/engine'),{game,setup}=require('./double-outward.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));}function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),groups=G.officialState.outwardGroups;assert.equal(G.wires.length,n===2?50:49);assert.equal(G.rmark.n,n===2?2:1);assert.equal(G.ymark.n,0);assert.equal(groups.length,n);assert.equal(new Set(groups.flat()).size,n*2);assert(G.equip.every(e=>e.n!==17));assert(!G.equipmentReserve.includes(17));for(let owner=0;owner<n;owner++){const pair=groups[owner],P=G.players[owner];assert.equal(pair.length,2);assert.equal(P.stands[0][0],pair[0]);assert.equal(P.stands.at(-1).at(-1),pair[1]);assert(G.wires[pair[0]].v<=G.wires[pair[1]].v);assert.equal(G.wires[pair[0]].o,owner);assert.equal(G.wires[pair[1]].o,owner);for(const st of P.stands){const normal=st.filter(id=>!BB.isOutward(G,G.wires[id]));assert(normal.every((id,i)=>i===0||G.wires[normal[i-1]].v<=G.wires[id].v));}for(let viewer=-1;viewer<n;viewer++){const V=BB.view(G,viewer);for(const id of pair){const w=V.players[owner].stands.flat().find(w=>w.id===id);assert.equal(w.v,viewer===owner?null:G.wires[id].v);if(viewer===owner)assert.equal(w.kind,undefined);}}}setup(G);assert.equal(G.phase,'play');assert(G.players.every((_,p)=>G.setup[p]===1));assert(groups.flat().every(id=>G.wires[id].info===null));assert.equal(G.deadline,null);
}
console.log('✓ 第64关2–5人所有队长8种子：48蓝／已知红1或双人2无黄，每人整手两随机朝外线、低左／高右及双架摆放、普通区独立排序、本人隐藏／队友可见、初始排除朝外／无计时、分解器入局及储备均替换');
{
 let G,selected,target;for(let seed=1;seed<100;seed++){const candidate=game(3,0,seed);setup(candidate);const right=candidate.wires[candidate.officialState.outwardGroups[0][1]];if(!Number.isInteger(right.v))continue;const match=candidate.wires.find(w=>w.o===1&&!w.cut&&w.v===right.v&&!BB.isOutward(candidate,w));if(match){G=candidate;selected=right.id;target=match.id;break;}}assert(G);const value=G.wires[selected].v;reject(G,0,{a:'outward-dual',own:target,val:value,w:target});act(G,0,{a:'outward-dual',own:selected,val:value,w:target});assert(G.pending.outwardIntent);assert.equal(G.pending.preferredOwn,selected);assert.equal(BB.view(G,1).pending.preferredOwn,undefined);const id=G.pending.id;act(G,1,{a:'resolve',id,w:target});assert.deepEqual(BB.view(G,0).pending.choices,G.officialState.outwardGroups[0]);const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'resolve',id,w:selected});act(saved,0,{a:'resolve',id,w:selected});assert.deepEqual(saved,G);assert(G.wires[selected].cut);assert.equal(G.det,0);assert(!G.wires[G.officialState.outwardGroups[0][0]].cut);
}
{
 let G,target,own;for(let seed=1;seed<100;seed++){const candidate=game(3,0,seed);setup(candidate);for(const id of candidate.officialState.outwardGroups[1]){const t=candidate.wires[id];if(!Number.isInteger(t.v))continue;const match=candidate.wires.find(w=>w.o===0&&!w.cut&&!BB.isOutward(candidate,w)&&w.v===t.v);if(match){G=candidate;target=id;own=match.id;break;}}if(G)break;}assert(G);const value=G.wires[target].v;act(G,0,{a:'dual',val:value,w:target});const id=G.pending.id;assert.equal(BB.view(G,1).pending.publicMatch,true);act(G,1,{a:'resolve',id,w:target});assert.equal(G.det,0);act(G,0,{a:'resolve',id,w:own});assert.equal(G.det,1);
}
console.log('✓ 第64关真实右端主动盲双拆可独立选择，保存及本人确认只用所选右线；队友选中任一朝外线后，完整配对才一次罚格／目标本人仍隐藏真值但可公开确认当前结果');
{
 const G=game(3);setup(G);const own=G.officialState.outwardGroups[0][1],target=G.wires.find(w=>w.o===1&&!BB.isOutward(G,w)&&Number.isInteger(w.v)),value=target.v===12?11:12;act(G,0,{a:'outward-dual',own,val:value,w:target.id});act(G,1,{a:'resolve',id:G.pending.id,w:target.id});assert.equal(G.phase,'lost');assert(G.lastAct.ids.every(id=>Number.isInteger(id)));assert.deepEqual(G.lastAct.ids,[target.id]);
}
console.log('✓ 第64关盲双拆目标猜错真实引爆；本人尚未选副本时不发布偏好线，也不产生未定义导线编号');
{
 let G,owner,value,outs;for(let seed=1;seed<500;seed++){const candidate=game(2,0,seed);setup(candidate);for(let p=0;p<2;p++){const pair=candidate.officialState.outwardGroups[p],v=candidate.wires[pair[0]].v;if(v!==candidate.wires[pair[1]].v||!Number.isInteger(v))continue;if(candidate.wires.filter(w=>w.v===v&&w.o===p).length===4){G=candidate;owner=p;value=v;outs=pair;break;}}if(G)break;}assert(G,'须从完整来源发牌找到同值双端／四根同手');G.turn=owner;assert(BB.outwardSoloValues(BB.view(G,owner),owner,outs).includes(value));act(G,owner,{a:'outward-solo',val:value,outs});assert.equal(BB.cutCount(G,value),4);assert.equal(G.det,0);assert(outs.every(id=>G.wires[id].cut));
}
{
 let G,owner,pair;for(let seed=1;seed<100;seed++){const candidate=game(3,0,seed);setup(candidate);const r=candidate.wires.find(w=>BB.kindOf(w)==='r'&&BB.isOutward(candidate,w));if(r){G=candidate;owner=r.o;pair=candidate.officialState.outwardGroups[owner];break;}}assert(G);G.wires.filter(w=>w.o===owner&&!pair.includes(w.id)).forEach(w=>{w.cut=true;w.info=null;});G.turn=owner;assert(BB.outwardRedPossible(G,owner));act(G,owner,{a:'outward-red'});assert.equal(G.phase,'lost','另一根实际蓝线不能被错误当红自动公开');assert(pair.every(id=>!G.wires[id].cut));
}
console.log('✓ 第64关真实来源同值双端加两已知线可显式盲单拆四根；两朝外剩线中一红一蓝错误全红宣告实际失败且不提前剪蓝，不能只检查其中一根');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);for(const own of G.officialState.outwardGroups[0]){for(const a of [{a:'equip',n:4,w:own},{a:'equip',n:18,w:own},{a:'character',w:own},{a:'equip',n:16,ws:[own,G.players[0].stands[0].find(id=>!BB.isOutward(G,G.wires[id]))],val:1}]){const before=JSON.stringify(G),error=BB.act(G,0,a);assert(error&&error.includes('朝外'),'两个端点都必须经过装备屏障');assert.equal(JSON.stringify(G),before);}}
 for(const target of G.officialState.outwardGroups[1]){for(const a of [{a:'dd',ws:[target,G.players[1].stands[0].find(id=>!BB.isOutward(G,G.wires[id]))],val:1},{a:'dual',w:target,val:1,stab:true},{a:'equip',n:18,w:target},{a:'character',ws:[target],val:1}]){const before=JSON.stringify(G),error=BB.act(G,0,a);assert(error&&error.includes('朝外'));assert.equal(JSON.stringify(G),before);}}
}
{
 let G,pair,value;for(let seed=1;seed<500;seed++){// 后段保留真实数值／数量，仅挑选来源种子。

 const candidate=game(3,0,seed);setup(candidate);const ids=candidate.officialState.outwardGroups[0],v=candidate.wires[ids[0]].v;if(!Number.isInteger(v)||!Number.isInteger(candidate.wires[ids[1]].v)||v===candidate.wires[ids[1]].v)continue;const others=candidate.wires.filter(w=>w.v===v&&w.id!==ids[0]);if(others.filter(w=>w.o===0).length>2)continue;const toCut=others.sort((a,b)=>Number(b.o===0)-Number(a.o===0)).slice(0,2);toCut.forEach(w=>{w.cut=true;w.info=null;});G=candidate;pair=ids;value=v;break;}assert(G);assert(BB.outwardSoloValues(BB.view(G,0),0,pair).includes(value));act(G,0,{a:'outward-solo',val:value,outs:pair});assert.equal(G.phase,'lost');assert(pair.every(id=>!G.wires[id].cut));}
console.log('✓ 第64关2–5人两端均禁止共享／个人／探测器／稳定器影响，拒绝字节不变；双线盲单拆猜同值但实际不同则真正失败、不提前剪其中正确一根；后段非开局证明');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),{choiceGame}=require('./double-outward.fixture'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb64-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  const example=choiceGame(n);let G=example.G;const {pair,target,value}=example,name='bb-doubleout'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'双端凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:64,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'双端观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  function restore(label,p,a){service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'暂停',paused:true});const paused=JSON.stringify(G);send(p,label+'暂停回应',a);assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'继续',paused:false});}
  connect();send(0,'偏好左但猜右值',{a:'outward-dual',own:pair[0],w:target,val:value});const id=G.pending.id;for(const ws of [...peers,observer])assert(!('preferredOwn' in last(ws,'official:view').view.pending));restore('目标',1,{a:'resolve',id,w:target});send(1,'目标确认',{a:'resolve',id,w:target});assert.equal(G.pending.step,'own');assert.deepEqual(last(peers[0],'official:view').view.pending.choices,pair);assert.equal(last(peers[0],'official:view').view.pending.preferredOwn,pair[0]);assert(!last(peers[1],'official:view').view.pending.choices);service.handle(observer,'official:perspective',{pid:seats[0].pid});const watched=last(observer,'official:view').view;assert(!watched.pending.choices);assert(!('preferredOwn' in watched.pending));assert(watched.players[0].stands.flat().filter(w=>pair.includes(w.id)).every(w=>w.v===null));restore('本人',0,{a:'resolve',id,w:pair[1]});const before=JSON.stringify(G);send(1,'冒充本人',{a:'resolve',id,w:pair[1]});assert.equal(JSON.stringify(G),before);send(0,'旧本人回复',{a:'resolve',id:id-1,w:pair[1]});assert.equal(JSON.stringify(G),before);send(0,'改选右端',{a:'resolve',id,w:pair[1]});assert(G.wires[pair[1]].cut);assert(!G.wires[pair[0]].cut);assert.equal(G.det,0);const once=JSON.stringify(G),revision=room.revision;send(0,'改选右端',{a:'resolve',id,w:pair[1]});assert.equal(room.revision,revision);assert.equal(JSON.stringify(G),once);for(const ws of [...peers,observer])assert.equal(last(ws,'official:view').view.det,0);wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第64关2–5人权威：左端偏好不在目标阶段发布，目标／本人各阶段暂停重启凭据重连后可改右端；菜单及偏好仅本人，观战选择该玩家仍剔除且双线隐藏，冒用／旧回复拒绝、重复一次剪线，零额外罚格');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',64),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧双端'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.doubleOutward(G),false);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.deepEqual(G.mission.rules,saved.mission.rules);}
}
console.log('✓ 第64关旧版本17改编保存／原任务与视图保留，不强制改为双端朝外玩法');
