const assert=require('assert'),fs=require('fs'),path=require('path'),{choiceGame}=require('./double-outward.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb64-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('双端夹具只允许隔离本机服务器');
function fixture(n){const ex=choiceGame(n),G=ex.G,code='D'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:64,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,pair:ex.pair,target:ex.target,value:ex.value};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'双端观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='double-outward-wires');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert((await page.locator('.all-outward-notice').innerText()).includes('每人两根'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}const own=await pages[0].evaluate(()=>window.testView);assert(own.players[0].stands.flat().filter(w=>data.pair.includes(w.id)).every(w=>w.v===null));assert.equal(await pages[0].locator('[data-act="outward-own"]').count(),2);if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  if(n%2)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();await pages[0].locator('[data-act="outward-own"][data-own="'+data.pair[0]+'"]').click();assert.equal(await pages[0].locator('[data-act="outward-own"][data-own="'+data.pair[0]+'"]').getAttribute('aria-pressed'),'true');await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"],#scr-game .slot.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="'+data.value+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='target')));for(const page of pages){assert(!('preferredOwn' in (await page.evaluate(()=>window.testView)).pending));assert(await page.locator('.declared-target[data-w="'+data.target+'"] .target-arrow').count()>0);}
  await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(data.code);await pages[1].locator('#btn-join').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');assert.deepEqual((await pages[0].evaluate(()=>window.testView)).pending.choices,data.pair);assert((await pages[0].locator('.act').innerText()).includes('可更改先前选择'));assert(!('preferredOwn' in (await pages[n].evaluate(()=>window.testView)).pending));
  await pages[n].locator('#spectator-perspective').selectOption(data.seats[0].pid);await pages[n].waitForFunction(()=>window.testView?.perspective==='p0');const watched=await pages[n].evaluate(()=>window.testView);assert(!watched.pending.choices);assert(!('preferredOwn' in watched.pending));assert(watched.players[0].stands.flat().filter(w=>data.pair.includes(w.id)).every(w=>w.v===null));
  await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[0].locator('#scr-game .tile.can[data-w="'+data.pair[1]+'"],#scr-game .slot.can[data-w="'+data.pair[1]+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(id=>!window.testView?.pending&&window.testView.players[0].stands.flat().find(w=>w.id===id).cut,data.pair[1])));
  for(const page of pages){const V=await page.evaluate(()=>window.testView);assert.equal(V.det,0);assert(!V.players[0].stands.flat().find(w=>w.id===data.pair[0]).cut);assert.equal(V.players[0].stands.flat().find(w=>w.id===data.pair[1]).v,data.value);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.equal((await pages[0].evaluate(()=>window.testView)).players[0].stands.flat().find(w=>w.id===data.pair[0]).v,null);
  console.log('✓ 第64关'+n+'人375像素双视图加观众：双端说明／本人两值隐藏、左右偏好按钮可读，实际点线与公共目标箭头，目标／本人各刷新恢复、确认后改选右端成功／左端仍隐藏未剪、偏好不在目标阶段发布、全员零罚格／无异常溢出；来源场景非完整整局证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
