// 内部恢复后的真实浏览器显示与电池再用；不模拟/认证自动触发时机。
const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),{create,unlock}=require('./emergency-reserve.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb55-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('储备箱夹具只允许隔离本机服务器');
function fixture(n,applied){const G=create(n);unlock(G);G.turn=1;if(applied)assert.equal(BB.applyEquipmentEffect(G,{gid:G.gid,n:15},{serverEquipment:true}),null);const code='R'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const [n,applied] of [[2,false],[2,true],[3,true],[4,true],[5,true]]){const data=fixture(n,applied),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'储备箱观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.equip?.some(e=>e.n===15));}
  for(let mode=0;mode<2;mode++){for(const page of pages){const V=await page.evaluate(()=>window.testView);assert.equal(V.equip.find(e=>e.n===15).used,applied);assert(V.players.every(p=>p.character.used&&!p.dd));assert.equal(V.turn,1);assert.equal(V.det,0);const box=page.locator('.card3[data-n="15"],.eq[data-n="15"]');assert((await box.innerText()).includes('3·3'));assert((await box.innerText()).includes(applied?'已结算':'即时效果尚未开放'));const battery=page.locator('.card3[data-n="7"],.eq[data-n="7"]');assert.equal(await battery.evaluate(e=>e.classList.contains('used')),!applied);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  const A=pages[0];if(!applied){const before=await A.evaluate(()=>window.testRevision);await A.locator('.eq[data-n="15"]').click();assert.equal(await A.locator('[data-act="eqinstant"]').count(),0);assert((await A.locator('.act').innerText()).includes('触发时机'));assert.equal(await A.evaluate(()=>window.testRevision),before);console.log('✓ 储备箱印刷3·3／双视图可查完整效果，但无客户端激活按钮，未自行认证自动时机');continue;}
  await A.locator('.eq[data-n="7"]').click();await A.locator('[data-act="battery-p"][data-p="0"]').click();await A.locator('[data-act="battery-go"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView.players[0].dd===1&&window.testView.equip.find(e=>e.n===7).used)));
  for(const page of pages){const V=await page.evaluate(()=>window.testView);assert(!V.players[0].character.used);assert(V.players.slice(1).every(p=>p.character.used&&!p.dd));assert(V.equip.find(e=>e.n===15).used);assert.equal(V.turn,1);assert.equal(V.det,0);}
  await A.reload({waitUntil:'domcontentloaded'});await A.locator('#jcode').fill(data.code);await A.locator('#btn-join').click();await A.waitForFunction(()=>window.testView?.players[0].dd===1&&window.testView.equip.find(e=>e.n===15).used);
  console.log('✓ 储备箱'+n+'人375像素双视图：内部恢复快照显示共享卡可再用／个人仍已用，电池真实再用仅恢复所选角色、观战同步／刷新保留；非实时自动触发证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
