const assert=require('assert'),fs=require('fs'),path=require('path'),F=require('./free-turn.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb10-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('抢回合夹具只允许隔离本机服务器');
function fixture(n){const G=F.game(n);F.setup(G);F.give(G,1,0);F.give(G,2,1);const code='F'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:10,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,deadline:G.deadline};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
 for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'轮序观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='timed-free-turn');}
 for(const page of pages){assert((await page.locator('[aria-label="限时自由轮序"]').innerText()).includes('等待抢回合'));assert(await page.locator('#timer').count());assert.equal(await page.locator('[aria-label="你的回合"]').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.equal(await pages[n].locator('[data-act="turn-claim"]').count(),0);
 await pages[1].locator('[data-act="turn-claim"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.freeTurn?.actor===1)));assert((await pages[1].locator('[aria-label="你的回合"]').innerText()).includes('轮到你'));await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(data.code);await pages[1].locator('#btn-join').click();await pages[1].waitForFunction(()=>window.testView?.official?.freeTurn?.actor===1);await pages[1].locator('[data-act="solo"][data-v="2"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.freeTurn?.decisionId===2)));assert.equal(await pages[1].locator('[data-act="turn-claim"]').isDisabled(),n>2);
 for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();await pages[0].locator('[data-act="turn-claim"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.freeTurn?.actor===0)));await pages[0].locator('[data-act="solo"][data-v="1"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.freeTurn?.decisionId===3)));
 for(const page of pages){const V=await page.evaluate(()=>window.testView);assert.equal(V.deadline,data.deadline);assert.equal(V.det,0);assert.equal(V.official.freeTurn.previous,0);assert((await page.locator('[aria-label="限时自由轮序"]').innerText()).includes('等待抢回合'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 console.log('✓ 第10关'+n+'人加观众375像素实际三维到二维：非队长抢先、本人回合通知、刷新保留行动者、真实两次四根单拆、多人禁连续／双人允许、所有人同一轮序和原截止、观众无抢回合入口、无异常溢出；重排后段非整局证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
