// 第五盒抓钩组件隔离联机验收；卡面用线夹具不认证55整关。
const assert=require('assert'),fs=require('fs'),path=require('path'),{create,unlock}=require('./grapple.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb55-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('抓钩夹具只允许隔离本机服务器');
function fixture(n,cap){const G=create(n,cap,n*7919+cap);unlock(G);G.turn=1;const code='H'+Date.now().toString(36).slice(-4).toUpperCase()+n,target=G.wires.find(w=>w.o===1&&!w.cut),seats=G.players.map((p,i)=>({...p,bot:false,credential:code+'凭据'+i}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,id:target.id,value:target.v,two:G.players[0].stands.length===2};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const [n,cap] of [[2,0],[3,0],[3,1],[4,0],[5,0]]){const data=fixture(n,cap),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'抓钩观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.equip?.some(e=>e.n===18));}
  const A=pages[0];assert.equal(await A.locator('.card3[data-n="18"] .cn').innerText(),'11·11');await A.locator('.card3[data-n="18"]').click();await A.locator('#scr-game .slot.can[data-w="'+data.id+'"]').click();await A.locator('#scr-game [data-act="view"]').click();assert.equal(await A.locator('.eq[data-n="18"] .eq-n').innerText(),'11·11');await A.locator('[data-act="eqgo"]').click();
  await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView.declaration?.type==='grapple')));
  for(const page of pages){assert((await page.locator('.grapple-notice').innerText()).includes('抓钩玩家1'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal((await page.evaluate(()=>window.testView)).turn,1);}
  if(data.two){for(let p=0;p<pages.length;p++){const V=await pages[p].evaluate(()=>window.testView);assert.equal('drawn' in V.pending,p===0);assert.equal('choices' in V.pending,p===0);assert.equal(await pages[p].locator('[data-act="grapple-rack"]').count(),p===0?2:0);}assert((await A.locator('.act').innerText()).includes('排序数值 '+data.value));await A.reload({waitUntil:'domcontentloaded'});await A.locator('#jcode').fill(data.code);await A.locator('#btn-join').click();await A.waitForFunction(()=>window.testView?.pending?.type==='grapple');await A.locator('[data-act="grapple-rack"][data-rack="1"]').click();}
  await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView.declaration?.destination)));
  for(let mode=0;mode<2;mode++){for(let p=0;p<pages.length;p++){const page=pages[p],V=await page.evaluate(()=>window.testView),wire=V.players[0].stands.flat().find(w=>w.id===data.id);assert.equal(wire.v,p===0?data.value:null);assert(V.equip.find(e=>e.n===18).used);assert.equal(V.turn,1);assert.equal(V.det,0);assert((await page.locator('.grapple-notice').innerText()).includes('已插入'));assert(await page.locator('.declared-target[data-w="'+data.id+'"] .target-arrow').count()>0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  console.log('✓ 抓钩'+n+'人队长'+cap+'375像素双视图：印刷11·11、非回合取线、公开原位置、'+(data.two?'私人值／架选择刷新恢复':'单架自动插入')+'、箭头标新位置、他人未知值、一次耗牌且不耗回合；组件非整关');
 }finally{for(const c of contexts)await c.close();}}
 assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
