// 隔离本机生成局面的界面／房主退出检查，不能代替官方败局裁定。
const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb43-wait-test-data';
if(!/^http:\/\/(localhost|127\.0\.0\.1):/.test(base)||!dir.startsWith('/tmp/'))throw Error('等待夹具仅供隔离本机');
const G=JSON.parse(fs.readFileSync('/tmp/bb43-wait-fixture.json','utf8')),code='W'+Date.now().toString(36).slice(-5).toUpperCase(),seats=G.players.map((p,pi)=>({pid:p.pid,name:p.name,bot:false,credential:'等待检查'+pi}));G.players.forEach(p=>p.bot=false);G.catalog=G.mission.catalog='campaign';
assert.equal(G.phase,'play');assert.equal(G.result,null);assert.equal(BB.recoverFatalState(G),false);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:43,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),contexts=[],pages=[],errors=[];try{
 for(let pi=0;pi<2;pi++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code,seat:pi===0?seats[0]:null});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(pi===0?seats[0].name:'等待观众');await page.locator('#jcode').fill(code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.nano?.waiting);}
 for(let mode=0;mode<2;mode++)for(const page of pages){const text=await page.locator('.nano-waiting').innerText();assert(text.includes('其他玩家的导线均已处理'));assert(text.includes('退出牌局'));assert(text.includes('炸弹尚未引爆'));const V=await page.evaluate(()=>window.testView);assert.equal(V.phase,'play');assert.equal(V.result,null);assert(!('revealed' in V.official.nano));assert(!('reserve' in V.official.nano));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('[data-act="view"]').click();}
 assert.equal(await pages[1].locator('[data-act="host-quit"]').count(),0);pages[0].once('dialog',d=>d.accept());await pages[0].locator('[data-act="host-quit"]').click();await pages[0].locator('#scr-lobby').waitFor({state:'visible'});await pages[1].locator('#scr-lobby').waitFor({state:'visible'});assert.deepEqual(errors,[]);console.log('✓ 第43关待裁定等待：手机二维／三维解释原因，不泄露备用值、不自动引爆；观战只读，房主退出返回房间可重开');
 }finally{for(const c of contexts)await c.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
