const assert=require('assert'),BB=require('../js/engine'),C=require('../js/campaign-rules'),Bot=require('../js/bot'),{game,setup,resort,give,rewards}=require('./number-rewards.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));}function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
function miss(G){const pi=G.turn,own=G.wires.find(w=>w.o===pi&&!w.cut&&Number.isInteger(w.v)),target=G.wires.find(w=>w.o!==pi&&!w.cut&&Number.isInteger(w.v)&&w.v!==own.v);assert(target);act(G,pi,{a:'dual',val:own.v,w:target.id});act(G,target.o,{a:'resolve',id:G.pending.id,w:target.id});}
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),s=BB.numberRewards(G);assert.equal(G.wires.length,n===2?51:50);assert.equal(G.rmark.n,n===2?3:2);assert.equal(G.rmark.cand.length,G.rmark.n);assert.equal(G.ymark.n,0);assert.equal(s.values.length,n);assert.equal(new Set(s.values).size,n);assert(s.values.every(v=>v>=1&&v<=12));assert.deepEqual(s.completed,[]);assert.equal(G.det,0);assert.equal(G.detMax,1);assert.equal(G.detMin,-4);setup(G);assert.equal(G.phase,'play');assert(G.players.every((_,p)=>G.setup[p]===1));assert.equal(G.deadline,null);for(let p=-1;p<n;p++)assert.deepEqual(BB.view(G,p).official.numberRewards,s);
}
console.log('✓ 第62关2–5人全部队长8种子：48蓝／已知红2或双人3、无黄、人数张随机唯一公开数字、橙色空格起点0／骷髅1／最早−4、普通初始和角色／无虚构计时');
{
 const G=game(4);setup(G);rewards(G);assert(BB.detonatorText(G).includes('还剩 1 格'));give(G,1,0);act(G,0,{a:'solo',val:1});assert(BB.detonatorText(G).includes('还剩 2 格'));assert(!BB.detonatorText(G).includes('人数起点'),'奖励后仍可能在普通人数起点之后，不能误称已退到其前面');
}
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);rewards(G);for(let i=0;i<n;i++)give(G,i+1,i);for(let i=0;i<n;i++){assert.equal(G.turn,i);act(G,i,{a:'solo',val:i+1});assert.equal(G.det,-Math.min(i+1,4));assert.equal(BB.numberRewards(G).completed.length,i+1);}assert.equal(G.phase,'play');const before=G.det;miss(G);assert.equal(G.det,before+1);assert.equal(BB.numberRewards(G).completed.length,n);const other=G.wires.find(w=>w.o===G.turn&&!w.cut&&Number.isInteger(w.v)&&w.v>n),value=other.v;give(G,value,G.turn);act(G,G.turn,{a:'solo',val:value});assert.equal(G.det,before+1,'已奖励值不能在下一次剪线时再后退');
 const H=game(n);setup(H);rewards(H);give(H,12,0);act(H,0,{a:'solo',val:12});assert.equal(H.det,0);assert.deepEqual(BB.numberRewards(H).completed,[]);
 const fatal=game(n);setup(fatal);miss(fatal);assert.equal(fatal.phase,'lost');assert.equal(fatal.det,1);
 const errors=game(n);setup(errors);rewards(errors);give(errors,1,0);act(errors,0,{a:'solo',val:1});assert.equal(errors.det,-1);miss(errors);assert.equal(errors.phase,'play');assert.equal(errors.det,0);miss(errors);assert.equal(errors.phase,'lost');assert.equal(errors.det,1);
}
console.log('✓ 第62关真实四根单拆每个选中值只奖一次、非选中值不奖，五人第五奖励在最早格不越界；后续错误不被重复奖励抵消，最初首错引爆、先一奖励后第二错引爆；后段非开局证明');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);rewards(G);const ones=G.wires.filter(w=>w.v===1);ones.forEach((w,i)=>{w.o=i===0?0:1;w.s=0;w.cut=i>=2;w.info=null;});resort(G);act(G,0,{a:'dual',w:ones[1].id,val:1});const id=G.pending.id;reject(G,0,{a:'resolve',id:id-1,w:ones[0].id});act(G,1,{a:'resolve',id,w:ones[1].id});assert.equal(G.pending.step,'own');assert.equal(G.det,0);assert.equal(BB.cutCount(G,1),2);assert.deepEqual(BB.numberRewards(G).completed,[]);const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'resolve',id,w:ones[0].id});act(saved,0,{a:'resolve',id,w:ones[0].id});assert.deepEqual(saved,G);assert.equal(G.det,-1);assert.deepEqual(BB.numberRewards(G).completed,[1]);reject(G,0,{a:'resolve',id,w:ones[0].id});
 const bot=game(n);setup(bot);bot.wires.filter(w=>w.v===6).slice(0,2).forEach(w=>w.cut=true);bot.equip=[{n:6,id:'rewinder',used:false}];const a=Bot.decide(bot,bot.turn);assert.deepEqual(a,{a:'equip',n:6});act(bot,bot.turn,a);assert.equal(bot.det,-1);assert(bot.equip[0].used);
}
console.log('✓ 第62关2–5人双拆目标公开／本人选择完成后才退格，保存恢复一致、重复不再奖；机器人在橙色最后一格会先用已解锁倒带器，个人卡不消耗');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);rewards(G);give(G,1,0);G.wires.filter(w=>w.v===10).forEach(w=>w.cut=true);G.equip=[{n:17,id:'disintegrator',used:false}];const event={gid:G.gid,n:17,generation:0,edition:'fr'},tokens=C.availableInfoTokens(G,false),index=tokens.findIndex(t=>t.value===1);assert(index>=0);const opts={serverEquipment:true,rng:()=>(index+.5)/tokens.length},saved=JSON.parse(JSON.stringify(G));const before=JSON.stringify(G);assert(BB.act(G,G.turn,{a:'equip',n:17}));assert.equal(JSON.stringify(G),before);assert.equal(BB.applyEquipmentEffect(G,event,opts),null);assert.equal(BB.applyEquipmentEffect(saved,event,opts),null);assert.deepEqual(saved,G);assert.equal(BB.cutCount(G,1),4);assert.equal(G.det,-1);assert.deepEqual(BB.numberRewards(G).completed,[1]);miss(G);assert.equal(G.det,0);const once=JSON.stringify(G);assert.equal(BB.applyEquipmentEffect(G,event,{serverEquipment:true,rng:()=>{throw Error('重复不应重抽');}}),null);assert.equal(JSON.stringify(G),once);
}
console.log('✓ 第62关明确法文分解器内部组件完成选中值也仅奖励一次，保存恢复／重复不重抽不重复退格、客户端无触发入口；不认证即时自动时机或德文可选效果');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb62-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=game(n);setup(G);rewards(G);const ones=G.wires.filter(w=>w.v===1);ones.forEach((w,i)=>{w.o=i===0?0:1;w.s=0;w.cut=i>=2;w.info=null;});G.wires.filter(w=>w.v===10).forEach(w=>w.cut=true);G.wires.filter(w=>w.v===2).forEach(w=>w.info=null);G.equip=[{n:17,id:'disintegrator',used:false}];resort(G);const name='bb-reward'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'奖励凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:62,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'奖励观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  function restore(label){service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'暂停',paused:true});wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'继续',paused:false});}
  connect();send(0,'奖励双拆',{a:'dual',val:1,w:ones[1].id});const id=G.pending.id;restore('目标');assert.equal(G.det,0);send(1,'目标回应',{a:'resolve',id,w:ones[1].id});assert.equal(G.pending.step,'own');restore('本人');assert.equal(G.det,0);assert.deepEqual(BB.numberRewards(G).completed,[]);send(0,'本人选择',{a:'resolve',id,w:ones[0].id});assert.equal(G.det,-1);assert.deepEqual(BB.numberRewards(G).completed,[1]);const once=JSON.stringify(G),revision=room.revision;send(0,'本人选择',{a:'resolve',id,w:ones[0].id});assert.equal(room.revision,revision);assert.equal(JSON.stringify(G),once);for(const ws of [...peers,observer]){const V=last(ws,'official:view').view;assert.equal(V.det,-1);assert.deepEqual(V.official.numberRewards.completed,[1]);}
  const event={gid:G.gid,n:17,generation:0,edition:'fr'},tokens=C.availableInfoTokens(G,false),index=tokens.findIndex(t=>t.value===2);assert(index>=0);assert.equal(service.applyEquipmentEffect(name,event,{rng:()=>(index+.5)/tokens.length}),null);assert.equal(G.det,-2);assert.deepEqual(BB.numberRewards(G).completed,[1,2]);restore('分解后');const applied=JSON.stringify(G),appliedRevision=room.revision;let calls=0;assert.equal(service.applyEquipmentEffect(name,event,{rng:()=>{calls++;return .9;}}),null);assert.equal(calls,0);assert.equal(room.revision,appliedRevision);assert.equal(JSON.stringify(G),applied);for(const ws of [...peers,observer]){const V=last(ws,'official:view').view;assert.equal(V.det,-2);assert.deepEqual(V.official.numberRewards.completed,[1,2]);assert(!V.equipmentEffects);}wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第62关2–5人权威目标／本人逐阶段暂停重启凭据重连，完整配对后才奖励且重复不再退；内部法文分解器第二数字奖励经重启重复不重抽／不再奖、全员同步／账本私有；后段组件非自动时机证明');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',62),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧奖励'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.numberRewards(G),null);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.equal(G.detMax,saved.detMax);}
}
console.log('✓ 第62关旧版本17改编保存与原引爆器／任务保持，不追加橙色起点或数字奖励');
