const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup,give}=require('./number-relay.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb65-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('接力夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);const value=G.officialState.numberRelay.hands[0][0];give(G,value,0);const code='N'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:65,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,value};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(const n of [3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
 for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'数字牌观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='number-card-relay');}
 for(let mode=0;mode<2;mode++){for(const page of pages){assert((await page.locator('[aria-label="数字牌接力"]').innerText()).includes('官方仅3–5人'));assert.equal(await page.locator('[aria-label="数字牌接力"] .route-card').count(),12);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert(await pages[0].locator('[data-act="number-relay-skip"]').isDisabled());if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
 await pages[0].locator('[data-act="solo"][data-v="'+data.value+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.type==='number-relay')));assert((await pages[0].locator('.turn-notice').innerText()).includes('传数字牌'));for(const page of pages.slice(1))assert.equal(await page.locator('[data-act="number-relay-card"]').count(),0);assert.equal(await pages[0].locator('[data-act="number-relay-card"]').count(),n===3?4:3);await pages[n].locator('#spectator-perspective').selectOption('p0');await pages[n].waitForFunction(()=>window.testView?.perspective==='p0');assert(!((await pages[n].evaluate(()=>window.testView)).pending.choices));
 await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.pending?.type==='number-relay');await pages[0].locator('[data-act="number-relay-card"][data-value="'+data.value+'"]').click();await pages[0].locator('[data-act="number-relay-recipient"][data-p="1"]').click();await pages[0].locator('[data-act="number-relay-confirm"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.turn===1&&!window.testView.pending)));
 for(const page of pages){const V=await page.evaluate(()=>window.testView),r=V.official.numberRelay;assert.equal(r.hands.flat().length,12);assert(r.hands[1].some(c=>c.value===data.value&&c.completed));assert(!r.hands[0].some(c=>c.value===data.value));assert.equal(V.det,0);assert.equal(V.turnNo,2);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 console.log('✓ 第65关'+n+'人375像素双视图加观众：12数字／对应值及匹配时跳过禁用、真实四根单拆翻背面、私有传牌选择及本人提示、观战切本人不获菜单、刷新继续传背面给队友，全员牌守恒／下一回合同步／零罚格无异常溢出；后段非整局证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
