const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup,resort,rewards}=require('./number-rewards.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb62-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('奖励夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);rewards(G);const ones=G.wires.filter(w=>w.v===1);ones.forEach((w,i)=>{w.o=i===0?0:1;w.s=0;w.cut=i>=2;w.info=null;});resort(G);const code='N'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:62,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,own:ones[0].id,target:ones[1].id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'奖励观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='number-completion-rewards');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert.equal(await page.locator('[data-number-reward]').count(),n);assert((await page.locator('[data-number-reward="1"]').innerText()).includes('2/4'));assert((await page.locator('[aria-label="完成数字奖励"]').innerText()).includes('再前进 1 格引爆'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  if(n%2)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"],#scr-game .slot.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="1"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='target')));for(const page of pages)assert(await page.locator('.declared-target[data-w="'+data.target+'"] .target-arrow').count()>0);
  await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(data.code);await pages[1].locator('#btn-join').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');for(const page of pages){assert.equal((await page.evaluate(()=>window.testView)).det,0);assert(!(await page.locator('[data-number-reward="1"]').innerText()).includes('已奖励'));}
  await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[0].locator('#scr-game .tile.can[data-w="'+data.own+'"],#scr-game .slot.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.det===-1&&!window.testView.pending)));
  for(let mode=0;mode<2;mode++){for(const page of pages){assert((await page.locator('[data-number-reward="1"]').innerText()).includes('4/4 · 已奖励'));assert((await page.locator('[aria-label="完成数字奖励"]').innerText()).includes('再前进 2 格引爆'));assert.equal(await page.locator('[data-number-reward].route-back').count(),1);assert.equal((await page.evaluate(()=>window.testView)).detMax,1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  console.log('✓ 第62关'+n+'人375像素双视图加观众：人数张奖励数字／2/4、真实二维及三维点线与公共箭头，两阶段各刷新恢复且未提前奖励，配对完成后全员4/4已奖励／距引爆2格，无页面异常及横向溢出；后段非整局验证');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
