const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup}=require('./number-bound.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb57-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('绑定夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);const b=G.officialState.constraints.bindings,i=b.indexOf('G');[b[i],b[0]]=[b[0],b[i]];const ones=G.wires.filter(w=>w.v===1);ones.forEach((w,i)=>{w.o=i===0?0:1;w.s=0;w.cut=i>=2;w.info=null;});G.players.forEach((p,o)=>p.stands=p.stands.map((_,s)=>G.wires.filter(w=>w.o===o&&w.s===s).sort((a,b)=>a.v-b.v||a.id-b.id).map(w=>w.id)));const code='B'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:57,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,own:ones[0].id,target:ones[1].id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'绑定观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='number-bound-constraints');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert.equal(await page.locator('.bound-card').count(),12);assert((await page.locator('.bound-constraints').innerText()).includes('尚无生效限制'));if(await page.locator('.bound-card[data-bound="1"]').getAttribute('open')===null)await page.locator('.bound-card[data-bound="1"] summary').click();assert((await page.locator('.bound-card[data-bound="1"] p').innerText()).includes('不能使用'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="1"]').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');assert.equal((await pages[0].evaluate(()=>window.testView)).official.constraints.active,null);await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');assert.equal((await pages[0].evaluate(()=>window.testView)).official.constraints.active,null);await pages[0].locator('#scr-game .tile.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView?.official?.constraints.active==='G')));
  for(const page of pages){assert((await page.locator('.bound-constraints').innerText()).includes('G 禁用装备'));assert.equal(await page.locator('.bound-card.completed').count(),1);assert.equal((await page.evaluate(()=>window.testView)).det,0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  console.log('✓ 第57关'+n+'人375像素双视图：12张绑定卡／展开完整规则、最初无限制、两阶段完成前不变／第四根后全员同步G、已完成卡标记与观战，零额外罚格；非整局验证');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
