const assert=require('assert'),BB=require('../js/engine'),{game,setup,resort,give,cardTo}=require('./number-relay.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));const cards=G.officialState.numberRelay.hands.flat();assert.equal(cards.length,12);assert.equal(new Set(cards).size,12);}
function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
assert.throws(()=>game(2),/不能双人/);
for(const n of [3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),s=G.officialState.numberRelay;assert.equal(G.wires.length,51);assert.equal(G.rmark.n,3);assert.equal(G.rmark.cand.length,3);assert.equal(G.ymark.n,0);assert.equal(G.officialState.numberRelay.hands.flat().length,12);assert.equal(new Set(G.officialState.numberRelay.hands.flat()).size,12);for(let p=0;p<n;p++)assert.equal(G.officialState.numberRelay.hands[p].length,n===3?4:n===4?3:p===cap||p===(cap+1)%n?3:2);assert(G.equip.every(e=>e.n!==10));assert(G.players.every(p=>p.character.id!=='xy-ray'));setup(G);assert.equal(G.phase,'play');assert.equal(G.deadline,null);assert(G.players.every((_,p)=>G.setup[p]===1));for(let p=-1;p<n;p++)assert.equal(BB.view(G,p).official.numberRelay.hands.flat().length,12);
}
console.log('✓ 第65关官方双人拒绝／3–5人所有队长8种子：48蓝／3已知红无黄、十二唯一公开数字，五人队长及左邻3张其余2、角色及X/Y排除、普通初始／无计时');
for(const n of [3,4,5]){const G=game(n);setup(G);for(let owner=0;owner<n;owner++){const V=BB.view(G,owner),hand=G.officialState.numberRelay.hands[owner];for(let value=1;value<=12;value++){assert.equal(BB.seqAllowed(G,value,owner),hand.includes(value));assert.equal(BB.seqAllowed(V,value,owner),hand.includes(value));}const matching=hand.some(value=>G.wires.some(w=>w.o===owner&&!w.cut&&w.v===value));assert.equal(BB.relayMatching(G,owner),matching);assert.equal(BB.relayMatching(V,owner),matching);}}
console.log('✓ 第65关3–5人每个玩家的所有权和匹配：数字状态／卡牌对象视图都按本人手牌判断，不误用当前玩家的数字牌或让未持有数字可拆');
for(const n of [3,4,5]){
 const G=game(n);setup(G);const s=G.officialState.numberRelay,value=G.officialState.numberRelay.hands[0][0];give(G,value,0);const invalid=G.wires.find(w=>w.o===0&&!w.cut&&Number.isInteger(w.v)&&!G.officialState.numberRelay.hands[0].includes(w.v));assert(invalid);reject(G,0,{a:'solo',val:invalid.v});reject(G,0,{a:'number-relay-skip'});act(G,0,{a:'solo',val:value});assert.equal(G.pending.type,'number-relay');assert.equal(G.pending.to,0);assert(!G.pending.retiring);assert(G.officialState.numberRelay.completed.includes(value));assert.equal(G.turn,0);assert.equal(G.turnNo,1);const id=G.pending.id;reject(G,1,{a:'number-relay',id,value,recipient:1});reject(G,0,{a:'number-relay',id:id-1,value,recipient:1});reject(G,0,{a:'number-relay',id,value,recipient:0});const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'number-relay',id,value,recipient:1});act(saved,0,{a:'number-relay',id,value,recipient:1});assert.deepEqual(saved,G);assert(!G.pending);assert.equal(G.turn,1);assert.equal(G.turnNo,2);assert(!G.officialState.numberRelay.hands[0].includes(value));assert(G.officialState.numberRelay.hands[1].includes(value));reject(G,0,{a:'number-relay',id,value,recipient:1});
}
console.log('✓ 第65关对应数字限制实际生效／拒绝完全不变，真实四根单拆翻该牌背面后仍能传，传前回合不结束，保存一致／越权旧选择拒绝，十二牌恒定');
for(const n of [3,4,5]){
 const G=game(n);setup(G);const s=G.officialState.numberRelay,number=G.officialState.numberRelay.hands[1][0];G.wires.filter(w=>w.o===0).forEach(w=>{w.cut=true;w.info=null;});give(G,number,0);assert(!BB.relayMatching(G,0));act(G,0,{a:'number-relay-skip'});assert.equal(G.det,1);assert.equal(G.pending.type,'number-relay');assert.equal(G.turn,0);act(G,0,{a:'number-relay',id:G.pending.id,value:G.officialState.numberRelay.hands[0][0],recipient:1});assert.equal(G.turn,1);
 const H=game(n);setup(H);H.wires.filter(w=>w.v===11).slice(0,2).forEach(w=>w.cut=true);H.equip=[{n:11,id:'coffee-mug',used:false}];const before=JSON.stringify(H.officialState.numberRelay.hands);act(H,0,{a:'equip',n:11,p:2});assert.equal(H.turn,2);assert(!H.pending);assert.equal(JSON.stringify(H.officialState.numberRelay.hands),before);assert.equal(H.det,0);
}
console.log('✓ 第65关没有对应数字时真实罚格跳过仍须传牌，不允许有匹配值主动省动作；咖啡杯跳过整个回合且不传、不罚');
for(const retire of [false,true]){
 const G=game(3);setup(G);cardTo(G,5,0);const fives=G.wires.filter(w=>w.v===5);fives.forEach((w,i)=>{w.o=i===0?0:1;w.s=0;w.cut=i>=2;w.info=null;});if(retire)G.wires.filter(w=>w.o===1&&w.id!==fives[1].id).forEach(w=>{w.cut=true;w.info=null;});resort(G);act(G,0,{a:'dual',w:fives[1].id,val:5});const id=G.pending.id;act(G,1,{a:'resolve',id,w:fives[1].id});assert.equal(G.pending.step,'own');assert.equal(G.turnNo,1);act(G,0,{a:'resolve',id,w:fives[0].id});assert.equal(G.pending.type,'number-relay');assert.equal(G.pending.to,retire?1:0);assert.equal(G.pending.retiring,retire);assert(G.officialState.numberRelay.completed.includes(5));assert.equal(G.det,0);
 if(retire){const value=G.officialState.numberRelay.hands[1].find(v=>!G.officialState.numberRelay.completed.includes(v));act(G,1,{a:'number-relay',id:G.pending.id,value,recipient:2});assert.equal(G.phase,'lost');assert(!G.pending);}else{act(G,0,{a:'number-relay',id:G.pending.id,value:5,recipient:2});assert.equal(G.phase,'play');assert.equal(G.turn,1);}
}
console.log('✓ 第65关双拆仍目标先答／本人选线，两线完整后才翻数字及传牌；队友目标清空时先处理其传牌，传后仍有正面真实失败而不先推进回合；后段非开局证明');
{
 const G=game(3);setup(G);const s=G.officialState.numberRelay,value=s.hands[0].find(v=>G.wires.some(w=>w.o!==0&&!w.cut&&w.v===v));assert(value);const red=G.wires.find(w=>BB.kindOf(w)==='r');red.o=0;red.s=0;G.wires.filter(w=>w.o===0&&w.id!==red.id).forEach(w=>{w.cut=true;w.info=null;});s.hands[0].filter(v=>v!==value).forEach(v=>G.wires.filter(w=>w.v===v).forEach(w=>{w.cut=true;w.info=null;}));s.completed=Array.from({length:12},(_,i)=>i+1).filter(v=>BB.cutCount(G,v)===4);resort(G);assert(!s.completed.includes(value));act(G,0,{a:'red'});assert(G.pending.retiring);const done=JSON.parse(JSON.stringify(G));act(G,0,{a:'number-relay',id:G.pending.id,value,recipient:1});act(done,0,{a:'number-relay',id:done.pending.id,value,recipient:1});assert.deepEqual(done,G);assert.equal(G.phase,'play');assert(G.officialState.numberRelay.hands[0].every(v=>G.officialState.numberRelay.completed.includes(v)));assert.equal(G.det,0);
 const H=game(3);setup(H);for(const v of H.officialState.numberRelay.hands[0].slice())cardTo(H,v,1);act(H,0,{a:'number-relay-skip'});assert.equal(H.det,1);assert.equal(H.turn,1);assert(!H.pending);assert.equal(H.officialState.numberRelay.hands[0].length,0);
}
console.log('✓ 第65关最后红线免费公开仍须传牌，传出唯一正面后只留背面合法／保存一致；构造空数字手仍按不匹配跳过，不伪造新牌或待选择，空牌的精确官方例外仍待裁定');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb65-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [3,4,5]){
  let G=game(n);setup(G);const value=G.officialState.numberRelay.hands[0][0];give(G,value,0);const name='bb-numrelay'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'传牌凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:65,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'接牌观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  connect();send(0,'单拆翻牌',{a:'solo',val:value});assert.equal(G.pending.type,'number-relay');const id=G.pending.id;assert(last(peers[0],'official:view').view.pending.choices.includes(value));assert(!last(peers[1],'official:view').view.pending.choices);service.handle(observer,'official:perspective',{pid:seats[0].pid});assert(!last(observer,'official:view').view.pending.choices);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'传牌暂停',paused:true});const paused=JSON.stringify(G);send(0,'暂停传牌',{a:'number-relay',id,value,recipient:1});assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);assert.equal(G.pending.id,id);assert(G.officialState.numberRelay.completed.includes(value));service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'传牌恢复',paused:false});const before=JSON.stringify(G);send(1,'冒用传牌',{a:'number-relay',id,value,recipient:2});assert.equal(JSON.stringify(G),before);send(0,'旧传牌选择',{a:'number-relay',id:id-1,value,recipient:1});assert.equal(JSON.stringify(G),before);send(0,'传给自己',{a:'number-relay',id,value,recipient:0});assert.equal(JSON.stringify(G),before);send(0,'传出背面',{a:'number-relay',id,value,recipient:1});assert.equal(G.turn,1);assert.equal(G.turnNo,2);assert(!G.pending);assert(G.officialState.numberRelay.hands[1].includes(value));const once=JSON.stringify(G),revision=room.revision;send(0,'传出背面',{a:'number-relay',id,value,recipient:1});assert.equal(room.revision,revision);assert.equal(JSON.stringify(G),once);for(const ws of [...peers,observer]){const r=last(ws,'official:view').view.official.numberRelay;assert.equal(r.hands.flat().length,12);assert(r.hands[1].some(c=>c.value===value&&c.completed));}wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第65关3–5人权威背面传牌决定暂停重启凭据重连，牌已翻面／回合尚未推进保留，菜单仅本人／观战视角剔除，越权旧选择／自己接收拒绝、重复只一次移动，所有客户端十二牌同步');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',65),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧数字'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.numberRelay(G),null);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.deepEqual(G.mission.rules,saved.mission.rules);}
}
console.log('✓ 第65关旧版本17改编2–5人保存／原玩法保留，不强制应用官方双人禁令或数字传牌');
