const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),M=require('../js/missions');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb45-browser-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw new Error('只允许隔离本机测试');
function rng(s){return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296);}
function fixture(n){const code='C'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=Array.from({length:n},(_,i)=>({pid:code+'p'+i,name:'认领界面'+i,credential:code+'凭证'+i,bot:false}));let G,winner,target,missing;
 for(let seed=1;seed<500;seed++){
  G=BB.createGame(M.get('official-development',45),seats,{captain:0,rng:rng(seed*104729)});const owners=[...new Set(G.wires.filter(w=>w.v===3).map(w=>w.o))];if(owners.length<2)continue;winner=owners.find(o=>o!==0);target=G.wires.find(w=>w.o!==winner&&w.v===3);
  for(let value=1;value<=12;value++){if(value===3)continue;const owner=G.players.findIndex((_,o)=>!G.wires.some(w=>w.o===o&&w.v===value));if(owner>=0){missing={owner,value};break;}}if(missing)break;
 }
 assert(missing&&target);G.catalog=G.mission.catalog='campaign';G.officialState.numberClaim.deck=[3,missing.value,...G.officialState.numberClaim.deck.filter(v=>v!==3&&v!==missing.value)];fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:45,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,winner,target,missing};}
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(let n=2;n<=5;n++){
 const data=fixture(n),pages=[],contexts=[];let threeD=true;
 try{for(const seat of data.seats){const c=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(c);await c.addInitScript(({code,seat})=>{localStorage.setItem('bb_name',JSON.stringify(seat.name));localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));localStorage.setItem('bb_view3d','true');const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...a){super(...a);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat});const p=await c.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('#nm').fill(seat.name);await p.locator('#jcode').fill(data.code);await p.locator('#btn-join').click();await p.waitForFunction(()=>window.testView?.official?.module==='number-claim');}
 const host=pages[0];async function views(){const r=Math.max(...await Promise.all(pages.map(p=>p.evaluate(()=>window.testRevision))));await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,r)));return Promise.all(pages.map(p=>p.evaluate(()=>window.testView)));}
 async function advance(f){await views();const r=await host.evaluate(()=>window.testRevision);await f();await host.waitForFunction(r=>window.testRevision>r,r);await views();}
 async function wire(pi,id){await pages[pi].locator('#scr-game '+(threeD?'.slot.can':'.tile.can')+'[data-w="'+id+'"]').click();}
 async function toggle(){for(const p of pages)await p.locator('#scr-game [data-act=view]').click();threeD=!threeD;}
 while((await views())[0].phase==='setup'){const v=await views(),pi=BB.setupActor(v[0]),id=v[pi].players[pi].stands.flat().find(w=>!w.cut&&Number.isInteger(w.v)&&!w.info).id;await advance(()=>wire(pi,id));}
 for(let mode=0;mode<2;mode++){assert.equal(await host.locator('[data-act=claim-draw]').count(),1);for(let pi=1;pi<n;pi++)assert.equal(await pages[pi].locator('[data-act=claim-draw]').count(),0);await toggle();}
 await advance(()=>host.locator('[data-act=claim-draw]').click());let v=await views();assert.equal(v[0].official.numberClaim.value,3);for(const p of pages){assert.equal(await p.locator('[data-act=claim-number]').count(),1);assert((await p.locator('.number-claim-panel').innerText()).includes('3'));assert.equal(await p.locator('[data-act=claim-penalty]').count(),1);}
 await advance(()=>pages[data.winner].locator('[data-act=claim-number]').click());assert.equal((await views())[0].turn,data.winner);for(const p of pages)assert.equal(await p.locator('[data-act=claim-number]').count(),0);await wire(data.winner,data.target.id);await advance(()=>pages[data.winner].locator('[data-act=val][data-v="3"]').click());for(const p of pages){assert.equal(await p.locator('.declared-target').count(),1);assert.equal(await p.locator('[data-act=claim-penalty]').count(),1);}if(n>=3){const pending=(await views())[0].pending.id;await advance(()=>host.locator('[data-act=claim-penalty]').click());assert.equal((await views())[0].pending.id,pending);assert.equal((await views())[0].det,1);}await advance(()=>pages[data.target.o].locator('[data-act=resolve-target]').click());const own=(await views())[data.winner].pending.choices.at(-1);await advance(()=>wire(data.winner,own));assert.equal((await views())[0].official.numberClaim.step,'draw');
 await advance(()=>host.locator('[data-act=claim-draw]').click());assert.equal((await views())[0].official.numberClaim.value,data.missing.value);await advance(()=>host.locator('[data-act=claim-assign][data-p="'+data.missing.owner+'"]').click());v=await views();assert.equal(v[0].pending.type,'number-claim-clue');for(let pi=0;pi<n;pi++)assert.equal('choices'in v[pi].pending,pi===data.missing.owner);
 const decision=v[0].pending.id;await advance(()=>host.locator('[data-act=host-pause]').click());await pages[data.missing.owner].reload({waitUntil:'domcontentloaded'});await pages[data.missing.owner].locator('#jcode').fill(data.code);await pages[data.missing.owner].locator('#btn-join').click();await pages[data.missing.owner].waitForFunction(id=>window.testView?.pending?.id===id,decision);await advance(()=>host.locator('[data-act=host-pause]').click());
 for(let mode=0;mode<2;mode++){for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await pages[data.missing.owner].locator(threeD?'.slot.can':'.tile.can').count(),(await views())[data.missing.owner].pending.choices.length);await toggle();}
 const choice=(await views())[data.missing.owner].pending.choices[0];await advance(()=>wire(data.missing.owner,choice));v=await views();assert.equal(v[0].det,n===2?1:2);assert.equal(v[0].official.numberClaim.step,'draw');console.log('✓ 第45关开发版'+n+'人手机双视图：队长翻牌、认领／当前数字私人双拆、公开目标、指定缺值、私人线索暂停重连与罚格、回应中额外暗示报告通过');
 }finally{for(const c of contexts)await c.close();}
}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
