// 隔离本机整局参考玩法：测试程序可读快照选正确目标，产品客户端仍只收许可视图。
const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),{game,setup}=require('./number-relay.fixture'),{run}=require('./number-relay.reachability');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb65-whole-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('整局参考只允许隔离本机服务器与临时快照');
function fixture(n){const seed=1,variant=n===3?0:1,G=game(n,0,seed),code='L'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid})),file=path.join(dir,'bb-'+code.toLowerCase()+'.json');G.catalog=G.mission.catalog='campaign';const initial=JSON.stringify(G),practice=JSON.parse(initial);setup(practice);const plan=run(practice,variant);assert.equal(plan.G.phase,'won');assert.equal(JSON.stringify(G),initial);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:65,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,file,plan};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [3,5]){const data=fixture(n),pages=[],contexts=[];let acts=0,reds=0,index=0,passes=0,targetPasses=0,reconnected=false;try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'整局接力观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='number-card-relay');}
  let G;while(acts<300){G=JSON.parse(fs.readFileSync(data.file)).G;if(G.phase==='won'||G.phase==='lost')break;const command=G.phase==='setup'?null:data.plan.trace[index++];const pi=command?command.owner:BB.setupActor(G),page=pages[pi],revision=await page.evaluate(()=>window.testRevision),a=command?.action;const wire=id=>page.locator('#scr-game .tile.can[data-w="'+id+'"],#scr-game .slot.can[data-w="'+id+'"]');
   if(G.phase==='setup'){const w=G.wires.find(w=>w.o===pi&&!w.cut&&!w.info&&BB.setupInfoAllowed(G,w));await wire(w.id).click();}
   else if(a.a==='resolve'){if(G.pending.step==='target')await page.locator('[data-act="resolve-target"]').click();else await wire(a.w).click();}
   else if(a.a==='dual'){await wire(a.w).click();await page.locator('[data-act="val"][data-v="'+a.val+'"]').click();}
   else if(a.a==='solo')await page.locator('[data-act="solo"][data-v="'+a.val+'"]').click();
   else if(a.a==='red'){await page.locator('[data-act="red"]').click();reds++;}
   else if(a.a==='number-relay-skip')await page.locator('[data-act="number-relay-skip"]').click();
   else if(a.a==='number-relay'){if(pi!==G.turn)targetPasses++;if(!reconnected){await page.reload({waitUntil:'domcontentloaded'});await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.pending?.type==='number-relay');reconnected=true;}await page.locator('[data-act="number-relay-card"][data-value="'+a.value+'"]').click();await page.locator('[data-act="number-relay-recipient"][data-p="'+a.recipient+'"]').click();await page.locator('[data-act="number-relay-confirm"]').click();passes++;}
   else if(a.a==='equip'){await page.locator('#scr-game .card3[data-n="'+a.n+'"],#scr-game .eq[data-n="'+a.n+'"]').click();if(a.n===6)await page.locator('[data-act="eqinstant"]').click();else if(a.n===11)await page.locator('[data-act="eqp"][data-p="'+a.p+'"]').click();else throw Error('未实现的参考装备交互');}
   else throw Error('未实现的参考界面动作 '+JSON.stringify(a));
   await page.waitForFunction(old=>window.testRevision>old,revision);const newRevision=await page.evaluate(()=>window.testRevision);await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,newRevision)));if(command){const state=JSON.parse(fs.readFileSync(data.file)).G;assert.deepEqual(state.officialState.numberRelay.hands,command.hands);assert.deepEqual(state.officialState.numberRelay.completed,command.completed);assert.equal(state.turnNo,command.turnNo);assert.equal(state.turn,command.turn);assert.equal(state.det,command.det);assert.equal(state.phase,command.phase);}acts++;if(acts===30)for(const p of pages)await p.locator('#scr-game [data-act="view"]').click();
  }
  G=JSON.parse(fs.readFileSync(data.file)).G;assert.equal(G.phase,'won');assert(G.wires.every(w=>w.cut));assert.equal(index,data.plan.trace.length);assert(reds>0);assert(!G.pending);assert.equal(G.officialState.numberRelay.hands.flat().length,12);assert.equal(G.officialState.numberRelay.completed.length,12);for(const page of pages){await page.waitForFunction(()=>window.testView?.phase==='won');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  console.log('✓ 第65关'+n+'人加观众375像素完整来源发牌界面通关：'+acts+'个游戏动作／'+passes+'次传牌（目标清空'+targetPasses+'次）／'+reds+'次主动红线公开／'+data.plan.skips+'次不匹配跳过，实际三维到二维／传牌刷新恢复，每步数字所有权／翻面／回合／引爆器与参考一致，全员胜局同步／12牌守恒／无异常溢出；全信息参考非生产策略认证');

 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
