const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),M=require('../js/missions');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb47-browser-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw new Error('只允许隔离本机测试');
function rng(s){return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296);}
function fixture(n){const code='A'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=Array.from({length:n},(_,i)=>({pid:code+'p'+i,name:'算式界面'+i,credential:code+'凭证'+i,bot:false}));let G,target;
 for(let seed=1;seed<300;seed++){G=BB.createGame(M.get('official-development',47),seats,{captain:0,rng:rng(seed*104729)});target=G.wires.find(w=>w.o>0&&w.v===12);if(target&&G.wires.some(w=>w.o===0&&w.v===12))break;}assert(target);G.catalog=G.mission.catalog='campaign';const observer={pid:code+'watch',name:'算式观众',credential:code+'观战凭证',perspective:null};fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:47,ruleset:'campaign',attempts:1,started:true,seats,observers:[observer],revision:0,seen:[],G}),{mode:0o600});return {code,seats,observer,target};}
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(let n=2;n<=5;n++){
 const data=fixture(n),pages=[],contexts=[];let threeD=true;
 try{for(const identity of data.seats.concat([data.observer])){const c=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(c);await c.addInitScript(({code,identity})=>{localStorage.setItem('bb_pid',JSON.stringify(identity.pid));localStorage.setItem('bb_name',JSON.stringify(identity.name));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:identity.credential}));localStorage.setItem('bb_view3d','true');const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...a){super(...a);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,identity});const p=await c.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('#nm').fill(identity.name);await p.locator('#jcode').fill(data.code);await p.locator('#btn-join').click();await p.waitForFunction(()=>window.testView?.official?.module==='number-arithmetic');}
 const host=pages[0],observer=pages[n];async function views(){const r=Math.max(...await Promise.all(pages.map(p=>p.evaluate(()=>window.testRevision))));await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,r)));return Promise.all(pages.map(p=>p.evaluate(()=>window.testView)));}
 async function advance(f){await views();const r=await host.evaluate(()=>window.testRevision);await f();await host.waitForFunction(r=>window.testRevision>r,r);await views();}
 async function wire(pi,id){await pages[pi].locator((threeD?'.slot.can':'.tile.can')+'[data-w="'+id+'"]').click();}
 async function toggle(){for(const p of pages)await p.locator('[data-act=view]').click();threeD=!threeD;}
 while((await views())[0].phase==='setup'){const v=await views(),pi=BB.setupActor(v[0]),id=v[pi].players[pi].stands.flat().find(w=>!w.cut&&Number.isInteger(w.v)&&!w.info).id;await advance(()=>wire(pi,id));}
 for(let mode=0;mode<2;mode++){assert.equal(await host.locator('[data-act=arithmetic-card]').count(),12);assert.equal(await observer.locator('[data-act=arithmetic-card]').count(),0);for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await toggle();}
 await wire(0,data.target.id);assert(await host.locator('[data-act=val][data-v="12"]').isDisabled());await host.locator('[data-act=arithmetic-card][data-card="3"]').click();await host.locator('[data-act=arithmetic-card][data-card="9"]').click();await host.locator('[data-act=arithmetic-op][data-operation="difference"]').click();assert(await host.locator('[data-act=val][data-v="12"]').isDisabled());await host.locator('[data-act=arithmetic-op][data-operation="sum"]').click();assert(await host.locator('[data-act=val][data-v="12"]').isEnabled());
 await advance(()=>host.locator('[data-act=val][data-v="12"]').click());let v=await views();assert(v.every(view=>view.official.arithmetic.open.length===10));assert(v.every(view=>!('selection'in view.official.arithmetic)));await observer.locator('#spectator-perspective').selectOption(data.seats[0].pid);await observer.waitForFunction(pid=>window.testView.perspective===pid,data.seats[0].pid);assert(!('choices'in (await observer.evaluate(()=>window.testView)).pending));
 await advance(()=>host.locator('[data-act=host-pause]').click());const id=v[0].pending.id;await pages[data.target.o].reload({waitUntil:'domcontentloaded'});await pages[data.target.o].locator('#jcode').fill(data.code);await pages[data.target.o].locator('#btn-join').click();await pages[data.target.o].waitForFunction(id=>window.testView?.pending?.id===id,id);await advance(()=>host.locator('[data-act=host-pause]').click());await advance(()=>pages[data.target.o].locator('[data-act=resolve-target]').click());const own=(await views())[0].pending.choices.at(-1);await advance(()=>wire(0,own));v=await views();assert.equal(v[0].turn,1);assert.deepEqual(v[0].official.arithmetic.discard,[3,9]);
 await pages[1].locator('[data-act=arithmetic-card][data-card="1"]').click();await pages[1].locator('[data-act=arithmetic-card][data-card="2"]').click();await advance(()=>pages[1].locator('[data-act=arithmetic-skip]').click());v=await views();assert.equal(v[0].det,1);assert.deepEqual(v[0].official.arithmetic.discard,[3,9,1,2]);for(let mode=0;mode<2;mode++){for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await toggle();}
 console.log('✓ 第47关开发版'+n+'人＋观众手机双视图：选两牌／和差结果禁用、一次弃牌、私人回应暂停刷新、观战只读与弃牌跳过通过');
 }finally{for(const c of contexts)await c.close();}
}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
