const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup,resort}=require('./passing-oxygen.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb63-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('接力夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);const fives=G.wires.filter(w=>w.v===5);fives.forEach((w,i)=>{w.o=i<2?0:1;w.s=0;w.info=null;});resort(G);const code='P'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:63,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,total:G.officialState.passingOxygen.total,own:fives[1].id,other:fives[0].id,target:fives[2].id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'氧气观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='passing-oxygen');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert((await page.locator('[aria-label="氧气接力"]').innerText()).includes('持有 '+data.total+' 枚'));assert((await page.locator('[aria-label="氧气接力"]').innerText()).includes('中心库存 0 枚'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert(await pages[0].locator('[data-act="passing-oxygen-skip"]').isDisabled());assert((await pages[0].locator('[data-act="val"][data-v="5"]').getAttribute('title')).includes('需要 5 枚氧气'));if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  if(n%2)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"],#scr-game .slot.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="5"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='target')));for(const page of pages)assert(await page.locator('.declared-target[data-w="'+data.target+'"] .target-arrow').count()>0);
  await pages[1].reload({waitUntil:'domcontentloaded'});await pages[1].locator('#jcode').fill(data.code);await pages[1].locator('#btn-join').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='target');await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');for(const page of pages){const v=await page.evaluate(()=>window.testView);assert.equal(v.det,0);assert.equal(v.official.passingOxygen.available,data.total-5);assert.equal(v.official.passingOxygen.reserve,5);assert.equal(v.official.passingOxygen.holder,0);}

  await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[0].locator('#scr-game .tile.can[data-w="'+data.own+'"],#scr-game .slot.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.passingOxygen.holder===1&&!window.testView.pending)));
  for(let mode=0;mode<2;mode++){for(const page of pages){const v=await page.evaluate(()=>window.testView);assert.equal(v.official.passingOxygen.available,data.total-5);assert.equal(v.official.passingOxygen.reserve,5);assert((await page.locator('[aria-label="氧气接力"]').innerText()).includes('接力玩家1 持有 '+(data.total-5)+' 枚'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.equal((await pages[0].evaluate(()=>window.testView)).players[0].stands.flat().find(w=>w.id===data.other).cut,false);if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  console.log('✓ 第63关'+n+'人375像素双视图加观众：库存／持有人和费用5可读、可行动时禁止省氧跳过，真实二维三维点线及公共箭头，两阶段各刷新不重复扣／不提前交氧，选第二副本后全员同步余量给下一位，总量守恒／无异常溢出；后段非整局证明');

 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
