const assert=require('assert'),BB=require('../js/engine'),{game,setup,resort,give,budget}=require('./passing-oxygen.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));const s=BB.passingOxygen(G);assert.equal(s.available+s.reserve,s.total);assert(s.available>=0&&s.reserve>=0);}
function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),s=BB.passingOxygen(G),total=n===2?14:n*6;assert.equal(G.wires.length,n===2?51:50);assert.equal(G.rmark.n,n===2?3:2);assert.equal(G.rmark.cand.length,G.rmark.n);assert.equal(G.ymark.n,0);assert.equal(s.total,total);assert.equal(s.available,total);assert.equal(s.reserve,0);assert.equal(s.holder,cap);assert(G.equip.every(e=>e.n!==10));assert(G.players.every(p=>p.character.id!=='xy-ray'));assert(G.mission.rules.noChat);setup(G);assert.equal(G.phase,'play');assert.equal(G.deadline,null);assert(G.players.every((_,p)=>G.setup[p]===1));for(let p=-1;p<n;p++){const v=BB.view(G,p).official.passingOxygen;assert.equal(v.total,total);assert.equal(v.holder,cap);assert.equal(v.available,total);assert.equal(v.reserve,0);}
}
console.log('✓ 第63关2–5人全部队长8种子：48蓝／已知红2或双人3无黄、队长14／18／24／30氧气、初始库存0、普通初始、排除共享与个人X/Y、水下禁聊／无虚构计时');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);give(G,5,0);const total=BB.passingOxygen(G).total;reject(G,0,{a:'solo',val:13});reject(G,0,{a:'dual',val:5,w:99999});reject(G,0,{a:'passing-oxygen-skip'});act(G,0,{a:'solo',val:5});assert.equal(G.turn,1);assert.equal(BB.passingOxygen(G).holder,1);assert.equal(BB.passingOxygen(G).available,total-5);assert.equal(BB.passingOxygen(G).reserve,5);assert.equal(G.det,0);
 const H=game(n);setup(H);for(let i=0;i<n;i++)give(H,i+1,i);for(let i=0;i<n;i++){assert.equal(H.turn,i);act(H,i,{a:'solo',val:i+1});}assert.equal(H.turn,0);assert.equal(BB.passingOxygen(H).holder,0);assert.equal(BB.passingOxygen(H).available,total);assert.equal(BB.passingOxygen(H).reserve,0);
}
console.log('✓ 第63关真实四根蓝5单拆只扣5枚，余量交下一位／库存5；整轮后队长取回库存，总量守恒，不按分段费或每根累加；非法目标／数值／主动省氧跳过完全回滚');
for(const n of [2,3,4,5])for(const hit of [true,false]){
 const G=game(n);setup(G);const fives=G.wires.filter(w=>w.v===5);fives.forEach((w,i)=>{w.o=i<2?0:1;w.s=0;w.info=null;});resort(G);let target=fives[2];if(!hit){target=G.wires.find(w=>Number.isInteger(w.v)&&w.v!==5&&!w.cut);target.o=1;target.s=0;target.info=null;resort(G);}const total=BB.passingOxygen(G).total;
 act(G,0,{a:'dual',val:5,w:target.id});assert.equal(BB.passingOxygen(G).available,total-5);assert.equal(BB.passingOxygen(G).reserve,5);assert.equal(BB.passingOxygen(G).holder,0);const id=G.pending.id;reject(G,0,{a:'resolve',id:id-1,w:fives[0].id});act(G,1,{a:'resolve',id,w:target.id});assert.equal(BB.passingOxygen(G).available,total-5);if(hit){assert.equal(G.pending.step,'own');const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'resolve',id,w:fives[1].id});act(saved,0,{a:'resolve',id,w:fives[1].id});assert.deepEqual(saved,G);assert(!G.wires[fives[0].id].cut);}assert.equal(BB.passingOxygen(G).reserve,5);assert.equal(BB.passingOxygen(G).holder,1);assert.equal(G.det,hit?0:1);assert.equal(G.phase,'play');
}
console.log('✓ 第63关2–5人成功／失败双拆均先付5，目标及本人阶段不再扣；本人可选第二副本，保存一致，结算后才交氧，失败另外罚一格且不退款');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);give(G,10,1);G.wires.filter(w=>w.o===1&&w.v!==10).forEach(w=>{w.cut=true;w.info=null;});budget(G,1,9);reject(G,1,{a:'solo',val:10});reject(G,1,{a:'passing-oxygen-skip',stab:true});act(G,1,{a:'passing-oxygen-skip'});assert.equal(G.det,1);assert.notEqual(G.turn,1);assert.equal(BB.passingOxygen(G).holder,G.turn);assert.equal(BB.passingOxygen(G).available,n===2?14:9);
 const fatal=game(n);setup(fatal);give(fatal,10,1);fatal.wires.filter(w=>w.o===1&&w.v!==10).forEach(w=>{w.cut=true;w.info=null;});budget(fatal,1,9);fatal.det=fatal.detMax-1;act(fatal,1,{a:'passing-oxygen-skip'});assert.equal(fatal.phase,'lost');assert.equal(BB.passingOxygen(fatal).available,9);
 const R=game(n);setup(R);const red=R.wires.find(w=>BB.kindOf(w)==='r');red.o=1;red.s=0;R.wires.filter(w=>w.o===1&&w.id!==red.id).forEach(w=>{w.cut=true;w.info=null;});resort(R);budget(R,1,0);assert(BB.passingAffordable(R,1));reject(R,1,{a:'passing-oxygen-skip'});act(R,1,{a:'red'});assert(R.wires[red.id].cut);assert.equal(R.det,0);
}
console.log('✓ 第63关只剩蓝10而氧9时才可罚格跳过，不退款／到尽头真正失败；零氧仅红仍可免费公开，不允许跳过或未核实稳定器修饰；后段稀缺边界非完整开局证明');
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);give(G,5,1);give(G,4,1);G.wires.filter(w=>![4,5].includes(w.v)).forEach(w=>{w.cut=true;w.info=null;});budget(G,1,BB.passingOxygen(G).total-5);act(G,1,{a:'solo',val:5});assert.equal(G.turn,1);assert.equal(BB.passingOxygen(G).available,BB.passingOxygen(G).total);assert.equal(BB.passingOxygen(G).reserve,0);act(G,1,{a:'solo',val:4});assert.equal(G.phase,'won');
 const H=game(n);setup(H);H.wires.filter(w=>w.v===11).slice(0,2).forEach(w=>w.cut=true);H.equip=[{n:11,id:'coffee-mug',used:false}];const to=n===2?1:2;act(H,0,{a:'equip',n:11,p:to});assert.equal(H.turn,to);assert.equal(BB.passingOxygen(H).holder,to);assert.equal(BB.passingOxygen(H).available,BB.passingOxygen(H).total);assert.equal(BB.passingOxygen(H).reserve,0);assert.equal(H.det,0);
 const signal=game(n);setup(signal);act(signal,1,{a:'passing-oxygen-signal'});assert(BB.passingOxygen(signal).requests[1]);assert.equal(signal.turn,0);assert.equal(signal.det,0);
}
console.log('✓ 第63关空手队长的顺时针位置仍补回库存，唯一剩余玩家接到全部氧气并真实单拆赢；队长咖啡杯将完整氧气交指定下一位且不罚格，非回合拇指不耗氧／回合；后段非整局证明');
{
 const G=game(2,0,8);setup(G);const twelve=G.wires.filter(w=>w.v===12);assert.equal(twelve.filter(w=>w.o===0).length,1);G.wires.filter(w=>Number.isInteger(w.v)&&w.v!==12).forEach(w=>{w.cut=true;w.info=null;});G.wires.filter(w=>!w.cut).forEach(w=>w.info=null);G.equip=[{n:18,id:'grapple',used:false}];G.det=1;const target=twelve.find(w=>w.o===0).id;act(G,1,{a:'equip',n:18,w:target});assert.equal(G.pending.type,'grapple');assert.equal(G.turn,0);assert.equal(BB.passingOxygen(G).holder,0);assert.equal(BB.passingOxygen(G).available,14);const saved=JSON.parse(JSON.stringify(G)),id=G.pending.id;act(G,1,{a:'grapple-rack',id,rack:1});act(saved,1,{a:'grapple-rack',id,rack:1});assert.deepEqual(saved,G);assert(G.wires.filter(w=>w.o===0&&!w.cut).every(w=>BB.kindOf(w)==='r'));act(G,0,{a:'red'});assert.equal(G.turn,1);assert.equal(BB.passingOxygen(G).available,14);act(G,1,{a:'solo',val:12});assert.equal(G.phase,'won');assert.equal(G.det,1);assert.equal(BB.passingOxygen(G).available,2);assert.equal(BB.passingOxygen(G).reserve,12);
}
console.log('✓ 第63关双人真实非回合抓钩收队长最后蓝12，私人放架前不交氧／不打断；队长红线免费公开交完整14，队友四根单拆12只付12后赢，无额外罚格，保存一致；后段非整局证明');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb63-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=game(n);setup(G);const fives=G.wires.filter(w=>w.v===5);fives.forEach((w,i)=>{w.o=i<2?0:1;w.s=0;w.info=null;});resort(G);const total=BB.passingOxygen(G).total,name='bb-passing'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'接力凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:63,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'氧气观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  function restore(label,p,a){service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'暂停',paused:true});const paused=JSON.stringify(G);send(p,label+'暂停回应',a);assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);assert.equal(BB.passingOxygen(G).available,total-5);assert.equal(BB.passingOxygen(G).reserve,5);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'继续',paused:false});}
  connect();const quiet=JSON.stringify(G);service.handle(peers[0],'chat',{text:'水下不应送出的消息'});assert.equal(JSON.stringify(G),quiet);assert(last(peers[0],'official:error'));assert(peers.every(ws=>!ws.messages.some(m=>m.topic==='chat')));send(0,'接力双拆',{a:'dual',val:5,w:fives[2].id});const id=G.pending.id;restore('目标',1,{a:'resolve',id,w:fives[2].id});assert.equal(BB.passingOxygen(G).holder,0);const before=JSON.stringify(G);send(0,'冒充目标',{a:'resolve',id,w:fives[2].id});assert.equal(JSON.stringify(G),before);send(1,'过期目标',{a:'resolve',id:id-1,w:fives[2].id});assert.equal(JSON.stringify(G),before);send(1,'目标回应',{a:'resolve',id,w:fives[2].id});assert.equal(G.pending.step,'own');restore('本人',0,{a:'resolve',id,w:fives[1].id});send(0,'本人选第二副本',{a:'resolve',id,w:fives[1].id});assert.equal(BB.passingOxygen(G).holder,1);assert.equal(BB.passingOxygen(G).available,total-5);assert.equal(BB.passingOxygen(G).reserve,5);assert.equal(G.det,0);assert(!G.wires[fives[0].id].cut);const once=JSON.stringify(G),revision=room.revision;send(0,'本人选第二副本',{a:'resolve',id,w:fives[1].id});assert.equal(room.revision,revision);assert.equal(JSON.stringify(G),once);for(const ws of [...peers,observer]){const V=last(ws,'official:view').view;assert.equal(V.official.passingOxygen.holder,1);assert.equal(V.official.passingOxygen.available,total-5);assert.equal(V.official.passingOxygen.reserve,5);}wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第63关2–5人权威目标／本人各阶段暂停重启凭据重连，扣5后恢复不重复扣或提前交氧，冒用／旧回复拒绝、明确副本与重复命令一次交余量，全员氧气守恒同步；水下聊天拒绝且不广播');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',63),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧氧气'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.passingOxygen(G),null);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.deepEqual(G.mission.rules,saved.mission.rules);assert.equal(G.detMax,saved.detMax);}
}
console.log('✓ 第63关旧版本17改编保存／视图与原任务保持，不追加氧气接力或改变原计时规则');
