// 缺氧通行证界面后段；不作为完整开局或设备自动触发证明。
const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup,resort,budget}=require('./passing-oxygen.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb63-whole-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('缺氧夹具只允许隔离本机服务器');
(async()=>{const G=game(3);setup(G);const tens=G.wires.filter(w=>w.v===10);tens.forEach((w,i)=>{w.o=i<3?1:0;w.s=0;w.info=null;});G.wires.filter(w=>w.o===1&&w.v!==10||w.v===9).forEach(w=>{w.cut=true;w.info=null;});resort(G);budget(G,1,9);G.equip=[{n:16,id:'wire-cutter',used:false}];const code='U'+Date.now().toString(36).slice(-4).toUpperCase(),seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid})),file=path.join(dir,'bb-'+code.toLowerCase()+'.json');G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:63,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),contexts=[],pages=[],errors=[];try{
 for(let pi=0;pi<4;pi++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code,seat:seats[pi]});const p=await ctx.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('#nm').fill(seats[pi]?.name||'缺氧观众');await p.locator('#jcode').fill(code);await p.locator('#btn-join').click();await p.waitForFunction(()=>window.testView?.official?.module==='passing-oxygen');}
 const actor=pages[1],before=JSON.stringify(JSON.parse(fs.readFileSync(file)).G);
 for(let mode=0;mode<2;mode++){assert(await actor.locator('[data-act="passing-oxygen-skip"]').isEnabled());assert.equal(await actor.locator('[data-act="solo"][data-v="10"]').count(),0);assert(await actor.locator('[data-act="val"][data-v="10"]').isDisabled());await actor.locator('#scr-game .card3[data-n="16"],#scr-game .eq[data-n="16"]').click();for(const w of tens.slice(0,2))await actor.locator('#scr-game .slot.can[data-w="'+w.id+'"],#scr-game .tile.can[data-w="'+w.id+'"]').click();assert(await actor.locator('[data-act="eqgo"]').isDisabled());assert((await actor.locator('.act').innerText()).includes('本次需要 10 枚氧气，当前 9 枚，不能支付'));assert.equal(JSON.stringify(JSON.parse(fs.readFileSync(file)).G),before);await actor.locator('[data-act="eqcancel"]').click();if(mode===0)for(const p of pages)await p.locator('#scr-game [data-act="view"]').click();}
 for(const p of pages){assert.equal((await p.evaluate(()=>window.testView)).official.passingOxygen.available,9);assert.equal((await p.evaluate(()=>window.testView)).official.passingOxygen.reserve,9);assert.equal((await p.evaluate(()=>window.testView)).equip[0].used,false);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.deepEqual(errors,[]);console.log('✓ 第63关三人375像素双视图缺氧：氧9／蓝10三根，普通单拆不成立、缺氧跳过可用；通行证选两根后明确费用10／不可支付，确认禁用、换视图／取消不耗牌不扣费，全员预算及快照不变／无异常溢出；后段非开局证明');
 }finally{for(const c of contexts)await c.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
