// 隔离本机整局参考玩法：测试程序可读快照选正确目标，产品客户端仍只收许可视图。
const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),{game}=require('./robot-route.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb59-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('整局参考只允许隔离本机服务器与临时快照');
function fixture(n){const G=game(n,0,100+n),code='W'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid})),file=path.join(dir,'bb-'+code.toLowerCase()+'.json');G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:59,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,file};}
function direction(G){const r=BB.robotRoute(G);let p=null;for(let k=1;k<=G.np;k++){const candidate=(G.turn+k)%G.np;if(G.wires.some(w=>w.o===candidate&&!w.cut&&Number.isInteger(w.v))){p=candidate;break;}}if(p===null)return r.direction;const held=new Set(G.wires.filter(w=>w.o===p&&!w.cut&&Number.isInteger(w.v)).map(w=>w.v)),left=r.row.filter((v,i)=>i<=r.position&&held.has(v)).length,right=r.row.filter((v,i)=>i>=r.position&&held.has(v)).length;return right>=left?1:-1;}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,5]){const data=fixture(n),pages=[],contexts=[];let acts=0,reds=0;try{
  for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'整局路线观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='robot-number-route');}
  let G;while(acts<300){G=JSON.parse(fs.readFileSync(data.file)).G;if(G.phase==='won'||G.phase==='lost')break;const pi=G.phase==='setup'?BB.setupActor(G):G.pending?G.pending.to:G.turn,page=pages[pi],revision=await page.evaluate(()=>window.testRevision);const wire=id=>page.locator('#scr-game .tile.can[data-w="'+id+'"],#scr-game .slot.can[data-w="'+id+'"]');
   if(G.phase==='setup'){const w=G.wires.find(w=>w.o===pi&&!w.cut&&!w.info&&BB.setupInfoAllowed(G,w));await wire(w.id).click();}
   else if(G.pending){const pd=G.pending;if(pd.type==='robot-direction')await page.locator('[data-act="robot-direction"][data-direction="'+direction(G)+'"]').click();else{assert.equal(pd.type,'cut');if(pd.step==='target')await page.locator('[data-act="resolve-target"]').click();else await wire(BB.view(G,pi).pending.choices.at(-1)).click();}}
   else{const own=G.wires.filter(w=>w.o===pi&&!w.cut),r=BB.robotRoute(G);if(own.every(w=>BB.kindOf(w)==='r')){await page.locator('[data-act="red"]').click();reds++;}else if(r.step==='move'){const values=BB.robotRouteValues(G,pi);if(!values.length)await page.locator('[data-act="robot-reverse"]').click();else{values.sort((a,b)=>own.filter(w=>w.v===b).length-own.filter(w=>w.v===a).length||a-b);await page.locator('[data-act="robot-move"][data-v="'+values[0]+'"]').click();}}else{assert.equal(r.step,'cut');const v=r.row[r.position];if(BB.soloOk(G,pi,v))await page.locator('[data-act="solo"][data-v="'+v+'"]').click();else{const target=G.wires.find(w=>w.o!==pi&&!w.cut&&w.v===v);await wire(target.id).click();await page.locator('[data-act="val"][data-v="'+v+'"]').click();}}}
   await page.waitForFunction(old=>window.testRevision>old,revision);const newRevision=await page.evaluate(()=>window.testRevision);await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,newRevision)));acts++;if(acts===30)for(const p of pages)await p.locator('#scr-game [data-act="view"]').click();
  }
  G=JSON.parse(fs.readFileSync(data.file)).G;assert.equal(G.phase,'won');assert(G.wires.every(w=>w.cut));assert.equal(G.officialState.robotRoute.completed.length,12);assert(reds>0,'整局须真实主动公开最后红线');assert.equal(G.det,0);assert(!G.pending);for(const page of pages){await page.waitForFunction(()=>window.testView?.phase==='won');assert.equal(await page.locator('.route-back').count(),12);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  console.log('✓ 第59关'+n+'人加观众375像素真实完整来源发牌整局胜利：'+acts+'个界面动作／'+reds+'次主动红线公开，实际三维切线／途中切换二维、12数字翻背面、全员胜局同步／引爆器0；测试程序用全信息参考选线，不认证推理策略或未解决装备例外');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
