const assert=require('assert'),BB=require('../js/engine'),{game,setup,resort,row,pair}=require('./robot-route.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));}function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let seed=1;seed<=8;seed++){
 const G=game(n,cap,seed),s=G.officialState.robotRoute;assert.equal(G.wires.length,n===2?51:50);assert.equal(G.rmark.n,n===2?3:2);assert.equal(G.rmark.cand.length,n===2?3:3);assert.equal(G.ymark.n,0);assert.equal(G.officialState.robotRoute.row.length,12);assert.equal(new Set(G.officialState.robotRoute.row).size,12);assert.equal(G.officialState.robotRoute.row[G.officialState.robotRoute.position],7);assert.equal(G.officialState.robotRoute.direction,G.officialState.robotRoute.position<6?1:-1);assert(G.equip.every(e=>e.n!==10));assert(G.players.every(p=>p.character.id!=='xy-ray'));setup(G);assert.equal(G.phase,'play');assert.equal(G.officialState.robotRoute.step,'move');assert.equal(G.turn,cap);assert(G.players.every((_,p)=>G.setup[p]===1));assert.equal(G.deadline,null);const views=G.players.map((_,p)=>BB.view(G,p).official);assert(views.every(v=>JSON.stringify(v)===JSON.stringify(views[0])),'公共路线不含私人手牌或合法选项数量');
}
console.log('✓ 第59关2–5人全部队长8种子：48蓝／红2/3及双人已知红3、十二数字随机唯一、从7朝较长侧、排除两种X/Y、初始标记／无倒计时、公共路线一致');
{
 const G=game(3);setup(G);row(G);G.wires.filter(w=>w.v===7).forEach(w=>{w.o=0;w.s=0;w.info=null;});resort(G);const s=G.officialState.robotRoute,id=G.officialState.robotRoute.decisionId;
 reject(G,0,{a:'solo',val:7});reject(G,1,{a:'robot-move',id,val:7});reject(G,0,{a:'robot-move',id:id-1,val:7});reject(G,0,{a:'robot-move',id,val:1.5});act(G,0,{a:'robot-move',id,val:7});assert.equal(G.officialState.robotRoute.position,6);assert.equal(G.officialState.robotRoute.step,'cut');reject(G,0,{a:'solo',val:1});act(G,0,{a:'solo',val:7});assert.equal(G.officialState.robotRoute.step,'direction');assert(G.officialState.robotRoute.completed.includes(7));assert.equal(G.turn,0);assert.equal(G.turnNo,1);const decision=G.pending.id;assert.deepEqual(BB.view(G,0).pending.choices,[-1,1]);assert(!BB.view(G,1).pending.choices);assert(!BB.view(G,-1).pending.choices);reject(G,1,{a:'robot-direction',id:decision,direction:-1});reject(G,0,{a:'robot-direction',id:decision-1,direction:-1});reject(G,0,{a:'robot-direction',id:decision,direction:0});reject(G,0,{a:'equip',n:6});const saved=JSON.parse(JSON.stringify(G));act(G,0,{a:'robot-direction',id:decision,direction:-1});act(saved,0,{a:'robot-direction',id:decision,direction:-1});assert.deepEqual(saved,G);assert.equal(G.officialState.robotRoute.direction,-1);assert.equal(G.turn,1);assert.equal(G.turnNo,2);assert.equal(G.officialState.robotRoute.step,'move');reject(G,0,{a:'robot-direction',id:decision,direction:-1});
}
for(const n of [2,3,4,5]){
 const G=game(n);setup(G);row(G);const ones=pair(G);const move=G.officialState.robotRoute.decisionId;act(G,0,{a:'robot-move',id:move,val:1});act(G,0,{a:'dual',w:ones[2].id,val:1});const id=G.pending.id;assert.equal(G.pending.type,'cut');act(G,1,{a:'resolve',id,w:ones[2].id});assert.equal(G.pending.step,'own');assert.equal(G.officialState.robotRoute.step,'cut');assert.equal(G.wires[ones[2].id].cut,false);act(G,0,{a:'resolve',id,w:ones[1].id});assert(G.wires[ones[1].id].cut);assert(!G.wires[ones[0].id].cut);assert.equal(G.pending.type,'robot-direction');assert.equal(G.det,0);assert(!G.officialState.robotRoute.completed.includes(1));act(G,0,{a:'robot-direction',id:G.pending.id,direction:1});assert.equal(G.turn,1);
}
console.log('✓ 第59关单拆与2–5人真实双拆：移动前／错误值拒绝，目标公开后仍等待本人自由选副本，完整结算后才问朝向，保存一致／重复与越权不变');
{
 const G=game(3);setup(G);row(G);const ones=pair(G);reject(G,0,{a:'dd',val:1,ws:[ones[2].id,ones[3].id]});act(G,0,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:1});act(G,0,{a:'dd',val:1,ws:[ones[2].id,ones[3].id]});const id=G.pending.id;assert.deepEqual(BB.view(G,1).pending.choices,[ones[2].id,ones[3].id]);assert(!BB.view(G,0).pending.choices);assert(!BB.view(G,-1).pending.choices);act(G,1,{a:'resolve',id,w:ones[3].id});assert.equal(G.pending.step,'own');act(G,0,{a:'resolve',id,w:ones[1].id});assert.equal(G.pending.type,'robot-direction');assert(!G.players[0].dd);assert(!G.wires[ones[2].id].cut);assert(!G.wires[ones[0].id].cut);assert.equal(G.det,0);
}
console.log('✓ 第59关双重探测器须先移动，合法多命中只给队友选择；本人选配对副本后才耗本回合并问朝向，未选副本保留');
{
 const G=game(3,0,1,['double-detector','triple-detector','general-radar']);setup(G);row(G);const ones=pair(G);G.wires.filter(w=>w.v===11).forEach(w=>w.cut=true);G.equip=[{n:11,id:'coffee-mug',used:false},{n:3,id:'triple-detector',used:false}];const initial=JSON.stringify(G.officialState.robotRoute);act(G,2,{a:'character',val:1});assert(G.players[2].character.used);assert.equal(JSON.stringify(G.officialState.robotRoute),initial);act(G,0,{a:'equip',n:11,p:1});const third=G.wires.find(w=>w.o===0&&w.s===0&&!w.cut&&w.v!==1),targets=[ones[0].id,ones[1].id,third.id];reject(G,1,{a:'character',ws:targets,val:1});act(G,1,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:1});act(G,1,{a:'character',ws:targets,val:1});const id=G.pending.id;act(G,0,{a:'resolve',id,w:ones[1].id});assert.equal(G.pending.step,'own');act(G,1,{a:'resolve',id,w:ones[3].id});assert.equal(G.pending.type,'robot-direction');assert(G.players[1].character.used);assert.equal(G.equip.find(e=>e.n===3).used,false);assert(G.players[0].dd);assert(!G.wires[ones[0].id].cut);assert(!G.wires[ones[2].id].cut);
}
for(const color of ['b','r']){
 const G=game(3);setup(G);row(G);pair(G);G.wires.filter(w=>w.v===9).forEach(w=>w.cut=true);G.equip=[{n:9,id:'stabilizer',used:false}];const target=G.wires.find(w=>BB.kindOf(w)===color&&w.v!==1&&!w.cut);target.o=1;target.s=0;target.info=null;resort(G);reject(G,0,{a:'equip',n:9});act(G,0,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:1});act(G,0,{a:'dual',w:target.id,val:1,stab:true});act(G,1,{a:'resolve',id:G.pending.id,w:color==='r'?null:target.id});assert.equal(G.phase,'play');assert.equal(G.pending.type,'robot-direction');assert.equal(G.det,0);assert(G.equip[0].used);assert(!G.wires[target.id].cut);if(color==='r')assert.equal(G.wires[target.id].info,null);act(G,0,{a:'robot-direction',id:G.pending.id,direction:1});assert.equal(G.stab,false);assert.equal(G.turn,1);
}
console.log('✓ 第59关额外个人雷达不重置路线，个人三重正确两阶段结算与共享牌／队长双重独立；稳定器保护蓝／红失败后仍选择朝向，罚格零且下一回合保护清除；非反向保护裁定');
for(const fatal of [false,true]){
 const G=game(3);setup(G);row(G);pair(G);const two=G.wires.find(w=>w.v===2);two.o=1;two.s=0;two.info=null;resort(G);G.det=fatal?G.detMax-1:0;act(G,0,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:1});act(G,0,{a:'dual',w:two.id,val:1});act(G,1,{a:'resolve',id:G.pending.id,w:two.id});assert.equal(G.det,fatal?G.detMax:1);assert.equal(G.phase,fatal?'lost':'play');assert.equal(G.pending?.type,fatal?undefined:'robot-direction');assert(G.wires.filter(w=>w.v===1).every(w=>!w.cut));
}
{
 const G=game(3);setup(G);row(G,11,1);G.wires.filter(w=>w.v===12).forEach(w=>{w.o=1;w.s=0;});resort(G);const s=G.officialState.robotRoute,id=G.officialState.robotRoute.decisionId;assert.deepEqual(BB.robotRouteValues(G,0),[]);reject(G,0,{a:'robot-move',id,val:1});reject(G,1,{a:'robot-reverse',id});reject(G,0,{a:'robot-reverse',id,stab:true});act(G,0,{a:'robot-reverse',id});assert.equal(G.det,1);assert.equal(G.officialState.robotRoute.position,11);assert.equal(G.officialState.robotRoute.direction,-1);assert.equal(G.officialState.robotRoute.step,'move');assert(BB.robotRouteValues(G,0).length);reject(G,0,{a:'robot-reverse',id:G.officialState.robotRoute.decisionId});reject(G,0,{a:'robot-move',id,val:BB.robotRouteValues(G,0)[0]});act(G,0,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:BB.robotRouteValues(G,0)[0]});
 const fatal=game(3);setup(fatal);row(fatal,11,1);fatal.wires.filter(w=>w.v===12).forEach(w=>{w.o=1;w.s=0;});resort(fatal);fatal.det=fatal.detMax-1;act(fatal,0,{a:'robot-reverse',id:fatal.officialState.robotRoute.decisionId});assert.equal(fatal.phase,'lost');assert(!fatal.pending);
}
{
 const G=game(3);setup(G);row(G);G.wires.filter(w=>w.v===11).forEach(w=>w.cut=true);G.equip=[{n:11,id:'coffee-mug',used:false}];const s=G.officialState.robotRoute,position=G.officialState.robotRoute.position,direction=G.officialState.robotRoute.direction;act(G,0,{a:'equip',n:11,p:2});assert.equal(G.turn,2);assert.equal(G.officialState.robotRoute.position,position);assert.equal(G.officialState.robotRoute.direction,direction);assert(!G.pending);assert.equal(G.officialState.robotRoute.step,'move');
 const H=game(3);setup(H);row(H);pair(H);H.wires.filter(w=>w.v===11).forEach(w=>w.cut=true);H.equip=[{n:11,id:'coffee-mug',used:false}];act(H,0,{a:'robot-move',id:H.officialState.robotRoute.decisionId,val:1});reject(H,0,{a:'equip',n:11,p:1});
 const R=game(3);setup(R);const red=R.wires.find(w=>BB.kindOf(w)==='r'),owner=red.o;R.wires.filter(w=>w.o===owner&&w.id!==red.id).forEach(w=>w.cut=true);R.turn=owner;act(R,owner,{a:'red'});assert(red.cut);assert(!R.pending);assert.equal(R.det,0);
}
console.log('✓ 第59关安全错误仍选择朝向／最后罚格直接爆炸；仅无可达蓝值可回合开始反向一次罚格，旧决定／修饰拒绝；咖啡杯移动前整回合跳过，普通仅红公开不移动机器人');
{
 const G=game(3);setup(G);row(G);pair(G);G.wires.filter(w=>w.v===6).forEach(w=>w.cut=true);G.equip=[{n:6,id:'rewinder',used:false}];G.det=1;act(G,0,{a:'robot-move',id:G.officialState.robotRoute.decisionId,val:1});const selected=JSON.stringify(G.officialState.robotRoute);act(G,1,{a:'equip',n:6});assert.equal(JSON.stringify(G.officialState.robotRoute),selected);assert.equal(G.det,0);
 for(const n of [2,3,4,5]){const H=game(n);setup(H);row(H);const ones=pair(H);H.wires.forEach(w=>w.cut=true);ones[0].cut=ones[2].cut=false;H.equip=[{n:18,id:'grapple',used:false}];H.officialState.robotRoute.completed=Array.from({length:11},(_,i)=>i+2);act(H,0,{a:'robot-move',id:H.officialState.robotRoute.decisionId,val:1});act(H,1,{a:'equip',n:18,w:ones[0].id});if(H.pending){assert.equal(H.pending.type,'grapple');assert.equal(H.turn,0);act(H,1,{a:'grapple-rack',id:H.pending.id,rack:1});}assert.equal(H.turn,1);assert.equal(H.officialState.robotRoute.step,'move');assert.equal(H.officialState.robotRoute.actor,1);act(H,1,{a:'robot-move',id:H.officialState.robotRoute.decisionId,val:1});act(H,1,{a:'solo',val:1});assert.equal(H.phase,'won');assert.equal(H.det,0);}
}
console.log('✓ 第59关随时倒带不清除已选路线；2–5人抓钩拿走当前玩家最后一根，私人放架后新玩家重新选移动，最后一对单拆真实胜利，无多余朝向或罚格；后段非整局认证');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb59-authority-'));
 function peer(name){return {room:name,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=game(n);setup(G);row(G);const ones=pair(G),own=ones[1].id,target=ones[2].id,name='bb-route'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'路线凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:59,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',{spectator:true,name:'路线观众'});room=service.load(name);G=room.G;}
  function send(p,id,a){service.handle(peers[p],'official:act',{gid:G.gid,revision:room.revision,commandId:id,action:a});}
  function restore(label,answer){service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'暂停',paused:true});const paused=JSON.stringify(G);send(0,label+'暂停回复',answer);assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:label+'继续',paused:false});}
  connect();let move=G.officialState.robotRoute.decisionId;restore('移动前',{a:'robot-move',id:move,val:1});send(0,'向前到1',{a:'robot-move',id:move,val:1});assert.equal(G.officialState.robotRoute.step,'cut');restore('移动后',{a:'dual',w:target,val:1});assert.equal(G.officialState.robotRoute.position,0);const moved=JSON.stringify(G);send(0,'重复旧移动',{a:'robot-move',id:move,val:1});assert.equal(JSON.stringify(G),moved);
  send(0,'路线目标',{a:'dual',w:target,val:1});const id=G.pending.id;restore('目标阶段',{a:'resolve',id,w:target});send(1,'目标确认',{a:'resolve',id,w:target});assert.equal(G.pending.step,'own');assert.equal(G.officialState.robotRoute.step,'cut');restore('本人阶段',{a:'resolve',id,w:own});send(0,'本人选第二副本',{a:'resolve',id,w:own});assert.equal(G.pending.type,'robot-direction');const directionId=G.pending.id;assert.deepEqual(last(peers[0],'official:view').view.pending.choices,[-1,1]);assert(!last(peers[1],'official:view').view.pending.choices);assert(!last(observer,'official:view').view.pending.choices);restore('朝向阶段',{a:'robot-direction',id:directionId,direction:-1});assert.equal(G.pending.id,directionId);const before=JSON.stringify(G);send(1,'冒充朝向',{a:'robot-direction',id:directionId,direction:-1});assert.equal(JSON.stringify(G),before);send(0,'旧朝向',{a:'robot-direction',id:directionId-1,direction:-1});assert.equal(JSON.stringify(G),before);send(0,'确认朝左',{a:'robot-direction',id:directionId,direction:-1});assert.equal(G.turn,1);assert.equal(G.turnNo,2);assert.equal(G.officialState.robotRoute.direction,-1);assert.equal(G.officialState.robotRoute.step,'move');assert.equal(G.det,0);const once=JSON.stringify(G),revision=room.revision;send(0,'确认朝左',{a:'robot-direction',id:directionId,direction:-1});assert.equal(JSON.stringify(G),once);assert.equal(room.revision,revision);for(const ws of [...peers,observer])assert.equal(last(ws,'official:view').view.official.robotRoute.direction,-1);wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 第59关2–5人权威移动前／后、目标／本人／朝向逐阶段暂停重启凭据重连，私人朝向菜单、公共同步／越权旧编号拒绝、重复命令不再换回合');
{
 const M=require('../js/missions');for(const n of [2,3,4,5]){const G=BB.createGame(M.get('campaign',59),Array.from({length:n},(_,i)=>({pid:'legacy'+i,name:'旧路线'+i}))),saved=JSON.parse(JSON.stringify(G));assert.equal(G.ruleset,'custom');assert.equal(G.mission.contentVersion,17);assert(!G.officialState);assert.equal(BB.robotRoute(G),null);assert.deepEqual(BB.view(saved,0),BB.view(G,0));assert.equal(G.players[0].dd,0);}
}
console.log('✓ 第59关旧版17改编保存／许可视图与无个人装备保留，不强行增加机器人路线或迁移正在进行的牌局');
