const assert=require('assert'),fs=require('fs'),path=require('path'),{game,setup,row,pair}=require('./robot-route.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb59-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('路线夹具只允许隔离本机服务器');
function fixture(n){const G=game(n);setup(G);row(G);const ones=pair(G),code='R'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:59,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,own:ones[1].id,other:ones[0].id,target:ones[2].id,last:ones[3].id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'路线观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='robot-number-route');}
  for(let mode=0;mode<2;mode++){for(const page of pages){assert.equal(await page.locator('[data-route-value]').count(),12);assert((await page.locator('[aria-label="机器人数字路线"]').innerText()).includes('朝右'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert(await pages[0].locator('[data-act="robot-move"][data-v="1"]').isVisible());assert.equal(await pages[1].locator('[data-act="robot-move"]').count(),0);if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  if(n%2)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();
  await pages[0].locator('[data-act="robot-move"][data-v="1"]').click();await pages[0].waitForFunction(()=>window.testView?.official?.robotRoute.step==='cut');await pages[0].locator('#scr-game .tile.can[data-w="'+data.target+'"],#scr-game .slot.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="1"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView?.pending?.step==='target')));for(const page of pages)assert(await page.locator('.declared-target[data-w="'+data.target+'"] .target-arrow').count()>0);await pages[1].locator('[data-act="resolve-target"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[0].locator('#scr-game .tile.can[data-w="'+data.own+'"],#scr-game .slot.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView?.pending?.type==='robot-direction')));
  assert.equal(await pages[0].locator('[data-act="robot-direction"]').count(),2);for(const page of pages.slice(1))assert.equal(await page.locator('[data-act="robot-direction"]').count(),0);assert((await pages[0].locator('.turn-notice').innerText()).includes('朝向'));assert.equal((await pages[0].evaluate(()=>window.testView)).players[0].stands.flat().find(w=>w.id===data.other).cut,false);
  await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.pending?.type==='robot-direction');await pages[0].locator('[data-act="robot-direction"][data-direction="-1"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView?.official?.robotRoute.direction===-1&&!window.testView.pending)));
  for(const page of pages){assert.equal((await page.evaluate(()=>window.testView)).turn,1);assert.equal((await page.evaluate(()=>window.testView)).det,0);assert((await page.locator('[aria-label="机器人数字路线"]').innerText()).includes('朝左'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  await pages[1].locator('[data-act="robot-move"][data-v="1"]').click();await pages[1].waitForFunction(()=>window.testView?.official?.robotRoute.step==='cut');await pages[1].locator('#scr-game .tile.can[data-w="'+data.other+'"],#scr-game .slot.can[data-w="'+data.other+'"]').click();await pages[1].locator('[data-act="val"][data-v="1"]').click();await pages[0].waitForFunction(()=>window.testView?.pending?.step==='target');await pages[0].locator('[data-act="resolve-target"]').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[1].locator('#scr-game .tile.can[data-w="'+data.last+'"],#scr-game .slot.can[data-w="'+data.last+'"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView?.official?.robotRoute.completed.includes(1))));
  for(let mode=0;mode<2;mode++){for(const page of pages){assert.equal(await page.locator('[data-route-value]').count(),12);assert.equal(await page.locator('.route-back').count(),1);assert((await page.locator('.route-back[data-route-value="1"]').innerText()).includes('已完成'));assert.equal((await page.evaluate(()=>window.testView)).official.robotRoute.position,0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  console.log('✓ 第59关'+n+'人真实第二次双拆完成四根：全员同步数字牌翻背面／保持十二牌位和机器人原位置，双视图375像素可读无溢出；后段非整局认证');
  console.log('✓ 第59关'+n+'人375像素双视图：12数字路线／移动入口仅本人、公共目标箭头、队友确认／本人选第二副本后私人朝向菜单与轮到本人提示、刷新恢复后全员同步朝左与下一玩家，零罚格；后段非整局证明');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
