const assert=require('assert'),fs=require('fs'),path=require('path'),BB=require('../js/engine'),M=require('../js/missions');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb44-browser-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw new Error('只允许隔离本机测试');
function rng(s){return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296);}
function fixture(n){const code='O'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=Array.from({length:n},(_,i)=>({pid:code+'p'+i,name:'氧气界面'+i,credential:code+'凭证'+i,bot:false}));let G,target,soloValue;
 for(let seed=1;seed<1000;seed++){G=BB.createGame(M.get('official-development',44),seats,{captain:0,rng:rng(seed*104729)});target=G.wires.find(w=>w.o>0&&w.v===9);soloValue=Array.from({length:8},(_,i)=>i+5).find(value=>G.wires.filter(w=>w.o===1&&w.v===value).length===4);if(target&&G.wires.some(w=>w.o===0&&w.v===9)&&G.equip.some(e=>e.n===9)&&(n!==2||soloValue))break;}
 assert(target&&G.equip.some(e=>e.n===9));if(n===2)assert(soloValue);G.catalog=G.mission.catalog='campaign';const observer={pid:code+'watch',name:'氧气观众',credential:code+'观战凭证',perspective:null};fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:44,ruleset:'campaign',attempts:1,started:true,seats,observers:[observer],revision:0,seen:[],G}),{mode:0o600});return {code,seats,observer,target,soloValue};}
(async()=>{const browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(let n=2;n<=5;n++){
  const data=fixture(n),pages=[],contexts=[];let threeD=true;
  try{for(const identity of data.seats.concat([data.observer])){
   const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,identity})=>{localStorage.setItem('bb_name',JSON.stringify(identity.name));localStorage.setItem('bb_pid',JSON.stringify(identity.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:identity.credential}));localStorage.setItem('bb_view3d','true');const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...a){super(...a);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,identity});
   const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(identity.name);await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='shared-oxygen');
  }
  const host=pages[0],observer=pages[n];async function views(){const r=Math.max(...await Promise.all(pages.map(p=>p.evaluate(()=>window.testRevision))));await Promise.all(pages.map(p=>p.waitForFunction(r=>window.testRevision>=r,r)));return Promise.all(pages.map(p=>p.evaluate(()=>window.testView)));}
  async function advance(f){await views();const r=await host.evaluate(()=>window.testRevision);await f();await host.waitForFunction(r=>window.testRevision>r,r);await views();}
  async function wire(pi,id){await pages[pi].locator('#scr-game '+(threeD?'.slot.can':'.tile.can')+'[data-w="'+id+'"]').click();}
  async function toggle(){for(const p of pages)await p.locator('#scr-game [data-act=view]').click();threeD=!threeD;}
  while((await views())[0].phase==='setup'){const v=await views(),pi=BB.setupActor(v[0]),id=v[pi].players[pi].stands.flat().find(w=>!w.cut&&Number.isInteger(w.v)&&!w.info).id;await advance(()=>wire(pi,id));}
  for(let mode=0;mode<2;mode++){for(const p of pages){assert((await p.locator('.oxygen-panel').innerText()).includes(n*2+'／'+n*2));assert(await p.locator('#chatin').isDisabled());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}assert.equal(await observer.locator('[data-act=oxygen-signal]').count(),0);assert.equal(await observer.locator('[data-act=oxygen-skip]').count(),0);await toggle();}
  await advance(()=>pages[n-1].locator('[data-act=oxygen-signal]').click());for(const p of pages)assert((await p.locator('.oxygen-panel').innerText()).includes(data.seats[n-1].name));
  await wire(0,data.target.id);assert((await host.locator('[data-act=val][data-v="9"]').getAttribute('title')).includes('3 枚氧气'));await advance(()=>host.locator('[data-act=val][data-v="9"]').click());let v=await views();assert(v.every(view=>view.official.oxygen.available===n*2-3));
  await observer.locator('#spectator-perspective').selectOption(data.seats[data.target.o].pid);await observer.waitForFunction(pid=>window.testView.perspective===pid,data.seats[data.target.o].pid);assert(!('choices'in (await observer.evaluate(()=>window.testView)).pending));
  await advance(()=>host.locator('[data-act=host-pause]').click());assert.equal(await pages[n-1].locator('[data-act=oxygen-signal]').count(),0);const decision=v[0].pending.id;await pages[data.target.o].reload({waitUntil:'domcontentloaded'});await pages[data.target.o].locator('#jcode').fill(data.code);await pages[data.target.o].locator('#btn-join').click();await pages[data.target.o].waitForFunction(id=>window.testView?.pending?.id===id,decision);assert.equal((await views())[0].official.oxygen.available,n*2-3);await advance(()=>host.locator('[data-act=host-pause]').click());
  await advance(()=>pages[data.target.o].locator('[data-act=resolve-target]').click());const own=(await views())[0].pending.choices.at(-1);await advance(()=>wire(0,own));v=await views();assert.equal(v[0].turn,1);assert.equal(v[0].official.oxygen.available,n*2-3);
  if(n===2){for(const b of await pages[1].locator('[data-act=val]').all()){const value=+(await b.getAttribute('data-v'));if(value>4){assert(await b.isDisabled());assert((await b.getAttribute('title')).includes('当前不足'));}}const solo=pages[1].locator('[data-act=solo][data-v="'+data.soloValue+'"]');assert(await solo.isDisabled());assert((await solo.getAttribute('title')).includes('共享氧气不足'));}
  await pages[1].locator('[data-act=eq][data-n="9"]').click();assert((await pages[1].locator('.act').innerText()).includes('再跳过回合'));await advance(()=>pages[1].locator('[data-act=eqinstant]').click());assert((await views())[0].stab);await advance(()=>pages[1].locator('[data-act=oxygen-skip]').click());v=await views();assert.equal(v[0].det,0);assert(v[0].equip.find(e=>e.n===9).used);assert.equal(v[0].official.oxygen.available,n===2?n*2:n*2-3);
  for(let mode=0;mode<2;mode++){for(const p of pages)assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await toggle();}
  console.log('✓ 第44关开发版'+n+'人＋观众：375像素双视图共享氧气、禁语、拇指请求、扣氧／暂停重连／私人回应、缺氧数字禁用、稳定器跳过与队长补满');
  }finally{for(const c of contexts)await c.close();}
 }assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
