// 单一标签组件隔离联机验收；不是第55关整局验证。
const assert=require('assert'),fs=require('fs'),path=require('path'),{create,unlock}=require('./unique-label.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb55-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('标签夹具只允许隔离本机服务器');
function fixture(n,cap){const G=create(n,cap);unlock(G);G.wires.filter(w=>w.v===4).forEach(w=>{w.cut=true;w.info=null;});G.equip.push({n:4,id:'sticky-note',used:false});G.turn=1;const chosen=G.wires.find(w=>w.o===0&&!w.info&&w.v!==2&&w.v!==4&&Number.isInteger(w.v)&&G.players[0].stands[w.s].filter(id=>G.wires[id].v===w.v).length===1&&G.wires.filter(t=>!t.cut&&t.info?.t==='v'&&t.info.v===w.v).length<2);assert(chosen);const cut=n===4;if(cut)chosen.cut=true;const code='U'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,id:chosen.id,value:chosen.v,cut};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const [n,cap] of [[2,0],[3,0],[3,1],[4,0],[5,0]]){const data=fixture(n,cap),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'唯一标签观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.equip?.some(e=>e.n===14));}
  const A=pages[0];assert.equal(await A.locator('.card3[data-n="14"] .cn').innerText(),'2·2');await A.locator('.card3[data-n="14"]').click();await A.locator('#scr-game .slot.can[data-w="'+data.id+'"]').click();assert(await A.locator('[data-act="eqgo"]').isEnabled());await A.locator('#scr-game [data-act="view"]').click();assert.equal(await A.locator('.eq[data-n="14"] .eq-n').innerText(),'2·2');await A.locator('[data-act="eqgo"]').click();await Promise.all(pages.map(page=>page.waitForFunction(id=>window.testView.players[0].stands.flat().find(w=>w.id===id).unique,data.id)));
  if(!data.cut){await A.locator('.eq[data-n="4"]').click();await A.locator('#scr-game .tile.can[data-w="'+data.id+'"]').click();await A.locator('[data-act="eqgo"]').click();await Promise.all(pages.map(page=>page.waitForFunction(id=>window.testView.players[0].stands.flat().find(w=>w.id===id).info?.t==='v',data.id)));}
  for(let mode=0;mode<2;mode++){for(let p=0;p<pages.length;p++){const page=pages[p],V=await page.evaluate(()=>window.testView),wire=V.players[0].stands.flat().find(w=>w.id===data.id);assert(wire.unique);assert.equal(wire.v,p===0||data.cut?data.value:null);assert.equal(V.turn,1);assert.equal(V.det,0);assert(V.equip.find(e=>e.n===14).used);assert.equal(wire.cut,data.cut);const tile=page.locator('#scr-game [data-w="'+data.id+'"]'),marker=tile.locator('.unique-marker,.unique-marker3');assert.equal(await marker.innerText(),'×1');assert((await marker.getAttribute('aria-label')).includes('含已剪线'));if(!data.cut){assert.equal(wire.info.v,data.value);const info=tile.locator('.tok,.tok3'),a=await marker.boundingBox(),b=await info.boundingBox();assert(a&&b);assert(Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)<=1,JSON.stringify({n,cap,p,mode,a,b,marker:await marker.evaluate(e=>getComputedStyle(e).top),info:await info.evaluate(e=>getComputedStyle(e).top)}));}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  await A.reload({waitUntil:'domcontentloaded'});await A.locator('#jcode').fill(data.code);await A.locator('#btn-join').click();await A.waitForFunction(id=>window.testView?.players[0].stands.flat().find(w=>w.id===id)?.unique,data.id);
  console.log('✓ 单一标签'+n+'人队长 '+cap+'375像素双视图：印刷2·2、'+(data.cut?'允许已剪线':'隐藏值不传／数字与×1同时显示不重叠')+'、非回合使用、不耗回合、观战同步及刷新保留；组件非整关');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
