const assert=require('assert'),BB=require('../js/engine'),Bot=require('../js/bot'),{create,unlock,target}=require('./unique-label.fixture');
function act(G,p,a){assert.equal(BB.act(G,p,a),null,JSON.stringify(a));}function reject(G,p,a){const before=JSON.stringify(G);assert(BB.act(G,p,a));assert.equal(JSON.stringify(G),before);}
assert.equal(BB.EQUIP[14].id,'unique-label');assert.equal(BB.equipmentLabel(14),'2·2');assert.deepEqual(BB.equipProgress(14),{value:2,count:4,printed:'2·2'});
for(const n of [2,3,4,5])for(let cap=0;cap<n;cap++)for(let actor=0;actor<n;actor++){
 const G=create(n,cap,actor),chosen=target(G,actor);assert(chosen);const id=chosen.id,value=chosen.v;G.wires.filter(w=>w.v===2).slice(0,2).forEach(w=>w.cut=true);reject(G,actor,{a:'equip',n:14,w:id});unlock(G);const other=G.wires.find(w=>w.o!==actor&&!w.cut);reject(G,actor,{a:'equip',n:14,w:other.id});reject(G,actor,{a:'equip',n:14,w:id,stab:true});
 const turn=G.turn,turnNo=G.turnNo,card=JSON.stringify(G.players[actor].character);G.wires[id].info={t:'v',v:value};const saved=JSON.parse(JSON.stringify(G));act(G,actor,{a:'equip',n:14,w:id});act(saved,actor,{a:'equip',n:14,w:id});assert.deepEqual(saved,G);assert.equal(G.turn,turn);assert.equal(G.turnNo,turnNo);assert.equal(G.det,0);assert.equal(G.pending,null);assert(G.equip[0].used);assert(G.wires[id].unique);assert.deepEqual(G.wires[id].info,{t:'v',v:value});assert.equal(JSON.stringify(G.players[actor].character),card);assert.equal(BB.uniqueMarkerCount(G),1);
 for(let viewer=-1;viewer<n;viewer++){const V=BB.view(G,viewer),w=V.players[actor].stands.flat().find(w=>w.id===id);assert(w.unique);assert.equal(w.v,viewer===actor?value:null);assert.equal(BB.uniqueMarkerCount(V),1);const unpacked=BB.unpack(BB.packPublic(G),BB.packHand(G,viewer),viewer),copy=unpacked.players[actor].stands.flat().find(w=>w.id===id);assert(copy.unique);assert.equal(copy.v,viewer===actor?value:null);assert.deepEqual(copy.info,{t:'v',v:value});}reject(G,actor,{a:'equip',n:14,w:id});
}
console.log('✓ 单一标签2–5人所有队长／使用者：四根2解锁、非回合使用、整架唯一蓝值、数字标记同时保留、一次用卡／不耗回合／角色独立；保存恢复及私有手牌／公共×1／紧凑包兼容通过');
{
 const G=create(3),id=target(G,0).id;unlock(G);G.wires[id].cut=true;act(G,0,{a:'equip',n:14,w:id});assert(G.wires[id].unique);assert.equal(BB.view(G,1).players[0].stands.flat().find(w=>w.id===id).v,G.wires[id].v);
 const duplicate=create(3),w=target(duplicate,0),same=duplicate.wires.find(t=>t.id!==w.id&&t.v===w.v);unlock(duplicate);same.o=0;same.s=w.s;same.cut=true;duplicate.players.forEach((p,owner)=>p.stands=p.stands.map((_,rack)=>duplicate.wires.filter(t=>t.o===owner&&t.s===rack).map(t=>t.id)));reject(duplicate,0,{a:'equip',n:14,w:w.id});
 const separate=create(2),s=target(separate,0),copy=separate.wires.find(t=>t.id!==s.id&&t.v===s.v);unlock(separate);copy.o=0;copy.s=1-s.s;separate.players.forEach((p,owner)=>p.stands=p.stands.map((_,rack)=>separate.wires.filter(t=>t.o===owner&&t.s===rack).map(t=>t.id)));act(separate,0,{a:'equip',n:14,w:s.id});
 for(const value of [1.1,1.5]){const special=create(3),id=target(special,0).id;unlock(special);special.wires[id].v=value;reject(special,0,{a:'equip',n:14,w:id});}
}
console.log('✓ 单一标签允许已剪蓝线；同架同值已剪副本仍阻止使用，另一架同值不阻止；黄／红拒绝，不公开未剪数值');
{
 function stock(){const G=create(5),id=target(G,0).id;unlock(G);G.wires[id].info=null;const candidates=G.wires.filter(w=>w.id!==id&&!w.cut&&Number.isInteger(w.v)).slice(0,7);candidates.forEach(w=>w.unique=true);assert.equal(BB.uniqueMarkerCount(G),7);return {G,id,candidates};}
 const {G,id}=stock();act(G,0,{a:'equip',n:14,w:id});assert.equal(BB.uniqueMarkerCount(G),7);assert(!G.wires[id].unique);assert(G.announcement.frequencyOnly);assert.equal(G.announcement.id,id);const before=JSON.stringify(G);reject(G,0,{a:'equip',n:14,w:id});assert.equal(JSON.stringify(G),before);G.equip.push({n:4,id:'sticky-note',used:false});G.wires.filter(w=>w.v===4).slice(0,2).forEach(w=>w.cut=true);const next=G.wires.find(w=>w.o===0&&!w.cut&&!w.info&&Number.isInteger(w.v));act(G,0,{a:'equip',n:4,w:next.id});assert.equal(G.announcement?.frequencyOnly||false,false);
 const reused=stock(),old=reused.candidates[0].id;reused.G.wires[old].cut=true;act(reused.G,0,{a:'equip',n:14,w:reused.id});assert(reused.G.wires[reused.id].unique);assert(!reused.G.wires[old].unique);assert.equal(BB.uniqueMarkerCount(reused.G),7);
}
console.log('✓ 构造7枚×1供给边界：无额外副本、临时口头声明错误后保留／下一有效动作移除、移动已剪标记到新线而非复制；不认证实际开局可耗尽供给');
{
 const G=create(3),id=target(G,0).id;unlock(G);G.wires[id].info=null;act(G,0,{a:'equip',n:14,w:id});G.officialState={version:1,module:'personal-constraints',constraints:{kind:'personal',personal:[{id:'H',retired:false},{id:'H',retired:false},null],available:[],enteredTurn:G.turnNo}};assert(!BB.targetAllowed(G,1,G.wires[id]));assert(!BB.soloAllowed(G,0,[G.wires[id]]));
 const trade=create(3),w=target(trade,0);unlock(trade);act(trade,0,{a:'equip',n:14,w:w.id});trade.equip.push({n:2,id:'walkie-talkies',used:false});const exchange=trade.wires.find(t=>t.o===0&&!t.cut&&t.id!==w.id&&t.v!==w.v),receive=trade.wires.find(t=>t.o===1&&!t.cut&&t.v!==2);exchange.s=w.s;trade.players.forEach((p,owner)=>p.stands=p.stands.map((_,rack)=>trade.wires.filter(t=>t.o===owner&&t.s===rack).sort((a,b)=>a.v-b.v||a.id-b.id).map(t=>t.id)));act(trade,0,{a:'equip',n:2,w:exchange.id,p:1});act(trade,1,{a:'walkie',id:trade.pending.id,w:receive.id});assert(!trade.wires[w.id].unique,'改变线架后，不让旧×1继续作为当前架的数量事实');
}
console.log('✓ ×1属于已标记线，限制H不能选；开发版线架交换使受影响×1失效，防止把旧架数量当新架事实；物理移动例外仍待核实');
{
 // 极小公开推理模型，用来隔离×1信息约束，不是任务55发牌证明。
 const G=create(3);G.mission.blue=[1,3];G.rmark={n:0,cand:[]};G.wires=[];G.players.forEach(p=>p.stands=p.stands.map(()=>[]));const tiles=[{v:1,o:1,cut:true},{v:1,o:0,cut:false},{v:1,o:2,cut:false},{v:1,o:2,cut:false},...Array.from({length:4},()=>({v:2,o:0,cut:true})),{v:3,o:1,cut:false},{v:3,o:1,cut:false},{v:3,o:0,cut:true},{v:3,o:0,cut:true}];tiles.forEach((t,id)=>{G.wires.push({id,...t,s:0,info:null});G.players[t.o].stands[0].push(id);});G.wires[0].unique=true;
 const prior=Math.random;try{let seed=12345;Math.random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const before=JSON.stringify(G),p=Bot.infer(G,0,5000);assert.equal(p[8].P[1]||0,0);assert.equal(p[9].P[1]||0,0);assert.equal(p[8].P[3],1);assert.equal(p[9].P[3],1);assert.equal(JSON.stringify(G),before);delete G.wires[0].unique;G.announcement={id:0,info:{t:'freq',v:1},frequencyOnly:true};const verbal=Bot.infer(G,0,5000);assert.equal(verbal[8].P[1]||0,0);assert.equal(verbal[8].P[3],1);}finally{Math.random=prior;}
 for(const n of [2,3,4,5]){const G=create(n);unlock(G);const a=Bot.decide(G,0,()=>.5);assert.equal(a.a,'equip');assert.equal(a.n,14);const alternative=JSON.parse(JSON.stringify(G));alternative.wires.filter(w=>w.o!==0&&!w.cut).forEach(w=>w.v=8);assert.deepEqual(Bot.decide(alternative,0,()=>.5),a);act(G,0,a);assert(G.equip[0].used);}
}
console.log('✓ 机器人×1推理计入已剪线、不会给同架剩余线分配该值，临时口头×1同样有效；不修改状态，主动放标仅看本人手牌／公开装备，隐藏值变化不影响决定');
{
 const fs=require('fs'),os=require('os'),path=require('path'),Service=require('../server/official'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bb55-unique-authority-'));
 function peer(room){return {room,readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));}};}function last(ws,t){return ws.messages.filter(m=>m.topic===t).at(-1)?.data;}
 try{for(const n of [2,3,4,5]){
  let G=create(n);unlock(G);G.turn=1;const id=target(G,0,true).id,value=G.wires[id].v,name='bb-unique'+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:'唯一标签凭据'+p.pid})),wss={clients:new Set()};G.catalog=G.mission.catalog='campaign';fs.writeFileSync(path.join(dir,name+'.json'),JSON.stringify({version:1,name,host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}));let service=Service(wss,dir),room,peers,observer,credential;
  function connect(){peers=seats.map(s=>{const ws=peer(name);wss.clients.add(ws);service.handle(ws,'hello',{credential:s.credential,name:s.name});return ws;});observer=peer(name);wss.clients.add(observer);service.handle(observer,'hello',credential?{credential,name:'唯一标签观众'}:{spectator:true,name:'唯一标签观众'});credential=last(observer,'official:welcome').credential;room=service.load(name);G=room.G;}
  function send(p,commandId,action,revision=room.revision){service.handle(peers[p],'official:act',{gid:G.gid,revision,commandId,action});}
  connect();service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'暂停唯一标签',paused:true});const paused=JSON.stringify(G);send(0,'暂停时标签',{a:'equip',n:14,w:id});assert.equal(JSON.stringify(G),paused);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.paused);assert(!G.equip[0].used);service.handle(peers[0],'official:pause',{gid:G.gid,revision:room.revision,commandId:'继续唯一标签',paused:false});
  const before=JSON.stringify(G);send(1,'冒用标记别人的线',{a:'equip',n:14,w:id});assert.equal(JSON.stringify(G),before);service.handle(observer,'official:act',{gid:G.gid,revision:room.revision,commandId:'观战标记',action:{a:'equip',n:14,w:id}});assert.equal(JSON.stringify(G),before);const turn=G.turnNo,revision=room.revision;send(0,'合法唯一标签',{a:'equip',n:14,w:id});assert.equal(room.revision,revision+1);assert(G.wires[id].unique);assert.equal(G.turn,1);assert.equal(G.turnNo,turn);assert.equal(G.det,0);
  for(const ws of [...peers,observer]){const V=last(ws,'official:view').view,w=V.players[0].stands.flat().find(w=>w.id===id);assert(w.unique);assert.equal(w.v,ws===peers[0]?value:null);assert.equal(w.info,null);}
  const done=JSON.stringify(G),rev=room.revision;send(0,'合法唯一标签',{a:'equip',n:14,w:id},revision);assert.equal(JSON.stringify(G),done);assert.equal(room.revision,rev);send(0,'旧修订标签',{a:'equip',n:14,w:id},revision);assert.equal(JSON.stringify(G),done);assert.equal(room.revision,rev);wss.clients.forEach(ws=>ws.readyState=3);service=Service(wss,dir);connect();assert(G.equip[0].used);assert(G.wires[id].unique);assert.equal(G.turnNo,turn);wss.clients.forEach(ws=>ws.readyState=3);
 }}finally{fs.rmSync(dir,{recursive:true,force:true});}
}
console.log('✓ 单一标签2–5人权威服务：非回合使用、公开×1不传隐藏数字、暂停重启／凭据重连、角色／观战／旧修订／重复拒绝，单次修订且不推进回合；使用后标记和卡状态重启保留');
