// 单剪通行证组件的隔离联机检查；不认证第55关整局。
const assert=require('assert'),fs=require('fs'),path=require('path'),{create,unlock}=require('./vip-pass.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb55-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('通行证夹具只允许隔离本机服务器');
function fixture(n,cap){const G=create(n,cap);unlock(G);const copies=G.wires.filter(w=>w.o===0&&w.v===2).map(w=>w.id),wrong=G.wires.find(w=>w.o===0&&!w.cut&&w.v!==2&&Number.isInteger(w.v)),code='V'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:55,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,ids:copies.slice(1),remaining:copies[0],wrong:wrong.id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{
 for(const [n,cap] of [[2,0],[3,0],[3,1],[4,0],[5,0]]){const data=fixture(n,cap),contexts=[],pages=[];try{
  for(let p=0;p<=n;p++){const context=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(context);await context.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view'){window.testView=m.data.view;window.testRevision=m.data.revision;}}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'通行证观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.equip?.some(e=>e.n===16));}
  const A=pages[0],before=await A.evaluate(()=>window.testRevision);assert.equal(await A.locator('.card3[data-n="16"] .cn').innerText(),'9·9');await A.locator('.card3[data-n="16"]').click();await A.locator('#scr-game .slot.can[data-w="'+data.ids[0]+'"]').click();await A.locator('#scr-game .slot.can[data-w="'+data.wrong+'"]').click();assert(await A.locator('[data-act="eqgo"]').isDisabled());assert.equal(await A.evaluate(()=>window.testRevision),before);await A.locator('#scr-game .slot.can[data-w="'+data.wrong+'"]').click();await A.locator('#scr-game .slot.can[data-w="'+data.ids[1]+'"]').click();assert(await A.locator('[data-act="eqgo"]').isEnabled());
  await A.locator('#scr-game [data-act="view"]').click();assert.equal(await A.locator('.eq[data-n="16"] .eq-n').innerText(),'9·9');assert.equal(await A.locator('.tile.sel').count(),2);await A.locator('[data-act="eqgo"]').click();await Promise.all(pages.map(page=>page.waitForFunction(()=>window.testView.declaration?.type==='vip-cut')));
  for(let mode=0;mode<2;mode++){for(let p=0;p<pages.length;p++){const page=pages[p],V=await page.evaluate(()=>window.testView);assert.deepEqual(V.declaration.ids,data.ids);assert(V.equip.find(e=>e.n===16).used);assert.equal(V.turn,1);assert.equal(V.det,0);assert(V.players[0].stands.flat().filter(w=>data.ids.includes(w.id)).every(w=>w.cut&&w.v===2));const remaining=V.players[0].stands.flat().find(w=>w.id===data.remaining);assert(!remaining.cut);assert.equal(remaining.v,p===0?2:null);assert((await page.locator('.vip-notice').innerText()).includes('两根'));for(const id of data.ids)assert.equal(await page.locator('.declared-target[data-w="'+id+'"] .target-arrow').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(mode===0)for(const page of pages)await page.locator('#scr-game [data-act="view"]').click();}
  await A.reload({waitUntil:'domcontentloaded'});await A.locator('#jcode').fill(data.code);await A.locator('#btn-join').click();await A.waitForFunction(()=>window.testView?.equip?.find(e=>e.n===16)?.used);assert.equal((await A.evaluate(()=>window.testView)).players[0].stands.flat().find(w=>w.id===data.remaining).cut,false);
  console.log('✓ 通行证'+n+'人队长 '+cap+'375像素双视图：印刷9·9、不同值确认禁用、选择后两根／跨架、所选两箭头公开、未选副本保留、一次耗牌回合及刷新恢复、观战只读；组件非整关');
 }finally{for(const c of contexts)await c.close();}}
 assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
