const assert=require('assert'),fs=require('fs'),path=require('path'),F=require('./weak-link.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb34-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('抢回合夹具只允许隔离本机服务器');
function fixture(n){const G=F.nonweakGame(n);F.setup(G);const code='F'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:34,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,owner:G.officialState.weakLink.owner,card:G.officialState.weakLink.cards[G.officialState.weakLink.owner],roles:G.players.map(p=>p.character.id)};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(const n of [3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
 for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'轮序观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='secret-weak-link');}
 for(let pi=0;pi<n;pi++){const V=await pages[pi].evaluate(()=>window.testView);assert.equal(V.official.weakLink.ownWeak,pi===data.owner);assert.equal(V.players[pi].character.id,data.roles[pi]);assert(V.players[pi].character.locked);for(let p=0;p<n;p++)if(p!==pi)assert(V.players[p].character.hidden);assert(await pages[pi].locator('[aria-label="秘密弱环节"] .private-choice').count());assert.equal(await pages[pi].locator('[data-act="personal"]').count(),0);assert.equal(await pages[pi].locator('[data-m="dd"]').count(),0);}
 await pages[n].locator('#spectator-perspective').selectOption('p'+data.owner);
 // 观战切视角仍不能看到秘密角色或弱环节身份。
 await pages[n].waitForFunction(owner=>window.testView?.perspective==='p'+owner,data.owner);const publicV=await pages[n].evaluate(()=>window.testView);assert(!('ownWeak' in publicV.official.weakLink));assert(publicV.players.every(p=>p.character.hidden));assert.equal(await pages[n].locator('[aria-label="秘密弱环节"] .private-choice').count(),0);assert.equal(await pages[n].locator('[data-act="weak-confirm"]').count(),0);
 for(const page of pages){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#scr-game [data-act="view"]').click();}
 await pages[0].reload({waitUntil:'domcontentloaded'});await pages[0].locator('#jcode').fill(data.code);await pages[0].locator('#btn-join').click();await pages[0].waitForFunction(()=>window.testView?.official?.weakLink?.startPending);assert((await pages[0].locator('[aria-label="秘密弱环节"]').innerText()).includes('你不是弱环节'));
 await pages[0].locator('[data-act="weak-player"][data-p="'+data.owner+'"]').click();await pages[0].locator('[data-act="weak-constraint"][data-id="'+data.card+'"]').click();await pages[0].locator('[data-act="weak-confirm"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.weakLink?.status==='revealed')));
 for(const page of pages){await page.waitForFunction(()=>document.querySelector('[aria-label="秘密弱环节"]')?.innerText.includes('个人装备已解锁'));const V=await page.evaluate(()=>window.testView);assert.deepEqual(V.players.map(p=>p.character.id),data.roles);assert.equal(V.det,0);assert(V.players.every(p=>!p.character.used&&!p.character.removed&&!p.character.hidden));assert((await page.locator('[aria-label="秘密弱环节"]').innerText()).includes('个人装备已解锁'));assert.equal(await page.locator('[data-act="weak-confirm"]').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 console.log('✓ 第34关'+n+'人加观众375像素三维到二维：本人秘密角色／身份／限制、其他角色背面及个人装备禁用、观战换其视角无秘密、开始决定刷新恢复、真实猜对两要素后全员原角色公开／解锁／零罚格、无异常溢出；未认证整局');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
