const assert=require('assert'),fs=require('fs'),path=require('path'),F=require('./yellow-before-x.fixture');
const {chromium}=require(process.env.BB_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BB_BROWSER_URL||'http://127.0.0.1:9123',dir=process.env.BB_TEST_DATA_DIR||'/tmp/bb35-test-data';
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(base)||!dir.startsWith('/tmp/'))throw Error('抢回合夹具只允许隔离本机服务器');
function fixture(n){const f=F.lastYellow(n),G=f.G;const code='F'+Date.now().toString(36).slice(-4).toUpperCase()+n,seats=G.players.map(p=>({pid:p.pid,name:p.name,bot:false,credential:code+'凭据'+p.pid}));G.catalog=G.mission.catalog='campaign';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bb-'+code.toLowerCase()+'.json'),JSON.stringify({version:1,name:'bb-'+code.toLowerCase(),host:seats[0].pid,mid:35,ruleset:'campaign',attempts:1,started:true,seats,observers:[],revision:0,seen:[],G}),{mode:0o600});return {code,seats,x:f.x.id,value:f.x.v,matching:f.matching.id,own:f.own.id,target:f.target.id};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.BB_CHROMIUM||'/snap/bin/chromium',headless:true,args:['--no-sandbox']}),errors=[];try{for(const n of [2,3,4,5]){const data=fixture(n),contexts=[],pages=[];try{
 for(let p=0;p<=n;p++){const ctx=await browser.newContext({viewport:{width:375,height:820},reducedMotion:'reduce'});contexts.push(ctx);await ctx.addInitScript(({code,seat})=>{localStorage.setItem('bb_view3d','true');if(seat){localStorage.setItem('bb_pid',JSON.stringify(seat.pid));localStorage.setItem('bb_officialCredentials',JSON.stringify({[code]:seat.credential}));}const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.topic==='official:view')window.testView=m.data.view;}catch(_){}});}};},{code:data.code,seat:data.seats[p]});const page=await ctx.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#nm').fill(data.seats[p]?.name||'轮序观众');await page.locator('#jcode').fill(data.code);await page.locator('#btn-join').click();await page.waitForFunction(()=>window.testView?.official?.module==='yellow-before-x');}
 async function reload(p){await pages[p].reload({waitUntil:'domcontentloaded'});await pages[p].locator('#jcode').fill(data.code);await pages[p].locator('#btn-join').click();await pages[p].waitForFunction(()=>window.testView?.official?.module==='yellow-before-x');}
 for(const page of pages){assert((await page.locator('.x-notice').innerText()).includes('2/4'));assert((await page.locator('.x-notice').innerText()).includes('仍锁定'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await pages[0].locator('.slot.can[data-w="'+data.target+'"]').click();await pages[0].locator('[data-act="val"][data-v="Y"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='target')));await reload(1);await pages[1].locator('[data-act="resolve-target"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='own')));
 for(const page of pages)assert((await page.evaluate(()=>window.testView)).official.yellowBeforeX.locked);assert.equal(await pages[n].locator('.can[data-w="'+data.own+'"]').count(),0);await reload(0);await pages[0].locator('.slot.can[data-w="'+data.own+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.official?.yellowBeforeX?.cut===4)));
 for(const page of pages){await page.waitForFunction(()=>document.querySelector('.x-notice')?.innerText.includes('X线已解锁'));await page.locator('#scr-game [data-act="view"]').click();}
 // 下一位以队友X为目标，正常两阶段拆掉最后一对蓝线。
 await pages[1].locator('.tile.can[data-w="'+data.x+'"]').click();await pages[1].locator('[data-act="val"][data-v="'+data.value+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.pending?.step==='target')));await pages[0].locator('[data-act="resolve-target"]').click();await pages[1].waitForFunction(()=>window.testView?.pending?.step==='own');await pages[1].locator('.tile.can[data-w="'+data.matching+'"]').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.testView?.phase==='won')));
 for(const page of pages){const V=await page.evaluate(()=>window.testView);assert.equal(V.det,0);assert.equal(V.official.yellowBeforeX.cut,4);assert.equal(V.official.yellowBeforeX.locked,false);assert(V.players.flatMap(p=>p.stands.flat()).every(w=>w.cut));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 console.log('✓ 第35关'+n+'人加观众375像素实际三维到二维：最后黄对目标／本人两阶段各刷新恢复，未完成配对仍锁定、4/4全员解锁、随后平面真实双拆队友X及本人匹配线获胜，观战无私有选择、零罚格、无异常溢出；构造后段非整局');
 }finally{for(const c of contexts)await c.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
