// 只代理服务端已核实清单登记的录音指纹，缓存放在私有数据目录。
const fs=require('fs'),path=require('path'),https=require('https'),crypto=require('crypto'),{Transform}=require('stream'),{pipeline}=require('stream/promises');
const limit=64*1024*1024;
function trusted(url){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&['cdn.pegasus.de','cocktailgames.com','www.cocktailgames.com'].includes(u.hostname);}catch(_){return false;}}
async function response(url,redirects=0){if(!trusted(url)||redirects>3)throw Error('录音地址无效');const res=await new Promise((resolve,reject)=>{const req=https.get(url,resolve);req.on('error',reject);req.setTimeout(30000,()=>req.destroy(Error('录音下载超时')));});if([301,302,303,307,308].includes(res.statusCode)){res.resume();if(!res.headers.location)throw Error('录音重定向无效');return response(new URL(res.headers.location,url).href,redirects+1);}if(res.statusCode!==200){res.resume();throw Error('录音下载失败');}return res;}
async function fetchTo(url,file){const res=await response(url);let bytes=0;const guard=new Transform({transform(chunk,encoding,done){bytes+=chunk.length;if(bytes>limit)return done(Error('录音超出大小限制'));done(null,chunk);}});await pipeline(res,guard,fs.createWriteStream(file,{flags:'wx',mode:0o600}));}
async function fingerprint(file){const stat=await fs.promises.stat(file);if(!stat.isFile()||stat.size>limit)throw Error('录音缓存无效');const hash=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(file))hash.update(chunk);return hash.digest('hex');}
module.exports=function create(options){const dir=options.dir,resolve=options.resolve,download=options.fetchTo||fetchTo,pending=new Map();fs.mkdirSync(dir,{recursive:true,mode:0o700});
 async function ensure(asset){const hash=asset.sha256;if(pending.has(hash))return pending.get(hash);const promise=(async()=>{const target=path.join(dir,hash+'.mp3');try{if(await fingerprint(target)===hash)return target;}catch(_){}await fs.promises.rm(target,{force:true});const temp=path.join(dir,hash+'-'+crypto.randomUUID()+'.part');try{await download(asset.url,temp);if(await fingerprint(temp)!==hash)throw Error('录音指纹不匹配');await fs.promises.rename(temp,target);return target;}finally{await fs.promises.rm(temp,{force:true});}})();pending.set(hash,promise);try{return await promise;}finally{pending.delete(hash);}}
 return {async handle(req,res,pathname){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','text/plain; charset=utf-8');const match=/^\/audio\/([a-f0-9]{64})\.mp3$/.exec(pathname);if(!match){res.writeHead(404);res.end('未找到录音');return;}if(!['GET','HEAD'].includes(req.method)){res.writeHead(405,{Allow:'GET, HEAD'});res.end();return;}if(req.url.includes('?')){res.writeHead(400);res.end('录音请求不接受额外参数');return;}let asset;try{asset=resolve(match[1]);}catch(_){asset=null;}if(!asset||asset.sha256!==match[1]||!trusted(asset.url)){res.writeHead(404);res.end('录音尚未核实或不可用');return;}try{const file=await ensure(asset),stat=await fs.promises.stat(file);if(res.destroyed)return;res.writeHead(200,{'Content-Type':'audio/mpeg','Content-Length':stat.size,'Cache-Control':'public, max-age=31536000, immutable',ETag:'"'+asset.sha256+'"','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')res.end();else{const stream=fs.createReadStream(file);stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res);}}catch(_){if(!res.headersSent){res.writeHead(502,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});res.end('录音暂时不可用，请稍后重试。');}else res.destroy();}}};
};
